### ISSUE TITLE
Skip test stages via boolean

### ISSUE THREAD

**Issue by dkirrane** [gruntwork-io/terratest#1014]
Is there a way to skip test stages using a boolean.

If I have this stage:
```
	defer test_structure.RunTestStage(t, "destroy", func() {
		destroy(t, workingDir)
	})
```

I want:

- `export SKIP_destroy="true"` to skip the stage

- `export SKIP_destroy="false"` to run the stage

**Comment by infraredgirl** [comment]
Hi @dkirrane - yes, that should work. Are you having any issues getting it to work?

**Comment by dkirrane** [comment]
@infraredgirl yes that was a typo on my part.
For me setting `SKIP_destroy` `true` or `false` the destroy stage is always skipped

The only way to run the destroy stage was to actually unset the variable? Is that expected behaviour?
`unset SKIP_destroy` and the destroy stage will run
