### ISSUE TITLE
Idea: Test util for watching for intermittent request issues

### ISSUE THREAD

**Issue by jimmiebtlr** [gruntwork-io/terratest#1018]
Wondering how you would test zero downtime deployments?

The approach I'm taking at the moment is sending a bunch of requests while doing some deploys and checking status codes of requests sent during that period.  If that approach sounds useful, I can cleanup my code and submit a pr.

The test util function signature I have in mind would be something along the lines of 
```
// HttpDoMany sends requests to url in a loop.  workers number of go routines are started up and 
// send requests in  a loop until isDone is true.
HttpDoMany(workers int, url string, isDone *bool) (statusCodeCounts map[int]int)
```

**Comment by zackproser** [comment]
Hi @jimmiebtlr - thanks for the issue!

Wondering if you've already seen https://github.com/gruntwork-io/terratest/blob/7bbcd3a4734cc2d41edb61a6c4f66a2043e83c0a/modules/http-helper/http_helper.go#L187 ? or the other similar convenience functions in the package? 

Do any of these satisfy your requirements?
