### ISSUE TITLE
no framework available in Terratest for Huawei Cloud API

### ISSUE THREAD

**Issue by atois** [gruntwork-io/terratest#1022]
In Terraform Automation Testing,there is no framework available in Terratest for Huawei Cloud API.
Is there any work in Progress for this?

**Comment by yorinasub17** [comment]
Hi thanks for the feature request. Unfortunately, we don't have plans to maintain cloud frameworks beyond AWS, Azure, and GCP at this moment. See [our guidelines on Infrastructure Validation Helpers contributions](https://terratest.gruntwork.io/docs/community/contributing/#infrastructure-and-validation-helpers) for more info.
