### ISSUE TITLE
AWS Module Package Has Not Been Updated With Get Tags for Subnets Changes in Latest Build

### ISSUE THREAD

**Issue by NeurogrammerT** [gruntwork-io/terratest#1025]
Hi, I'm currently using the aws module to do various tests on aws resource tags. I see that the change has been made to add a GetTagsForSubnets function to the module, and I see this latest change has been merged to master. However, it seems the actual build of the package and deployment to the website has no been completed. This is causing issues because the compiler is telling me the GetTagsForSubnets function doesn't exist, but I can see it does in the master repo. This repo needs to be pushed to a new build for the compiler to recognize this change. I see a new build was pushed for this change, but it appears to have failed. I think it needs to be pushed again. So, is this something that will be done soon? I really need this function to conclude my testing. Is there some way to import this master branch aws module as a workaround until a new build is made? I'm not sure who to contact, but if someone could at least get back to me on this asap, I'd appreciate it.

**Comment by yorinasub17** [comment]
Thanks for the report. A new release has been cut with the feature set: https://github.com/gruntwork-io/terratest/releases/tag/v0.38.3

**Comment by NeurogrammerT** [comment]
> Thanks for the report. A new release has been cut with the feature set: https://github.com/gruntwork-io/terratest/releases/tag/v0.38.3

Awesome, thanks for the quick response!
