### ISSUE TITLE
Add `logger.Logf` message to `ssh.runSSHCommand`

### ISSUE THREAD

**Issue by wjam** [gruntwork-io/terratest#104]
I've been using Terratest in anger recently and have spotted a few things about the library.

Adding a log message to the `runSSHCommand` method would mean that when `CheckSshCommand` fails, you aren't just left with a message of how the exit status for some command wasn't 0. An example can be found in `RunCommandAndGetOutputE` which makes it easier to track what went wrong when a test fails.

Use case: It's difficult to track down what failed when executing numerous `CheckSshCommand` when testing an AMI

**Comment by brikis98** [comment]
+1. We've hit this before too. PR to fix it would be very welcome.
