### ISSUE TITLE
Unsupported State Format Version - terraform-json

### ISSUE THREAD

**Issue by FooBartn** [gruntwork-io/terratest#1043]
**Problem**

Running a InitAndPlanAndShowStruct with Terraform version 1.1.2 results in:

```
Error:          Received unexpected error:
                    unsupported state format version: expected ["0.1" "0.2"], got "1.0"
```

The current terraform-json dependency is at 0.12

**Resolution**

bump terraform-json dependency to 0.13

**Comment by andy-caruso** [comment]
There's a [PR](https://github.com/gruntwork-io/terratest/pull/1039) for this, looks like it has some issues with tests though

**Comment by yorinasub17** [comment]
Released as https://github.com/gruntwork-io/terratest/releases/tag/v0.38.9
