### ISSUE TITLE
Upgrade to docker compose v2.x

### ISSUE THREAD

**Issue by yariksheptykin** [gruntwork-io/terratest#1048]
[General Availability](https://docs.docker.com/compose/cli-command/#transitioning-to-ga-for-compose-v2) (GA) for docker compose v2 is ["Almost There"](https://github.com/docker/roadmap/issues/256). With GA we could consider upgrading docker compose examples ([sample project](https://github.com/gruntwork-io/terratest/tree/master/examples/docker-compose-stdout-example) and [test](https://github.com/gruntwork-io/terratest/blob/master/test/docker_stdout_example_test.go)) as well as the [docker package](https://github.com/gruntwork-io/terratest/blob/master/modules/docker/docker_compose.go) to use v2.

The upgrade should be quite stright forward as it mostly requires replacing "docker-compose" (dash) command with "docker compose" (no dash) and linking to the [official migration instructions](https://docs.docker.com/compose/cli-command-compatibility/) for porting tests.

**Comment by yorinasub17** [comment]
Seems reasonable! I subscribed to the GA ticket to track it, and we can prioritize this as soon as it is released as GA.

**Comment by yariksheptykin** [comment]
Anquick heads up:
compose V2 has finally transitioned to GA. See https://github.com/docker/roadmap/issues/256#issuecomment-1110984993

**Comment by nialdaly** [comment]
Hi @yariksheptykin and @yorinasub17, I've raised a [PR](https://github.com/gruntwork-io/terratest/pull/1125) to resolve this issue. I hope that's okay? I was also wondering if it's worth renaming instances to `docker-compose.yml` to `compose.yml` as discussed [here](https://github.com/compose-spec/compose-spec/blob/master/spec.md#compose-file)?

I wanted to get your thoughts on the `version` property present in the existing `docker-compose.yml` files and if they are necessary with the move to V2? Thanks!

**Comment by yariksheptykin** [comment]
> I wanted to get your thoughts on the version property present in the existing docker-compose.yml files and if they are necessary with the move to Docker Compose V2? Thanks!

I would suggest dropping `version` altogether. This will set the version to the compose spec, which should be a sane default.
