### ISSUE TITLE
Add support for deleting an AMI along with its backing snapshot

### ISSUE THREAD

**Issue by wjam** [gruntwork-io/terratest#105]
I've been using Terratest in anger recently and have spotted a few things about the library.

As part of building a pipeline for some Packer/Terraform infrastructure, it's common that AMIs will be created that are instantly destined for the bin - either because a branch/PR is being tested or because the AMI failed testing. It'd be useful to add a method that is capable of both deregistering the AMI as well as deleting the snapshot behind the AMI.

**Comment by brikis98** [comment]
Deregister is here: https://github.com/gruntwork-io/terratest/blob/9348b5bd2fbfbe5fcf3c40b59117c16670c1f3b9/modules/aws/ec2.go#L146-L165. PR welcome for deleting :)
