### ISSUE TITLE
How to get the 'backup_retention_period' from a rds instance

### ISSUE THREAD

**Issue by danrhjones** [gruntwork-io/terratest#1058]
Hi, I am new to terratest and terraform. 

I can see from the example that I can create an RDS instance, which I have modified to add `backup_retention_period = 7`

I would like to be able to test that this has been done, but i cant work out how to get that field. (It doesn't help that I am also quiet new to AWS and have no idea what that field would be classed as!)

Any help is greatly appreciated, thanks

**Comment by infraredgirl** [comment]
Hi Dan, were you able to resolve this?

**Comment by danrhjones** [comment]
Yes I was able to resolve it

I used `aws.GetRdsInstanceDetails` and it contains an element `*dbInstance.BackupRetentionPeriod`
