### ISSUE TITLE
Add support for tagging AWS resources

### ISSUE THREAD

**Issue by wjam** [gruntwork-io/terratest#106]
I've been using Terratest in anger recently and have spotted a few things about the library.

Part of a pipeline that is building an AMI, I've found it quite common to add a tag to an AMI once it has passed testing. Adding a method to add tags to an AMI, along with other AWS resources, would be useful.

**Comment by brikis98** [comment]
Could you use [snapshot_tags](https://www.packer.io/docs/builders/amazon-ebs.html#snapshot_tags) in Packer?

**Comment by wjam** [comment]
The idea is to allow the adding a tag to mark the AMI as tested only after the AMI has passed testing although, after learning today that AMI tags aren't visible across accounts, the value is somewhat diminished.

**Comment by brikis98** [comment]
Ah, I gotcha. An interesting idea and I'd be open to a PR for that assuming you haven't lost all enthusiasm for it :)
