### ISSUE TITLE
Allow for binaries to be installed via go install

### ISSUE THREAD

**Issue by pete0emerson** [gruntwork-io/terratest#1096]
Since this is golang tooling, I'd like to be able to use native go tooling to install the binary:

```
 ~ $ go install github.com/gruntwork-io/terratest@latest
go install: github.com/gruntwork-io/terratest@latest: module github.com/gruntwork-io/terratest@latest found (v0.40.6), but does not contain package github.com/gruntwork-io/terratest
```

**Comment by yorinasub17** [comment]
The path needs to point to where the main code is for the command, which is in `cmd/terratest_log_parser`. So in this case, you can install the log parser with:

```
go install github.com/gruntwork-io/terratest/cmd/terratest_log_parser@latest
```

Similarly, to install `pick-instance-type`, you can run:

```
go install github.com/gruntwork-io/terratest/cmd/pick-instance-type@latest
```

**Comment by pete0emerson** [comment]
Ah, nice. I'll close this out.

**Comment by loupgaroublond** [comment]
```
~ $ go install github.com/gruntwork-io/terratest/cmd/terratest_log_parser@latest
go: downloading github.com/gruntwork-io/go-commons v0.8.0
go: downloading github.com/urfave/cli v1.22.2
go: downloading github.com/sirupsen/logrus v1.8.1
go: downloading github.com/go-errors/errors v1.0.2-0.20180813162953-d98b870cc4e0
go: downloading github.com/cpuguy83/go-md2man/v2 v2.0.0
go: downloading github.com/russross/blackfriday/v2 v2.1.0
```

that worked beautifully, and clearly the problem is a lack of experience with go-lang - any chance you folks might document these two install commands somewhere for other go-lang newbies encountering this?

**Comment by yorinasub17** [comment]
Sure! I'll open a PR with the documentation update shortly.

**Comment by yorinasub17** [comment]
PR with docs update: https://github.com/gruntwork-io/terratest/pull/1098

**Comment by maha51ece-tech** [comment]
How to install terratest_log_parser for Github actions step during run time.How can i see those 3 files created during test run

I have below in my yaml file

      - name: Run Assertion Tests
        run: |
          cd test 
          go install github.com/gruntwork-io/terratest/cmd/terratest_log_parser@latest
          go install github.com/gruntwork-io/terratest/cmd/pick-instance-type@latest
          go test -v ./... -timeout 30m | tee test_output.log
          terratest_log_parser -testlog test_output.log -outputdir test_output
