### ISSUE TITLE
Terraform : Failed to read variables file when using VarFiles

### ISSUE THREAD

**Issue by kzankpe** [gruntwork-io/terratest#1109]
I have a test case where  I provide variables file for the plan command. I am getting the error below :

```
Error:      	Received unexpected error:
        	            	FatalError{Underlying: error while running command: exit status 1; ╷
        	            	│ Error: Failed to read variables file
        	            	│ 
        	            	│ Given variables file ../terraform.tfvars does not exist.

```

The file does exist in the directory not empty.
Here an extract of the test case

```
terraformtfvars := "../terraform.tfvars"
assert.FileExists(t,terraformtfvars,"File does not exist: ",terraformtfvars)
	
	terraformOption := &terraform.Options{
		TerraformDir:  "../",
		VarFiles: []string{"../terraform.tfvars"},
	}

	out, err := terraform.InitAndPlanE(t, terraformOption)
```

Is there something I am doing wrong here? 
Thank you.

**Comment by denis256** [comment]
Hi,
I think path to var file should be relative to `TerraformDir`, in the example above should be `VarFiles: []string{"terraform.tfvars"}`

Simplified example in: https://github.com/denis256/terratest-tests/blob/master/tf_var/test/tf_var_relative_path_test.go

**Comment by kzankpe** [comment]
Hi @denis256,

Thank you for your response. I fixed my code with your hint and it's working now.

Best Regards,
