### ISSUE TITLE
Questions when using Terratest

### ISSUE THREAD

**Issue by foreverXZC** [gruntwork-io/terratest#111]
I have used Terratest in several cases on AWS and Azure. I found your work was extremely fascinating and really useful in plenty of circumstances. However, I met some problems and would like to report an issue here. I feel curious about whether it's my fault or there actually occurs some defects.

Firstly, when I am using ssh example for the first time, the program cannot find the directory named /.test-data, unless I create such directory and files like TerraformOptions.json manually. But for the second time, this error no longer occurs.

Secondly, when I try to use some modules, the program seems cannot find the output unless I explicitly write output in tf file. For instance, I have to add such lines to guarantee that the program runs correctly even if this module actually has some outputs.
output "resource_group_name" {
  value = "${module.xxx.resource_group_name}"
}
As a result, I wonder whether Terratest really supports usage of modules.

Last but not the least, when the test fails, I found it really difficult to locate the error, because the log is too long and I have to dive into the log deeply and find what the error actually is. I am just wondering how I can make this process easier. Thanks a lot!

**Comment by brikis98** [comment]
> Firstly, when I am using ssh example for the first time, the program cannot find the directory named /.test-data, unless I create such directory and files like TerraformOptions.json manually. But for the second time, this error no longer occurs.

Sounds like a bug! Could you share your code?

> Secondly, when I try to use some modules, the program seems cannot find the output unless I explicitly write output in tf file. For instance, I have to add such lines to guarantee that the program runs correctly even if this module actually has some outputs.

This is not a Terratest limitation; this is how Terraform works. Only outputs declared in the top-level ("root") module where you're running `terraform apply` will be accessible via the `terraform output` command (which is what Terratest is using under the hood). See [module outputs](https://www.terraform.io/docs/modules/usage.html#outputs)

> Last but not the least, when the test fails, I found it really difficult to locate the error, because the log is too long and I have to dive into the log deeply and find what the error actually is. I am just wondering how I can make this process easier.

Agreed. Currently, the best way to do it is to search for the text `FAIL:` in the log file, but that's obviously tedious. Go does not do a great job of displaying errors in tests, so we may need to add some special logic to Terratest to make this easier. Ideas and PRs welcome.

**Comment by foreverXZC** [comment]
I did not modify the code, but if there does not exist a folder named ".test-data", the error occurs like this:
![path error](https://user-images.githubusercontent.com/8863250/41590306-4d301d3c-73e9-11e8-9c76-0dfa6aeeb2c3.png)

**Comment by brikis98** [comment]
Did you have any of the `SKIP_xxx` environment variables set?

**Comment by foreverXZC** [comment]
No. I did not change anything, just downloaded the example code and ran it...

**Comment by brikis98** [comment]
Well, the tests are passing in CI and locally fairly consistently, so we need to figure out if there's something different in your environment.

How are you running the tests? Could you share the full command and log output?

**Comment by foreverXZC** [comment]
I downloaded the whole zip file on GitHub again. I did not modify anything and executed "go test -v -run TestTerraformSshExample". such error still occurs:
![path error 2](https://user-images.githubusercontent.com/8863250/41693831-cf0803dc-7539-11e8-9f20-3f8509913445.png)
I would like to illustrate that I am using Windows 10. I wonder whether Terratest performs different between Windows and Linux or Mac...

**Comment by brikis98** [comment]
> I would like to illustrate that I am using Windows 10

Ah, that is most likely the issue! I bet we have a bug somewhere where we're not handling file paths correctly on Windows. Or CI server and dev boxes are all *nix...

I wonder if it's simply the use of *nix style paths (with forward-slashes) here: https://github.com/gruntwork-io/terratest/blob/master/test/terraform_ssh_example_test.go#L26.

**Comment by foreverXZC** [comment]
Thanks for reply. I think except for the problem I have mentioned, everything else including such paths with forward-slashes runs properly as I imagined.

**Comment by brikis98** [comment]
So, for example, [terraform_redeploy_example_test.go](https://github.com/gruntwork-io/terratest/blob/master/test/terraform_redeploy_example_test.go), which also uses forward slashes and the `LoadTerraformOptions` method, works for you? If so, that is strange indeed!

Even if it does, I'd be curious if changing those slashes to backslashes fixes the issue for you or not...

**Comment by foreverXZC** [comment]
Yes in this example the same problem occurs. I still need to create a folder named ".test-data" manually. In addition, back slashes also do not work.
Furthermore, in redeploy test example, a function named "undeployUsingTerraform" is used. However, it is defined in packer test example, which means that if I use this redeploy test only, this function will be regarded as undefined. As a result, I recommend to replace this function to "LoadTerraformOptions" and "Destroy", just as other examples (for instance, ssh test example) do.

**Comment by foreverXZC** [comment]
For the problem above, I have already made a simple pull request. #131
