### ISSUE TITLE
Fix severe vulnerabilities in go-getter v1.5.11 by upgrading to v2.0.2+ 

### ISSUE THREAD

**Issue by YasserBennani** [gruntwork-io/terratest#1138]
Hello,

It seems that the version of go-getter currently used by terratest `v1.5.11` has a couple of vulnerabilities according to analysis from dependabot. The current vulnerabilities range from high to critical in severity:

- Command injection in HashiCorp go-getter :warning: **_critical_**: HashiCorp go-getter before 2.0.2 allows Command Injection.
- Unsafe downloads in HashiCorp go-getter :warning: **_high_**: 
  - HashiCorp go-getter through 2.0.2 does not safely perform downloads. Asymmetric resource exhaustion could occur when go-getter processed malicious HTTP responses.
  -  Arbitrary host access was possible via go-getter path traversal, symlink processing, and command injection flaws.
  -  Protocol switching, endless redirect, and configuration bypass were possible via abuse of custom HTTP response header processing.

I thought I would bring it up for your consideration. Thanks.

**Comment by YasserBennani** [comment]
@denis256 The above vulnerabilities were fixed in `go-getter v1.6.1` - which `terratest` is using now - for the major version 1 `(v1.X.X)` users. It looks like `go-getter` is currently maintained on both major versions 1 and 2 if I am not mistaken, so this issue is only relevant for for `go-getter v2.X.X` users now. Feel free to close if this issue is no longer relevant to `terratest`.

**Comment by yorinasub17** [comment]
Will close as this was addressed in https://github.com/gruntwork-io/terratest/pull/1136
