### ISSUE TITLE
Disable helm dependency build on template rendering

### ISSUE THREAD

**Issue by curuvija** [gruntwork-io/terratest#1143]
Hi,

I'm running a loop rendering more than a few templates and on each 'helm dependency build' command is executed which slows down the execution of tests. Here I see: 

https://github.com/gruntwork-io/terratest/blob/0dd0f81e8cee879995a10660f6e084d9334a8e53/modules/helm/template.go#L38

Could we have an option to disable this and in that case I could probably do something like this:

`helm.RenderTemplate(s.T(), options, s.ChartPath, s.Release, s.Templates, "--dependency-update")`

This will download dependencies only once. 

Is there an another way to solve this issue that I'm not aware off? 

There is one similar issue already created here https://github.com/gruntwork-io/terratest/issues/342.

**Comment by Jeinhaus** [comment]
In our case our test cases are now failing, since we download dependencies from a private Helm repository before executing the tests. It would be great if this feature was optional so we don't have to modify all our tests to be able to pull from our private repositories.

**Comment by nieomylnieja** [comment]
I agree, there are similar issues already: https://github.com/gruntwork-io/terratest/issues/1193#issuecomment-1434782474

**Comment by rshutt-va** [comment]
I'm cross-posting this from #1193.  To further address the "default behavior" concern, should not the default behavior of Template and Install have some parity?

Even more strange is that the helm.Install workflow does not do ANY dep build; the user must do this before installing (typically for an integration test). It is counterintuitive to have the Template workflow forcibly do the helm dep build vs. the Install workflow not doing it. The preferred solution would be to have the Template workflow omit the dep build and suggest the user is instructed to do the dep build before any Template workflow as it is with the Install workflow.
