### ISSUE TITLE
AWS ECR support for get and put lifecycle policy

### ISSUE THREAD

**Issue by cauealvesbraz** [gruntwork-io/terratest#1212]
Hello guys,

First of all, thanks for this amazing project and congratulations to the maintainers.

I'm using the Terratest for create tests to all my modules and now I need support for get and put AWS ECR policy.

I already created a pull request to add this support. Could you validate if it's suitable? Here: https://github.com/gruntwork-io/terratest/pull/1198

**Comment by denis256** [comment]
Released in https://github.com/gruntwork-io/terratest/releases/tag/v0.41.5
