### ISSUE TITLE
vpc tags are not getting retrieved

### ISSUE THREAD

**Issue by pravindhawas** [gruntwork-io/terratest#1216]
Hi Team,
 I am creating vpc. In terratest, I want to retrieve the tag for newly created vpc and want to compare with expected tag. I have written below code.
However, below code is not able to get the vpc tags. This looks like problem with function code line: vpc_tags := aws.GetTagsForVpc(t, vpc_id, "eu-central-1"). 
I can confirm that vpc_id are getting passed correctly (for example : vpc_id = "vpc-0x111x59x111111xx")

Can anyone please help me indentifying what I am missing here?

**vpc_test.go file code:** 

package vpc_test

import (
	"testing"
	"fmt"
	"log"
	"encoding/json"
	"github.com/gruntwork-io/terratest/modules/aws"
	"github.com/gruntwork-io/terratest/modules/terraform"
	"github.com/stretchr/testify/assert"
)

func TestTerraformBasicExample(t *testing.T) {
	t.Parallel()

	terraformOptions := terraform.WithDefaultRetryableErrors(t, &terraform.Options{
		TerraformDir: "../test",
		PluginDir: "/opt/app-root/terraform-plugin-providers",
		NoColor: true,
	})

	defer terraform.Destroy(t, terraformOptions)

	terraform.InitAndApply(t, terraformOptions)

	vpc_id := terraform.Output(t, terraformOptions, "vpc_id")

	vpc_tags := aws.GetTagsForVpc(t, vpc_id, "eu-central-1")

	b, err := json.Marshal(vpc_tags)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println(string(b))

	external_tag, contains_external_tag := vpc_tags["Name"]
	assert.True(t, contains_external_tag)
	assert.Equal(t, "external", external_tag)
}

**Comment by denis256** [comment]
Hello,
value of `vpc_id` should look like `vpc-0e1d43f4fac344xyz`,
example usage of of `GetTagsForVpc` can be found in: https://github.com/gruntwork-io/terratest/blob/master/modules/aws/vpc_test.go#L120

**Comment by pravindhawas** [comment]
Hi @denis256 ,

Yes vpc_id is correct I am getting from terraform output and passing into 
vpc_tags := aws.GetTagsForVpc(t, vpc_id, "eu-central-1")
example: vpc_id is something like you mentioned vpc-0e1d43f4fac344xyz

however, I can see vpc_tags is blank and do not have value.

I have 2 tags to vpc that is created using terraform as below:
tags     = {
"Name"  = "external"
"infra" = "true"
}
Am i missing anything

**Comment by james03160927** [comment]
Please check if the region eu-central-1 is specified in the VPC Terraform file. If it is not provided, the VPC will be created in the default region configured by the user, and we won't be able to check the VPC tags with the eu-central-1 region

![image](https://github.com/user-attachments/assets/a8949ac3-1e53-4adc-ae81-2008e23ac4c4)

**Comment by james03160927** [comment]
Will close this issue. Feel free to reopen it if you continue to see the same issue.
