### ISSUE TITLE
Can you use local.tf file instead of variables.tf 

### ISSUE THREAD

**Issue by rmccarthy-ellevation** [gruntwork-io/terratest#1220]
I would like to know if I can use the local.tf instead of the variables.tf for testing AWS terraform?
Thanks!

**Comment by denis256** [comment]
Hi,
afaik Terraform will evaluate all `*.tf` files from the working directory so I think it will load definitions from `local.tf` too.

**Comment by rmccarthy-ellevation** [comment]
> Hi, afaik Terraform will evaluate all `*.tf` files from the working directory so I think it will load definitions from `local.tf` too.

Awesome, thanks.
