### ISSUE TITLE
Order of combined output form shell.RunCommandAndGetOutputE

### ISSUE THREAD

**Issue by mimazaka** [gruntwork-io/terratest#1228]
Hi guys, 

I would like to asked if I should expect specific order of lines in output for func `shell.RunCommandAndGetOutputE` ?

I noticed `output` struct returns internal  `merged` struct on call of `output.Combined()`. The second one contains comment that parallel writes should not be allowed.

I noticed that during manual debug of `shell.RunCommandAndGetOutputE` , especially with some slowdowns inside  execution of code within wait group defined in `readStdoutAndStderr`, I obtained output with mixed lines form `stdout `and `stderr`.

Is there any solution to have an output in specific order e.g. standard error data stream first and standard output second?

**Comment by denis256** [comment]
Hi,
AFAIK there is no function to return both `stdout` and `stderr` - this can be a good improvement for terratest
