### ISSUE TITLE
Incompatible versions with Azure SDK for go

### ISSUE THREAD

**Issue by AnilDeyyala** [gruntwork-io/terratest#1234]
C:\Users\anil.deyyala\go\pkg\mod\github.com\gruntwork-io\terratest@v0.41.10\modules\azure\resourcegroup.go:78:9: cannot use &rg (value of type *"github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2021-04-01/resources".Group) as type *"github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2020-10-01/resources".Group in return statement
C:\Users\anil.deyyala\go\pkg\mod\github.com\gruntwork-io\terratest@v0.41.10\modules\azure\resourcegroup.go:100:9: cannot use rg.Values() (value of type []"github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2021-04-01/resources".Group) as type []"github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2020-10-01/resources".Group in return statement

getting this error while trying with cosmos db for the same terraform & terratest code provided

**Comment by denis256** [comment]
Hi,
which version of `azure-sdk-for-go` is used? it is the same as defined in `go.mod` of `terratest`?

https://github.com/gruntwork-io/terratest/blob/v0.41.10/go.mod#L8

**Comment by AnilDeyyala** [comment]
Yes,

import (
	"testing"

	"github.com/Azure/azure-sdk-for-go"
	"github.com/Azure/azure-sdk-for-go/profiles/latest/cosmos-db/mgmt/documentdb"
	"github.com/gruntwork-io/terratest/modules/azure"
	"github.com/gruntwork-io/terratest/modules/random"
	"github.com/gruntwork-io/terratest/modules/terraform"
	"github.com/stretchr/testify/assert"
)

**Comment by AnilDeyyala** [comment]
> Hi, which version of `azure-sdk-for-go` is used? it is the same as defined in `go.mod` of `terratest`?
> 
> https://github.com/gruntwork-io/terratest/blob/v0.41.10/go.mod#L8

import (
	"testing"

	"github.com/Azure/azure-sdk-for-go"
	"github.com/Azure/azure-sdk-for-go/profiles/latest/cosmos-db/mgmt/documentdb"
	"github.com/gruntwork-io/terratest/modules/azure"
	"github.com/gruntwork-io/terratest/modules/random"
	"github.com/gruntwork-io/terratest/modules/terraform"
	"github.com/stretchr/testify/assert"
)

**Comment by AnilDeyyala** [comment]
> C:\Users\anil.deyyala\go\pkg\mod\github.com\gruntwork-io\terratest@v0.41.10\modules\azure\resourcegroup.go:78:9: cannot use &rg (value of type *"github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2021-04-01/resources".Group) as type *"github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2020-10-01/resources".Group in return statement C:\Users\anil.deyyala\go\pkg\mod\github.com\gruntwork-io\terratest@v0.41.10\modules\azure\resourcegroup.go💯9: cannot use rg.Values() (value of type []"github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2021-04-01/resources".Group) as type []"github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2020-10-01/resources".Group in return statement
> 
> getting this error while trying with cosmos db for the same terraform & terratest code provided

Yes, using that version only.

Here the version from go.mod file

cloud.google.com/go v0.83.0 // indirect
	cloud.google.com/go/storage v1.10.0 // indirect
	**github.com/Azure/azure-sdk-for-go v50.2.0+incompatible // indirect**
	github.com/Azure/go-autorest v14.2.0+incompatible // indirect

**Comment by AnilDeyyala** [comment]
Add (or replace if it already exists) the directive for azure-sdk-for-go in the go.mod file to:

`github.com/Azure/azure-sdk-for-go v46.0.0+incompatible`

and run go mod tidy again?

This Fixes #1234

**Comment by AnilDeyyala** [comment]
Add (or replace if it already exists) the directive for azure-sdk-for-go in the go.mod file to:

`github.com/Azure/azure-sdk-for-go v46.0.0+incompatible`

and run go mod tidy again?

closes #1234
