### ISSUE TITLE
support port forwarding for deployment resources

### ISSUE THREAD

**Issue by mstrYoda** [gruntwork-io/terratest#1260]
Hi 👋  kubectl supports port-forwarding using deployment object. Currently k8s package inside terratest restricts it to only pods and services. It would be nice to support deployments too.

**Comment by marcellmartini** [comment]
Hello, This is my first help and I'd like to implement this issue. I already read the [guidelines](https://terratest.gruntwork.io/docs/community/contributing/#contribution-guidelines).

If there isn't any problem, my next steps will be:
* Update the document 
* open a PR with the code.

**Comment by marcellmartini** [comment]
I saw the doc folder and there aren`t any necessary changes to be made.

**Comment by marcellmartini** [comment]
PR #1274 was merged. This issue can be closed. Thank you all.

**Comment by denis256** [comment]
Released in https://github.com/gruntwork-io/terratest/releases/tag/v0.41.21
