### ISSUE TITLE
Add support for RDS

### ISSUE THREAD

**Issue by mikhailadvani** [gruntwork-io/terratest#128]
Validation of creation of DB instances
Validation of creation of DB parameter groups
Validation of creation of DB option groups
Validation of association of the above

**Comment by brikis98** [comment]
Can you provide more details on what you're looking for?

**Comment by mikhailadvani** [comment]
should I open a separate issue for the other databases connectivity test or continue on this one?

**Comment by brikis98** [comment]
You mean to support PostgreSQL and other types of DBs?

**Comment by mikhailadvani** [comment]
yes

**Comment by brikis98** [comment]
Separate issues to track each would probably be best!

**Comment by mikhailadvani** [comment]
cool. should I close this issue then? I think the tests are also passing now

**Comment by brikis98** [comment]
Yup, thanks!
