### ISSUE TITLE
SSH Key Pair Problem

### ISSUE THREAD

**Issue by foreverXZC** [gruntwork-io/terratest#129]
After I tried SSH example plenty of times, which is pretty popular and really interesting, I found it quite difficult to use key pair. Sometimes I would like to use my local private and public key, which means that I do not generate a new key pair and utilize it as "terraform_ssh_example_test.go" does. If I use AWS, it is not a big issue because I can upload my local key pair to AWS and then import it, using AWS specific functions such as "ImportEC2KeyPair".
However, if I would like to try other kinds of cloud platform, say, Azure, I cannot find a easy method to utilize given functions in terratest/modules/ssh, because SSH host requires AWS specific input aws.Ec2Keypair. As a result, I have to write my own test code, which is quite similar to given functions in Terratest but instead not platform specific, to test SSH to virtual machines on other platforms.
So does anyone meet the same issue? I will feel quite glad if someone knows the solution to my question. Thanks a lot!

**Comment by Briansbum** [comment]
I had a similar issue where I was trying to use keys that I have stored in a Vault instance and some were for AWS and some were not.

I got around it by using the `ssh.Keypair` type from `github.com/gruntwork-io/terratest/ssh`.

The way I use it is like this:
```golang
keypair := ssh.KeyPair{PrivateKey: myPrivateKeyString}

publicHost := ssh.Host{
			Hostname:    publicIP,
			SshKeyPair:  &keypair,
			SshUserName: "ubuntu",
}
```

`ssh.Host` doesn't have any issue using this and if you need the public key it's gonna be fairly simple to add it to `keypair`.

I hope this helps.

**Comment by brikis98** [comment]
+1 on @Briansbum's approach. Let me know if it doesn't work for you!

**Comment by foreverXZC** [comment]
Yes it really helps. Thank you so much.

**Comment by brikis98** [comment]
Great, thanks for following up.
