### ISSUE TITLE
Is it possible to create k8s tests for custom resources

### ISSUE THREAD

**Issue by Mo0rBy** [gruntwork-io/terratest#1316]
I've just started using `terratest` and figuring out how to use it along with the `ginkgo` testing framework (and even goLang!). It looks like it will perform a good number of the kubernetes tests that I am envisioning, however, is there anyway to query custom resources?

The first suite of tests I want to create are not doing much settingUp/tearingDown, I just want to query what exists in our cluster. This will include ensuring configmaps have the correct `key:values`, checking pods/deployments for correct values and other general checks, I might even get some HTTP checks on a certain ports for our microservices.
What I REALLY want to be able to test are resources related to `istio`, but there are no packages in the `terratest` modules that would indicate that there is support for `istio` testing.

An example of one of these tests might be to get the resource (such as an `AuthorizationPolicy`) and assert that it has the correct rules applied to it.

Are there any ways to create stuff in order to test custom resources that are not currently supported by the `terratest` modules?
I'd be happy for any suggestions, thanks!

**Comment by denis256** [comment]
Hi,
I think at this point can be used `KubectlApply() / RunKubectlAndGetOutputE()` to work with custom resources

**Comment by Mo0rBy** [comment]
I won't be using `KubectlApply()` as we currently want to just test things that already exist in our infra, we just want a suite that is going to check loads of different things and we can use it as a way to ensure that we have got we want deployed.

I was thinking that we could use the `RunKubectlE()` or `RunKubectlAndGetOutputE`, but I was hoping there would be a better, more intentional method to use. Is there any documentation on contributing to the project to add new methods for custom resources such as `istio`? Not saying I will definitely be making contributions but if I read some docs on what Contributors need to think about in order to add functionality, I might give it a go at.

**Comment by Mo0rBy** [comment]
I found the contribution docs, but it's more of a guide on TDD, the pre-commits, what to do if your changes are related to Azure, not really design focused.
