### ISSUE TITLE
Enhancement Suggestion for HTTP Helper

### ISSUE THREAD

**Issue by foreverXZC** [gruntwork-io/terratest#133]
In the past few days, I used given http example and it worked pretty well. However, I think that existing functions do not meet all of my requirements.

First, sometimes I do not need validation of response body. For instance, I would like to deploy a template web application, but I am not aware of the whole body of this web app. As a result, I only care about whether I can get an http response successfully, instead of checking contents.

Second, in some cases, I would like to validate specific parts of response body, not the whole content. For example, I want to launch a Ubuntu Linux server and run commands to install nginx. This process can be done using `checkSshCommandE`. Next, after I open port 80 to allow http request, I would like to send an http request to see whether the response body contains the word "nginx". In this circumstance, the body is really long and even varies among different versions. By contrast, I can make sure that the content contains "nginx". So my requirement here is just to check a substring.

In above cases, I have to write my own test code using `retry.DoWithRetry`, `HttpGet`, etc. I wonder whether these enhancement suggestions are really worthwhile. If needed, I can add some features and make pull requests. Thanks a lot!

**Comment by brikis98** [comment]
Did you look at [HttpGetWithCustomValidation](https://github.com/gruntwork-io/terratest/blob/master/modules/http-helper/http_helper.go#L67) and [HttpGetWithRetryWithCustomValidation](https://github.com/gruntwork-io/terratest/blob/master/modules/http-helper/http_helper.go#L110)?

**Comment by foreverXZC** [comment]
OK I will try to write my own validation response function and run the test. Thanks for instruction.

**Comment by brikis98** [comment]
OK, great!

**Comment by mingfang** [comment]
This is how I got it to work in case anyone wants to see an example.
https://github.com/mingfang/terraform-provider-k8s/blob/master/test/modules/prometheus/basic_test.go

It's very basic but unfortunately I'll have to cut and paste this code to every test.
Hopefully terratest will natively support this validation soon.
