### ISSUE TITLE
Add OpenTofu support

### ISSUE THREAD

**Issue by brikis98** [gruntwork-io/terratest#1333]
**Describe the solution you'd like**
[As recently announced](https://opentofu.org/blog/the-opentofu-fork-is-now-available/), the OpenTofu fork should drop soon. We should make sure that Terratest supports it out of the box. 

Here's an idea for an initial implementation: anywhere Terratest calls out to the `terraform` binary, we should update it to check for the `terraform` binary first; if that's not found, then try the `tofu` binary; and if that's not found, show an error (as we do today). Whatever we pick, we should mention in the debug log.

**Describe alternatives you've considered**
In theory, you can already use OpenTofu by using the [`TerraformBinary` config](https://github.com/gruntwork-io/terratest/blob/master/modules/terraform/options.go#L41), but that requires extra steps, whereas I'd like OpenTofu to "just work" with Terratest. 

**Additional context**
OpenTofu should work as a "drop in" replacement for Terraform, so in theory, no other changes should be necessary. However, we should run our tests to make sure once the `tofu` binary is available for testing. One place where OpenTofu will differ is `stdout` and `stderr` output will say OpenTofu instead of Terraform; if Terratest is parsing that log output anywhere, we'll need to update the code accordingly.

This is just the initial implementation in the sense that it should be backward compatible. In the future, we can reverse the lookup order, and perhaps even drop support for `terraform`, but those would be significant breaking changes (especially the latter), so we'd want to see how things go with OpenTofu and what the community wants first.

**Comment by skyzyx** [comment]
From a technical perspective, I expect that it will be a no-op for the time being as OpenTF anticipates maintaining compat/interop for the foreseeable future. (However, OpenTF has stated that _some_ functionality may be added to OpenTF that is a _superset_ of what's in base Terraform. [[source](https://github.com/opentffoundation/roadmap/issues/24)])

From a process perspective:

1. If there is a bug in OpenTF that does not exist in Terraform (or vice-versa), will bug reports (as they pertain to this project) be treated equally on both platforms?

1. Will testing be performed with code targeting both platforms?

1. For OpenTF's potential future "superset" functionality, will that be treated as a first-class citizen?

**Comment by denis256** [comment]
Released in https://github.com/gruntwork-io/terratest/releases/tag/v0.46.0

**Comment by kvendingoldo** [comment]
btw. you can also integrate [tenv](https://github.com/tofuutils/tenv) that support Terraform as well as OpenTofu (and Terragrunt :) ) in one tool. It allow you to simplify version management.
