### ISSUE TITLE
Test Helm remote repo

### ISSUE THREAD

**Issue by jguionnet** [gruntwork-io/terratest#1358]
**Describe the solution you'd like**
I would like the helm test feature to support the --repo options, I would like that underneath the following commands could be executed

`helm template keda --namespace medieval-38bl76 --set metricsServer.replicaCount=45 --set resources.metricServer.limits.memory=4545Mi --repo https://kedacore.github.io/charts` 

`helm template --namespace keda-system keda -f custom-values.yaml --repo https://kedacore.github.io/charts` 

I want to verify that my customization on top of chart work from release to release of remote chart I am using

**Describe alternatives you've considered**

Coding

**Additional context**

**Comment by merusso** [comment]
Why not add the Helm repo and reference like so?
```
$ helm repo add kedacore https://kedacore.github.io/charts
$ helm template keda kedacore/keda --namespace keda --version 2.12.0
```

**Comment by jguionnet** [comment]
> Why not add the Helm repo and reference like so?
> 
> ```
> $ helm repo add kedacore https://kedacore.github.io/charts
> $ helm template keda kedacore/keda --namespace keda --version 2.12.0
> ```

I could and how do I do that programmatically with terratest?

**Comment by denis256** [comment]
```
	options := &helm.Options{}
	helm.AddRepo(t, options, "keda", "https://kedacore.github.io/charts")
	helm.RunHelmCommandAndGetOutputE(t, options, "repo", "update")
	helm.RunHelmCommandAndGetStdOutE(t, options, "template", "keda", "kedacore/keda", "--namespace", "keda", "--version", "2.12.0")
```

https://github.com/denis256/go-tests/tree/master/terratest-helm-test

**Comment by merusso** [comment]
I was thinking you could also use [helm.RenderTemplateE()](https://github.com/gruntwork-io/terratest/blob/1f1821ea7907875eca48592df99ea3d92bfa0888/modules/helm/template.go#L27C13-L27C13), but I see that it expects a local chart directory unlike the respective `helm template` command.
