### ISSUE TITLE
GetAccountId method should use GetCallerIdentity instead of GetUser

### ISSUE THREAD

**Issue by brikis98** [gruntwork-io/terratest#139]
The `GetAccountId` method currently calls `iam.GetUser` and extracts the account ID from the user's ARN:

https://github.com/gruntwork-io/terratest/blob/master/modules/aws/account.go#L27

This means the method only works when authenticated as an IAM User, but will not work if you use, say, IAM Roles for auth. A better approach would be to use `sts.GetCallerIdentity`, which works with all auth mechanisms, and returns the account ID as a field, requiring no extra extraction.

**Comment by rajdhandus** [comment]
I would like to work on this issue... Please let me know if I can go ahead and start..

**Comment by brikis98** [comment]
Yes please and thank you!
