### ISSUE TITLE
terratest_log_parser does not retain a lot of useful test and failure information

### ISSUE THREAD

**Issue by dkirrane** [gruntwork-io/terratest#1399]
**Describe the bug**
I would expect the report.xml generated by `terratest_log_parser` to contain the reason for the test failure.
However, terratest_log_parser loses the assertion results

**To Reproduce**
1. `go test -count=1 -v | tee test_output.log`

The above command created the following lines in the test_output.log:
```
--- FAIL: TestHelloWorldTerraform (0.74s)
    terraform_hello_world_test.go:193: 
        	Error Trace:	/mnt/c/terratest/terraform_hello_world_test.go:193
        	Error:      	Not equal: 
        	            	expected: "Hello foo eRcjAe"
        	            	actual  : "Hello eRcjAe"
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-Hello foo eRcjAe
        	            	+Hello eRcjAe
        	Test:       	TestHelloWorldTerraform
FAIL
exit status 1
```

2. `terratest_log_parser -testlog test_output.log -outputdir test_output --log-level info`

The above command created the following report.xml:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
	<testsuite tests="1" failures="1" time="0.804" name="github.com/company/terratest">
		<properties>
			<property name="go.version" value="go1.11"></property>
		</properties>
		<testcase classname="terratest" name="Failure" time="0.000">
			<failure message="Failed" type="">    terraform_hello_world_test.go:193: </failure>
		</testcase>
	</testsuite>
</testsuites>
```

**Expected behavior**
I would expect the report.xml to include 

- the testcase name == test i.e. the go test function name `TestHelloWorldTerraform`
- the failure body == assertion error

**Versions**
- Terratest version: 1.7.5
- Environment details (Ubuntu 20.04, Windows 10, etc.): WSL2

**Comment by james03160927** [comment]
Upon further investigation, I discovered that we are using the github.com/jstemmer/go-junit-report/parser package to generate the XML report. Unfortunately, this package does not offer an option to include assertion error details, and it appears that we are unable to do so either. There is an open issue related to this on GitHub (#181), which was created on March 26, but it has not yet been addressed. https://github.com/jstemmer/go-junit-report/issues/181

I'll close this issue as there's nothing we can do on this yet. Let's reopen this when this ticket is addressed.
