### ISSUE TITLE
kind cluster: context deadline exceeded

### ISSUE THREAD

**Issue by JCzz** [gruntwork-io/terratest#1401]
**Describe the bug**
I am running k8s kind cluster on macos arm64. When running:
`go test -v -tags kubernetes -run TestKubernetesHelloWorldExample`
It do apply the pods, but when testing for `http://172.18.0.1:5000` it runs into problems, see terminal output below.
Do you use client-go to access `http://172.18.0.1:5000` or do I need to create an ingress to access from the host?

**Nice to have**
- [ ] Terminal output
`TestKubernetesHelloWorldExample 2024-04-16T19:26:01+02:00 retry.go:103: HTTP GET to URL http://172.18.0.1:5000 returned an error: Get "http://172.18.0.1:5000": context deadline exceeded (Client.Timeout exceeded while awaiting headers). Sleeping for 3s and will try again.
`

**Versions**
Terratest version: v0.46.13
MacOS
go version
go version go1.21.7 darwin/arm64

Same On Windows 11 WSL
go version go1.21.3 linux/amd64

**Additional context**

**Comment by denis256** [comment]
Hi,
to access Kubernetes is used go client, it may be that the request reaches the cluster but hangs for some reason(API problem, network policies) - I would say to try to use `kubectl` cli to check if the cluster is reachable and can create pods.

**Comment by JCzz** [comment]
Hi @denis256 

Thanks, I can create pods and use kubectl for usual stuff. I can also see:
kubectl get pods 
```
NAME                                     READY   STATUS    RESTARTS       AGE
hello-world-deployment-944cbd46d-2jpzz   1/1     Running   0              18h
```

I can also run my own client-go up against the cluster.

**Comment by denis256** [comment]
Hm, it may be a problem with accessing exposed services - it is responding when accessing through services?

**Comment by JCzz** [comment]
That is the problem, I think. The service is running in a kind cluster, using docker on macos. I can see the services, but unable to "curl 172.18.0.1:5000" to the service from host machine:
```
kubectl get svc
NAME                  TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)          AGE
hello-world-service   LoadBalancer   10.96.31.44     172.18.0.1    5000:31173/TCP   25h
kubernetes            ClusterIP      10.96.0.1       <none>        443/TCP          27d

```

```
curl 172.18.0.1:5000
curl: (7) Failed to connect to 172.18.0.1 port 5000 after 8 ms: Couldn't connect to server

```

This is known issue running on non linux environment, but using client-go should be able to to access the services from within the same network, I think?

**Comment by denis256** [comment]
```
On macOS and Windows, docker does not expose the docker network to the host. Because of this limitation, containers (including kind nodes) are only reachable from the host via port-forwards
```
https://kind.sigs.k8s.io/docs/user/loadbalancer/

**Comment by JCzz** [comment]
I wish I could say any it is not working, but it does.

**Comment by JCzz** [comment]
Maybe a suggestion could be to use https://github.com/curl/curl-docker

**Comment by jk1m** [comment]
> Note: Running on Apple MBP M1

I was getting the same error but managed to figure it out after looking closer. It's actually an issue with the image, `training/webapp:latest`. `exec`ing into the pod, there were no Flask processes running and when trying to manually run it, I received `Segmentation fault (core dumped)`. Possible reasons? Trying to pull the image yields: 

"Suggest the author of docker.io/training/webapp:latest to upgrade the image to the OCI Format or Docker Image manifest v2, schema 2."

Changing the image and corresponding port (in the test, too) will get the test to pass.
