### ISSUE TITLE
Difference between ConfigPath in KubectlOptions and configPath as function parameter

### ISSUE THREAD

**Issue by Bablzz** [gruntwork-io/terratest#1411]
Hello everyone!
Thanks for awesome project - terraform!!!

I hope you are doing well!

I have a question - what difference between [ConfigPath](https://github.com/gruntwork-io/terratest/blob/2851217e39f9479414749017faa4eddac97586ae/modules/k8s/kubectl_options.go#L12)  and configPath [here](https://github.com/gruntwork-io/terratest/blob/2851217e39f9479414749017faa4eddac97586ae/modules/k8s/kubectl.go#L49) (for example)

in my mind second example it's a path to file with k8s resource?! or I misunderstood?

Thanks in advance!

**Comment by ryehowell** [comment]
Hi @Bablzz, thanks for opening this Issue!

`ConfigPath` for the `KubectlOptions` struct is meant to be used to point to a `kubectl` config file to configure the `kubectl` client. 

`configPath` for the `KubectlDelete` function is meant to be used as a path to a kubernetes manifest file that defines an object deployed to a running kubernetes cluster that should be deleted via the `KubectlDelete` function. 


Hope this helps!

**Comment by Bablzz** [comment]
@ryehowell thank you! :)
