### ISSUE TITLE
using random.UniqueId() for resource naming prevents destroy

### ISSUE THREAD

**Issue by cgradwohl-playq** [gruntwork-io/terratest#1444]
**Describe the bug**
A common pattern I see when writing tests with Terratest, is to use random.UniqueId() for resource naming so that naming collisions will not conflict during parallel testing.

However, during the destroy phase, if the call to AWS api's is retried then a new random.UniqueId() is generated and passed to the destroy call to AWS. This of course will not exist and ultimately the destroy with fail.

This mean that for resources with random.UniqueId() identifiers, the destroy will either work the first time or not at all.

**To Reproduce**
Steps to reproduce the behavior, code snippets and examples which can be used to reproduce the issue.

```go
t.Parallel()

workingDir := "../examples/complete_mysql"
instanceId := fmt.Sprintf("complete-mysql-%s", uniqueId)

terraformOpts := terraform.WithDefaultRetryableErrors(t, &terraform.Options{
TerraformDir: workingDir,
Vars: map[string]interface{}{
	"env_name":        env_name,
	"identifier":      instanceId,
	"private_zone_id": privateZoneId,
	"public_zone_id":  publicZoneId,
	"vpc_id":          vpcId,
},
})

defer terraform.Destroy(t, terraformOpts)
```

**Expected behavior**
The destroy should work, even if the underlying call to AWS fails or retries.

**Nice to have**
- [ ] Terminal output
- [ ] Screenshots

**Versions**
- Terratest version: 1.5.7
- Environment details (Ubuntu 20.04, Windows 10, etc.): ubuntu-latest

**Additional context**

**Comment by james03160927** [comment]
Hi @cgradwohl-playq, based on the code you shared, I don't see where the random ID is generated. During terraform destroy, it should use the ID stored in the state from when the resources were applied, so it shouldn't behave as you're describing. Could you provide more details on how to reproduce the issue you're experiencing?

**Comment by james03160927** [comment]
Closing this issue if you no longer experience this issue. Feel free to reopen this.
