### ISSUE TITLE
Add SSO configuration support to Terratest

### ISSUE THREAD

**Issue by kkrav3ts** [gruntwork-io/terratest#1460]
**Describe the solution you'd like**
In order to run tests in CLI, I need to be logged in first. I use IAM Identity Center (SSO, not Legacy):
```
[default]
sso_session = gw-sso
sso_account_id = 123456789012
sso_role_name = AdminRole
region = us-east-1
output = json

[sso-session gw-sso]
sso_region = us-east-1
sso_start_url = https://company-abc.awsapps.com/start
```

Being successfully logged in, I run tests and get:
```
TestNetworkFirewall 2024-11-01T21:03:29+02:00 region.go:109: Looking up all AWS regions available in this account
--- FAIL: TestNetworkFirewall (0.00s)
    region.go:66: profile "default" is configured to use SSO but is missing required configuration: sso_region, sso_start_url
FAIL
FAIL    github.com/gruntwork-io/terraform-aws-vpc/test/vpc-app-natgw-eips       0.061s
FAIL
```

Basically, I'd wanted to ask to implement support for new implementation of IAM Identity Center (SSO) login: https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sso.html

**Describe alternatives you've considered**
With using Legacy IAM Identity Center, everything works fine:
```
[default]
sso_start_url = https://company-abc.awsapps.com/start
sso_region = us-east-1
sso_account_id = 123456789012
sso_role_name = AdminRole
region = us-east-1
output = json
```

**Additional context**
None

**Comment by kkrav3ts** [comment]
@ZachGoldberg alas I am not able to do it myself as it requires better Go understanding and Terratest structure. So I created this ticket to request assistance. Is it possible to re-assign it to someone who is good with Go and Terratest?

**Comment by kkrav3ts** [comment]
@wakeful yes, it works as expected. Thanks!

**Comment by wakeful** [comment]
hey @kkrav3ts 

You should now be able to point directly to the **master** branch. The changes for the **AWS SDKv2** migration have been merged ( #1451 ).

**Comment by kkrav3ts** [comment]
Thanks!

**Comment by wakeful** [comment]
hey @kkrav3ts can you close this issue?

**Comment by kkrav3ts** [comment]
Sure, will do!
