### ISSUE TITLE
We should publish the GoDoc for Terratest

### ISSUE THREAD

**Issue by brikis98** [gruntwork-io/terratest#151]
This will make it easier to see what modules/functions are available.

**Comment by berney** [comment]
Found it here [terratest GoDoc](https://godoc.org/github.com/gruntwork-io/terratest)

**Comment by brikis98** [comment]
Oh, how cool! Great find, thanks!

I've added a link to the README: https://github.com/gruntwork-io/terratest#godoc. Browsing through it, our docs could use some work to make the GoDoc more useful, but it's a start.
