### ISSUE TITLE
Add support for OCI

### ISSUE THREAD

**Issue by sw-samuraj** [gruntwork-io/terratest#158]
Terratest has an [aws package](https://github.com/gruntwork-io/terratest/tree/master/modules/aws) with a number of utilities useful for AWS. It would be great to add similar utilities for testing code in [OCI](https://cloud.oracle.com/cloud-infrastructure).

**Comment by brikis98** [comment]
Agreed. PRs welcome!

**Comment by sw-samuraj** [comment]
I've provided a PR (#159) with the first helper function for deleting of OCI images. I would like to write an example and test to document it.

**Comment by brikis98** [comment]
Initial support added in #159. Thanks @sw-samuraj!
