### ISSUE TITLE
Update Terratest Docs to show support for multiple clouds

### ISSUE THREAD

**Issue by josh-padnick** [gruntwork-io/terratest#161]
Initially, we supported only AWS. We now support GCP and thanks to #158, #159, and #160, we have limited support for Oracle Cloud Infrastructure (OCI). We should update our README to reflect this support.

**Comment by robmorgan** [comment]
Maybe this is best left for another issue, but I think Terratest really needs a dedicated documentation site.

I started writing a table of contents once and this is how far I got:

```
1. Requirements
2. Installation
3. Testing HTTP Services
4. Testing Packer templates
5. Testing Terraform AWS resources
6. Testing Terraform GCP resources
7. Testing Docker
8. Files
9. Git
10. Misc
	1. Random Functions
	2. Retry
```

I think it would be good to nut out a skeleton, then maybe we start working on something.

**Comment by brikis98** [comment]
I like the idea @robmorgan. Terratest consists of a large number of functions, so a documentation site that tried to go over each one would be unmaintainable / unreadable, but I think what you're suggesting is more of a series of guides and best practices. I think that would be very worth having, either on a dedicated website, or as a blog post series.

**Comment by robmorgan** [comment]
@brikis98 your right, I guess that direction I'm heading in. More of a series of guides + best practices. I'll open another ticket for it.

**Comment by robmorgan** [comment]
Moving my part to #162.

**Comment by brikis98** [comment]
New website shows all the clouds/providers we support: https://terratest.gruntwork.io/
