### ISSUE TITLE
Is there a way to work with Terraform workspaces via Terratest?

### ISSUE THREAD

**Issue by sw-samuraj** [gruntwork-io/terratest#163]
**Question:**
In our _Terraform_ scripts, we are using a concept of [workspaces](//www.terraform.io/docs/state/workspaces.html). For example, it's part of naming convention of resources:

```hcl
resource "oci_core_instance" "CPServer" {
  display_name = "cpServer${count.index}-${terraform.workspace}"
  # other configuration
}
```

Is there a way to work with _workspaces_ in the _Terratest_ test? E.g. switch to the existing, or create the new one.

Is it even a valid use case?

**Comment by sw-samuraj** [comment]
I think that `RunTerraformCommand` should be fine for now. :+1: 

Would be OK if I write some proposal/PR for those functions? Something like:

* `WorkspaceNew(t *testing.T, name string) string`,
* `WorkspaceSelect(t *testing.T, name string) string`,

or maybe just:

* `WorkspaceSelectOrNew(t *testing.T, name string) string`.

I guess, they could be modeled like [Destroy](//github.com/gruntwork-io/terratest/blob/be2c7d366654f28812e037c3e8455a408ad2483c/modules/terraform/destroy.go#L17).

**Comment by brikis98** [comment]
Sure, that would be great 👍

**Comment by sw-samuraj** [comment]
New function `WorkspaceSelectOrNew` satisfies the initial question.
