### ISSUE TITLE
Practice recommendation for dealing with an output list

### ISSUE THREAD

**Issue by sw-samuraj** [gruntwork-io/terratest#167]
**Question:**
The _Terraform_ output can be defined as a list, e.g.

```tf
output "CPPublicIPs" {
  value = ["${oci_core_instance.CPServer.*.public_ip}"]
}
```

will provide a following output:

```
CPPublicIPs = [
    129.146.109.157,
    129.146.111.161,
    129.146.101.69
]
```

However, _Terratest_ function `Output` provides just a `string`. Is there a recommendation how to deal with _output list_? Does it have to be parsed manually? E.g.

```go
out := terraform.Output(t, terraformOptions, "CPPublicIPs")
ips := strings.Split(out, "\n")
```

Wouldn't be convenient to have a function like `OutputList(t *testing.T, options *Options, key string) []string`?

**Comment by brikis98** [comment]
> Wouldn't be convenient to have a function like OutputList(t *testing.T, options *Options, key string) []string?

Yes. We actually have functions like this in some of our individual tests, but have not yet extracted them into Terratest itself. A PR for that would be very welcome! Using the JSON output and a JSON parser is probably the way to go.

**Comment by yorinasub17** [comment]
`OutputList` and `OutputMap` were introduced since [v0.13.6](https://github.com/gruntwork-io/terratest/releases/tag/v0.13.6)
