### ISSUE TITLE
DynamoDb support

### ISSUE THREAD

**Issue by rafaelmarques7** [gruntwork-io/terratest#181]
Hello,

First of all, let me start by saying that I recently discovered this library, and that I truly appreciate it, as it is very useful! 

With that being said, I was trying to test a terraform module that created dynamoDb tables.
During the tutorials, I noticed it was possible to test RDS databases, but now, upon viewing the documentation  of the [aws package](https://godoc.org/github.com/gruntwork-io/terratest/modules/aws), I noticed that there was no function available for testing DynamoDb. 

Is this really the case, or did I missed the function completely?

**Comment by brikis98** [comment]
We have not yet added helpers for working with DynamoDB. PR very welcome 😃

**Comment by iamjohnnym** [comment]
@brikis98 Given that @rafaelmarques7 doesn't have the time, I'll see if I can tackle this.  Do you have a specific vision for this, anything that you can think of that I should keep in mind when doing?

**Comment by brikis98** [comment]
Thanks @iamjohnnym! 

I imagine the most useful functionality would be:

- Create a DynamoDB table
- Wait until the table exists and is ready (remember, AWS APIs are async + eventually consistent) 
- Write some data
- Read some data
- Delete a DynamoDB table

**Comment by iamjohnnym** [comment]
That's fair.

I'll take over @rafaelmarques7 original work.  From there, I'll address your questions from that PR.  I also have a more immediate needs to check metadata of a dynamoDB table.

So I understand a bit better.  What processes use the create/destroy methods of a given resource?  I understand looking at attributes on AWS that gets deployed by terraform but what does `terratest` do with methods that create resources?

**Comment by brikis98** [comment]
> What processes use the create/destroy methods of a given resource? I understand looking at attributes on AWS that gets deployed by terraform but what does terratest do with methods that create resources?

Not sure I understand the question?

**Comment by yorinasub17** [comment]
Initial set of DynamoDB functions were introduced in https://github.com/gruntwork-io/terratest/releases/tag/v0.15.11. If there are more to add, please file new tickets. Thanks!
