### ISSUE TITLE
http_helper package is covering HTTP GET methods only and doesn't allow to send HTTP Headers

### ISSUE THREAD

**Issue by sw-samuraj** [gruntwork-io/terratest#186]
The `http_helper` package currently supports the HTTP `GET` method only. Additionally, it doesn't allow to send any HTTP Header.

**Questions:**

1) Is it planned to support other HTTP methods, e.g. `POST`?

2) Is it planned to support HTTP Headers? This could be important if a service expects some mandatory headers, e.g. a token etc.

**Comment by brikis98** [comment]
We add methods when we use them. So far, most of our tests have needed GET and no headers, but if you have a use case that needs more, I'd definitely welcome a PR to add those!

**Comment by robmorgan** [comment]
Fixed in https://github.com/gruntwork-io/terratest/releases/tag/v0.18.5
