### ISSUE TITLE
-Var-File Support

### ISSUE THREAD

**Issue by tcmoody** [gruntwork-io/terratest#192]
Hello all, I use the tfvars file just about everywhere for my terraform (try to avoid using the -var arg), is there any chance that -var-file arg support will be coming soon?

**Comment by brikis98** [comment]
We had no plans to add it, but a PR would be welcome! You'd add it to [terraform.Options](https://github.com/gruntwork-io/terratest/blob/master/modules/terraform/options.go#L12) and add the appropriate CLI args [here](https://github.com/gruntwork-io/terratest/blob/master/modules/terraform/cmd.go#L15).

**Comment by berney** [comment]
You may be able to use this technique:

Use the `TerraformDir` in `terraform.Options` you can put your `*.auto.tfvars` and `terraform.tfvars` files there and they'll be auto-loaded.

This works well in a lot of scenarios. It won't work well if you want to have many tests where the terraform code (under test) `TerraformDir` is the same and you want to use different `.tfvars` files to change some complex variables (that can't be passed in `Vars` (`-var`)).

I too welcome a PR adding `-var-file` support.

**Comment by brikis98** [comment]
This is being worked on in https://github.com/gruntwork-io/terratest/pull/201

**Comment by kurtmaile** [comment]
+1

**Comment by pysysops** [comment]
@tcmoody - Now that #201 is merged I think that this can be closed 😃
