### ISSUE TITLE
Make terratest_log_parser token buffer size configurable

### ISSUE THREAD

**Issue by yorinasub17** [gruntwork-io/terratest#203]
If the log contains a word that is longer than 64*1024 characters, `terratest_log_parser` will crash with `FATA[2018-12-06T01:00:04Z] Error reading from scanner: bufio.Scanner: token too long `

**Comment by trobert2** [comment]
I am also having this problem when trying to do `	terraform.InitAndApply(t, terraformOptions)` and the module I am testing has long files to pass in.
```
    apply.go:13: FatalError{Underlying: bufio.Scanner: token too long}
```

**Comment by yorinasub17** [comment]
Reopening as that PR doesn't actually fix this issue.

**Comment by pearcec** [comment]
This fixed it for me.  Did you add OutputMaxLineSize to your terraform.Options
tfOptions := &terraform.Options{
	TerraformDir: "../examples/definition",
	OutputMaxLineSize: 128 * 1024,
}

**Comment by yorinasub17** [comment]
This is now fixed in https://github.com/gruntwork-io/terratest/releases/tag/v0.26.6
