### ISSUE TITLE
ec2.go doesn't like non-standard ec2 instance ID's

### ISSUE THREAD

**Issue by aries-strato** [gruntwork-io/terratest#204]
Trying to use terratest with Stratoscale Symphony and it appears ec2.go doesn't like the way instance ID's look in Symphony vs what it expects from AWS:

In Symphony instance ID's are a bit longer, eg: i-d04e3e86b706490f9dfe6b3d2fc910cf

Whereas aws ec2 instance ID's are much shorter, eg: i-0d2203701b120a204

Here is the result of a sample Terratest destroy:

--- FAIL: TestTerraformAwsExample (88.31s)
    ec2.go:171: InvalidID: The ID 'i-d04e3e86b706490f9dfe6b3d2fc910cf' is not valid
         status code: 400, request id: 8bda744a-ad29-4fba-a6e4-a96fc8eeca4b
FAIL

**Comment by brikis98** [comment]
AFAIK, `ec2.go` does not itself parse Instance IDs... We just pass them to the AWS SDK ([relevant code based on your error message](https://github.com/gruntwork-io/terratest/blob/master/modules/aws/ec2.go#L168-L196)), so judging by the 400 error, I think this is AWS complaining about your instance IDs, not Terratest.

**Comment by aries-strato** [comment]
Thanks @brikis98  - I guess I'll need to look further into the AWS SDK for Go and see what needs to be modified there.

**Comment by iamdheee** [comment]
how do i fix this? could you help?
    ec2.go:284: 
                Error Trace:    ec2.go:284
                                                        terraform_aws_example_test.go:46
                Error:          Received unexpected error:
                                InvalidInstanceID.NotFound: The instance ID 'i-00b2e1ecef37b5674' does not exist
                                        status code: 400, request id: 1692c5cc-aa41-49bc-8478-fb1e6197aedb
