### ISSUE TITLE
Function to get private IP of EC2 instances

### ISSUE THREAD

**Issue by drmmarsunited** [gruntwork-io/terratest#211]
Hello!  I'd like to contribute some code functions to retrieve the `PrivateIpAddress` from a given EC2 instance.  In my use case, I launch nodes into an AWS ASG without public IPs and no ALB/ELB up front.  However, I have services that should be exposed via HTTP/HTTPS on these nodes that should be reachable from my test instance over direct connect.

Happy to contribute the code myself!  Didn't see any other open issues around this, but please let me know if there are.

**Comment by drmmarsunited** [comment]
In preparation for carrying out the work, I don't see a `_test` file for `ec2.go` in the *aws* module.  Where are the tests (if there are any) for those functions?  Sorry if I'm missing something terribly obvious!

**Comment by brikis98** [comment]
Sounds like a great addition!

We have tests in two places:

1. `_test.go` files. These are mostly "unit tests" (they're not purely unit tests in many cases, as this is infra code, but close enough).

1. Tests in the `/test` folder. These are automated tests for the examples in the `/examples` folder. We try to have as many of these as they are effectively executable documentation that shows how Terratest is meant to be used—and tests Terratest at the same time!

**Comment by drmmarsunited** [comment]
Worth an out-loud brainstorm:

Incorporating an example of my use case wouldn't necessarily work, given that it's dependent upon routing setups of the network in which the test instance relies on.  I was trying to think of a simple way to incorporate a test that would run publicly without much fuss, and the simplest one I could conjure up was:

1. Modify the basic HTTP Terraform example to output the instance's `private_ip` attribute
2. Within the `_test.go` file, run the newly created `GetPrivateIpOfEc2Instance` function and compare it to the output attribute to ensure a match

The inverse to that was to write a negative test to ensure that attempting to connect to the private IP of an instance over SSH and/or an HTTP port would fail, but this feels wrong given that it *could* be possible with the right network setup, and I don't want to confuse Terratest users.

Thoughts?

**Comment by brikis98** [comment]
The SSH code in Terratest can use a "jump host": https://github.com/gruntwork-io/terratest/blob/master/modules/ssh/ssh.go#L237. So, one option:

1. Launch 2 EC2 instances
1. Get the public IP of one
1. Get the private IP of the other
1. SSH to the private IP using the public IP as a jump host

**Comment by drmmarsunited** [comment]
Will do.  Thanks.

**Comment by drmmarsunited** [comment]
PR out: #212

**Comment by drmmarsunited** [comment]
Thanks for all the quick turnarounds!
