### ISSUE TITLE
GCP cloudfunctions

### ISSUE THREAD

**Issue by acrisci** [gruntwork-io/terratest#226]
I would like to do some testing for GCP cloudfunctions.

Bascially I need:

* assert cloud function exists
* assert cloud function was called

Possibly some other stuff.

Is this within scope for the Terratest GCP module?

I can do the second one with stackdriver logs but not sure if that's the best approach.

Contributor ready.

**Comment by josh-padnick** [comment]
@acrisci Another way of testing that a cloud function exists and was called is actually trying to invoke it and checking that you got the expected response.

**Comment by acrisci** [comment]
Forgot to mention that I may invoke from a trigger, not directly (like pubsub or storage object change). But if it's a pain maybe I could skip that part.
