### ISSUE TITLE
Can Terratest be used to provide the details of provisioned resources

### ISSUE THREAD

**Issue by chetanchatrath** [gruntwork-io/terratest#235]
Hi Team,
[This is a question]
I am exploring the Terratest features and would like to understand if it can be used in the following scenario:

1. Terraform scripts provision and/or update the required infrastructure (terraform init, plan, apply)
2. Use Terratest to test if the required infrastrcuture has been provisioned or updated sucessfully as per the scripts
3. Provide readable test reports to Ops for step 2.. If yes, then can the information be written in a file which can be used.

I dont want to incur costs by creating a separate infrastructure and deleting it for test purposes.

**Comment by brikis98** [comment]
> Terraform scripts provision and/or update the required infrastructure (terraform init, plan, apply)
> Use Terratest to test if the required infrastrcuture has been provisioned or updated sucessfully as per the scripts

Yes... The [examples](/examples) and corresponding [tests](/tests) cover this extensively.

> Provide readable test reports to Ops for step 2.. If yes, then can the information be written in a file which can be used.

Currently, the only output is whatever logging you put in, and Go's default test output. If you're looking for a report, you'd probably have to write something custom!

> I dont want to incur costs by creating a separate infrastructure and deleting it for test purposes.

The whole goal of Terratest is to deploy your infrastructure for real, as that's critical to building confidence that your infrastructure actually works. See [How Terratest compares to other testing tools
](https://github.com/gruntwork-io/terratest#how-terratest-compares-to-other-testing-tools) for more info.

**Comment by chetanchatrath** [comment]
Hi,
I have noticed that Terraform follows the pattern of installing the infrastructure and then running the test and then destroy it. I was looking for a tool which can provide the information of the resources that are installed once the terraform deploys the resources in production. 
Secondly, if terraform has been used for initial deployment and then there are additional resources that need to be added on top of the initial deployment, Terraform will just install the new resources and destroy the ones not mentioned. Using Terratest can we just get the list of the delta resources?

**Comment by brikis98** [comment]
> I was looking for a tool which can provide the information of the resources that are installed once the terraform deploys the resources in production.

Yes, you can use Terratest for this. Just don't call `terraform.Destroy` in your test code...

> Secondly, if terraform has been used for initial deployment and then there are additional resources that need to be added on top of the initial deployment, Terraform will just install the new resources and destroy the ones not mentioned. Using Terratest can we just get the list of the delta resources?

Not sure I understand this use case. If you ran `apply` on your Terraform code, then changed the code, you can run `plan` to see what changes Terraform will deploy...

**Comment by chetanchatrath** [comment]
Hi,
Thanks for answering my 1 question.

I am exploring the features of terratest and would like to know how it can
be used in the following scenario:





-The production already has inrastructure created using non-terraform
approach.

-The terraform files have been designed to create/update infra over and
above the already existing.


Thanks

Chetan

**Comment by brikis98** [comment]
If you deployed infrastructure NOT using Terraform, then you need to import the state so you can manage it with Terraform. See [terraform import](https://www.terraform.io/docs/import/index.html) and [terraforming](https://github.com/dtan4/terraforming) for more info.
