### ISSUE TITLE
Apply - Resource counts from appy

### ISSUE THREAD

**Issue by kurtmaile** [gruntwork-io/terratest#236]
Hi,

In terratest is it possible from terraform.Apply to capture the resource added, changed and destroyed counts from the apply?  This info is quite key and a simple first up check when you know what these should be in terms of expected counts.

Quickly looking at the code I assume a string parse of 'out' from RunTerraformCommandE is required?

Cheers!

**Comment by brikis98** [comment]
Yup, you'll need to parse the `stdout` / `stderr` to get this info!

**Comment by aclowkey** [comment]
In stdout it's pretty straight forward. We can parse the string with regex `(Apply|Destroy) complete! Resources: (.+)`, split group \# 2 by comma, and extract `\d+ (added|changed|destroyed)`
>Apply complete! Resources:1 added, 1 changed, 1 destroyed

Then return a struct similar to 
```go
type ResourceCount struct {
	Added     int
	Changed   int
	Destroyed int
}
```
But why should we parse the stderr? doesn't it imply

**Comment by brikis98** [comment]
> Not sure if the command implementation should always return these counts, or they should be additional package `output_utils.get_counts(out)`? Which later could be expanded to perhaps parse planned resource?

Seems like a standalone command that takes in a string and returns these counts or an error would be the better approach. You can then combine it with `apply` or `plan` or `destroy` as needed.

> But why should we parse the stderr? doesn't it imply that nothing happened thus no resource counts?

Terraform logs some things to `stdout`, some to `stderr`, and I didn't remember off the top of my head which one this goes to, so if it's `stdout`, then that's just fine.

**Comment by kurtmaile** [comment]
thanks for comments - feels like a valuable assertion to be able to create as part of overall tests.  I can have a look at this.  appreciate the guidance above thanks!

**Comment by aclowkey** [comment]
I implemented a large part of it. Not sure if I'll have the time to write
tests for it.

I'll share the function in this thread soon. Quite simple regexparse

**Comment by kurtmaile** [comment]
awesome!  Its more for me as a newbie to this tool as to the best place to slot this feature in.  Regex pretty simple as you say.  Let me know, happy to pick it up from you if you dont have time to finish it.

**Comment by aclowkey** [comment]
Unfortunately Im moving out and packed my pc already.. So maybe in the next
week :(

**Comment by kurtmaile** [comment]
no probs - good luck with move, le me know when you are ready :)

**Comment by aclowkey** [comment]
```go
// GetResourceCount parsed apply output and returns number of affected resources.
func GetResourceCount(stdout string) (*ResourceCount, error) {
	pattern, err := regexp.Compile("(Destroy|Apply) complete! Resources: ((\\d+) added, (\\d+) changed, )?(\\d+) destroyed.")
	if err != nil {
		return nil, err
	}
	matches := pattern.FindStringSubmatch(stdout)
	added, err := strconv.Atoi(matches[3])
	if err != nil {
		return nil, err
	}
	changed, err := strconv.Atoi(matches[4])
	if err != nil {
		return nil, err
	}
	destroyed, err := strconv.Atoi(matches[5])
	if err != nil {
		return nil, err
	}
	return &ResourceCount{
		Added:     added,
		Changed:   changed,
		Destroyed: destroyed,
	}, nil
}

// ResourceCount represnts count of apply / destroy command
type ResourceCount struct {
	Added     int
	Changed   int
	Destroyed int
}

```
Tip for writing a test for this: You can change the `count` attribute of a resource to check for added / destroyed resources. To change, just rename a var. 

:)

**Comment by kurtmaile** [comment]
Great thanks!

**Comment by klebediev** [comment]
Is somebody working on this functionality?
Should it be a function in `terraform` package?

**Comment by yorinasub17** [comment]
A version of this has been implemented in https://github.com/gruntwork-io/terratest/releases/tag/v0.17.1.
