### ISSUE TITLE
Add more test-structure helpers for saving and loading *Options?

### ISSUE THREAD

**Issue by kirecek** [gruntwork-io/terratest#239]
Are PRs with save/load data helpers welcomed? For example [kubectl options](https://godoc.org/github.com/gruntwork-io/terratest/modules/k8s#KubectlOptions). Or should I keep using generic `SaveTestData` in my tests?

**Comment by yorinasub17** [comment]
Yup PRs welcome! save/load data helpers for kubectl options sounds like it will be a great addition!
