### ISSUE TITLE
storage.go dialing Google: Could not find default credentials

### ISSUE THREAD

**Issue by git4raj** [gruntwork-io/terratest#243]
I have a sample code to work in my terminal that calls a terraform template which creates and destroys a bucket, verifies by calling gcp.AssertStorageBucketExists(). 

When I try the same in my pipeline, all works (creates & destroys the bucket) but throws the following error when calls to check the bucket.

line 184: storage.go dialing Google: Could not find default credentials. Looks like, The context.Background doesn't have the proper credentials in the container shell where the test.go gets executed.

Any idea, how to give authentication info?

**Comment by brikis98** [comment]
@Etiene or @robmorgan could you help out?

**Comment by git4raj** [comment]
Just an update. I ran gcloud auth activate --key-file filename.json. It says the service account is authenticated. When I run gcloud compute instances list - it lists all instances . I do these two command right before the go test. However, the error while calling gcp.AssertStorageBucketExists() continues. The line 184 that is referenced in storage.go is context.Backend(). Appreciate your help.

**Comment by git4raj** [comment]
Even though the terminal shell is authenticated and all the commands gcloud works in the shell, the gcp.AssertStorageBucketExists() / context.Backend() - looks only at the environment variable GOOGLE_APPLICATION_CREDENTIALS. I did the following in the container as part of the pipeline
export GOOGLE_APPLICATION_CREDENTIALS="/home/user/Downloads/[FILE_NAME].json"

as mentioned in https://cloud.google.com/docs/authentication/production#auth-cloud-implicit-go

I'm documenting here for folks who are in the same journey. Having said that, it should not be looking at ONLY this env variable. It should be able to use the whatever is authenticated in the shell.

**Comment by robmorgan** [comment]
Hi @git4raj yes its due to the behaviour of the Google Cloud SDK we use. As you mentioned the SDK is expecting the `GOOGLE_APPLICATION_CREDENTIALS` environment variable to be set. We also rely on a number of different environment variables in Terratest. See: https://github.com/gruntwork-io/terratest/blob/master/modules/gcp/provider.go

I agree that this could be documented better so I'll leave this issue open for now. Side note: We should also move to supporting `GOOGLE_APPLICATION_CREDENTIALS`.

**Comment by git4raj** [comment]
On another note, I notice that the GCP provider has only Storage and Compute. Even there, it is pretty minimal (for storage only bucketexists), unlike AWS, where you can check labels etc. Would you know something coming? Can I test?

**Comment by robmorgan** [comment]
I'm closing this issue for now. Feel free to open another one to discuss changes to the modules.
