### ISSUE TITLE
[Question] Use case for save/load options in RunTestStages

### ISSUE THREAD

**Issue by kirecek** [gruntwork-io/terratest#244]
Hello,

how should I use and what's the correct use case for saving/loading options and using RunTestStage?

For example let's consider this snippet inspired by https://github.com/hashicorp/terraform-aws-consul/blob/master/test/consul_helpers.go :

```go
package test

import (
	"testing"

	"github.com/gruntwork-io/terratest/modules/aws"
	"github.com/gruntwork-io/terratest/modules/terraform"
	test_structure "github.com/gruntwork-io/terratest/modules/test-structure"
)

const SAVED_AWS_REGION = "AwsRegion"

func TestExample(t *testing.T) {
	exampleFolder := test_structure.CopyTerraformFolderToTemp(t, ".", ".")

	test_structure.RunTestStage(t, "setup_ami", func() {
		awsRegion := aws.GetRandomRegion(t, nil, []string{"eu-north-1"})
		test_structure.SaveString(t, exampleFolder, SAVED_AWS_REGION, awsRegion)
	})

	test_structure.RunTestStage(t, "deploy", func() {
		awsRegion := test_structure.LoadString(t, exampleFolder, SAVED_AWS_REGION)
		_ = awsRegion
		// ...
		terraformOptions := &terraform.Options{}
		test_structure.SaveTerraformOptions(t, exampleFolder, terraformOptions)
	})

	test_structure.RunTestStage(t, "validate", func() {
		terraformOptions := test_structure.LoadTerraformOptions(t, exampleFolder)
		_ = terraformOptions
		// ..
	})
}
```

Due to using Load in deploy and validate stage, I cannot skip "setup_ami" and neither "deploy".
```bash
$ SKIP_setup_ami go test
Failed to load value from .test-data/AwsRegion.json: open .test-data/AwsRegion.json: no such file or directory
$ SKIP_deploy=1 go test
Failed to load value from .test-data/TerraformOptions.json: open .test-data/TerraformOptions.json: no such file or directory
```
---

1. What's the benefit of using `RunTestStage` since it can't be skipped in the most cases?

2. If I skip stage containing **SaveTerraformOptions**, shouldn't **LoadTerraformOptions** return empty options instead of failing?

3. Shouldn't be options declared in the function's scope and just reused in or passed to closures?

*Sorry, I'm confused. What am I missing here?*

Thanks :)

**Comment by brikis98** [comment]
I think you're missing a stage in that snippet called `teardown` that runs `terraform destroy`.

Typical usage pattern:

1. `SKIP_teardown=true go test ...` <-- build the AMI, deploy Terraform, run validations.
1. Make tweaks in Terraform code to fix bugs.
1. `SKIP_teardown=true SKIP_setup_ami=true go test...` <-- we didn't have to rebuild the AMI!
1. Repeat two steps above x 10.
1. Finally, Terraform code works, now start tweaking validation logic.
1. `SKIP_teardown=true SKIP_setup_ami=true SKIP_deploy=true go test...` <-- we didn't have to rebuild the AMI or redeploy Terraform!
1. Finally, validation logic works.
1. ` SKIP_setup_ami=true SKIP_deploy=true go SKIP_validation=true test...` <-- skip straight to teardown

**Comment by kirecek** [comment]
Thanks! I was missing this usage pattern :) Now I get it.
