### ISSUE TITLE
Add support for AWS Security Groups

### ISSUE THREAD

**Issue by jakauppila-sentry** [gruntwork-io/terratest#250]
We are building some core security group modules that create a suite of security groups that provide various ingress/egress across the enterprise. With that we want to build some tests to validate that the particular rules we're building are getting applied as expected.

**Comment by brikis98** [comment]
Generally, the best way to test that your security groups are working, is to try to send some traffic through them (e.g., using the helpers for making HTTP requests, SSH connections, DB connections, etc that are already built into Terratest)! See [How Terratest compares to other testing tools
](https://github.com/gruntwork-io/terratest#how-terratest-compares-to-other-testing-tools).

**Comment by jakauppila-sentry** [comment]
Is verifying that the rules I have configured to be created something I should be even worrying about? It might be better handled by awsspec to directly check those attributes of the resource.

At this individual resource level, I trust that security groups work as designed, I just want to verify that it was configured correctly.

**Comment by brikis98** [comment]
> It might be better handled by awsspec to directly check those attributes of the resource.

If you're primarily interested in checking these sorts of properties, then yes, the various xxx-spec tools may be a better fit.

> At this individual resource level, I trust that security groups work as designed, I just want to verify that it was configured correctly.

Security Groups probably work as you intend, but whether you're using them correctly, or have other issues that get in the way, is a completely different matter. It would be very easy to open up, say, port 12345, and validate via AWS APIs that the port is indeed listed in your Security Group, but then to find out that requests to port 12345 still fail. They could fail for any number of reasons: e.g., you set the port params, but not the right CIDR block params; or you opened up the wrong protocol; or you created an egress rule when you meant to create an ingress rule; or you have a network ACL blocking the requests even if the security groups allow them; or your server is actually listening on port 12346; or a dozen other potential bugs.

The Terratest philosophy would help you catch the vast majority of such bugs; merely checking if your security group includes port 12345 will not.

**Comment by jakauppila-sentry** [comment]
Yup, totally get that. We have sub-modules that configure specific security groups and want to have tests that validate those individual components, so to that end, I'm probably better off just inspecting the Terraform output for the values since I should be confident that Terraform is doing it's job.

We're also planning to have the holistic example that combines all the security groups that will be part of a typical deployment, create servers, and validate connectivity between them with Terratest which falls more in-line with the philosophy.
