### ISSUE TITLE
terraform variable precedence

### ISSUE THREAD

**Issue by matt-smith** [gruntwork-io/terratest#255]
When setting the same variable (for example `"example_var"`) in both `VarFiles` and `Vars` terraformOptions, ordering is not honoured and therefore the [variable precedence](https://www.terraform.io/docs/configuration/variables.html#variable-definition-precedence) is incorrect. The value of the variable in the VarFile will always be applied despite the ordering inside of the test.

For example:
```
...
	terraformOptions := &terraform.Options{
		// The path to where our Terraform code is located
		TerraformDir: "../examples/terraform-basic-example",

		// Variables to pass to our Terraform code using -var-file options
		VarFiles: []string{"varfile.tfvars"},

		// Variables to pass to our Terraform code using -var options
		Vars: map[string]interface{}{
			"example_var": "test123",
		},

		// Disable colors in Terraform commands so its easier to parse stdout/stderr
		NoColor: true,
	}
...
``` 

and `varfile.tfvars` contained 

```
...
example_var = "test456"
...
```

`example_var` would always be set to `test456`

looks like https://github.com/gruntwork-io/terratest/blob/master/modules/terraform/format.go#L14-L15 is causing this behaviour.

**Comment by brikis98** [comment]
Are you expecting `-var-file` to go first always?

The docs say:

> Any -var and -var-file options on the command line, in the order they are provided. 

"The order they are provided" doesn't really make much sense in a `terraform.Options` struct. There's no way in Go to know what order you provided those variables.

**Comment by matt-smith** [comment]
Hey @brikis98, thanks for your response and explanation. 

I think it's more likely that a user would want one or two variables passed in as `-var`'s to take precedence over a larger `-var-file` perhaps. What do you think?

I've opened a small PR [PR-256](https://github.com/gruntwork-io/terratest/pull/256) with my changes.

**Comment by brikis98** [comment]
Having `-var` take precedence over `-var-file` probably makes sense. That said, in most use cases, we only use one of `-var` or `-var-file`, not both, as keeping things in one place makes it easier to reason about the code.

**Comment by sebastianczech** [comment]
As far as I was checking, #1217 resolves that issue. If you define ``SetVarsAfterVarFiles: true``, then values passed in ``Vars`` take precedence over values from ``VarFiles`` e.g.:

```go
terraformOptions := terraform.WithDefaultRetryableErrors(t, &terraform.Options{
	TerraformDir: ".",
	VarFiles:     []string{"example.tfvars"},
	Vars: map[string]interface{}{
		"example": "value_passed_from_test",
	},
	SetVarsAfterVarFiles: true,
})
```

**Comment by matt-smith** [comment]
perfect thanks @sebastianczech , I'll close this issue in that case.
