### ISSUE TITLE
(Question) Shell Module

### ISSUE THREAD

**Issue by MichaelSmyth0184** [gruntwork-io/terratest#261]
Hi,
I am looking at using TerraTest to potentialy spin up an ec2 server, run a command to get the version of the operating system and compare that to the tag value assigned to the server.
Would this be possible using the Shell module provided? And if so would it be possible to provide an example of this?

Any help on the matter would be greatly appreciated!

Many thanks,

Michael

**Comment by brikis98** [comment]
Check out the `examples` and `test` folders. There are plenty of examples of how to deploy an EC2 Instance, how to SSH to it and run commands on it, and how to look up the tags of the Instance.

**Comment by MichaelSmyth0184** [comment]
Is there any examples remoting onto Windows machines and running shell commands?

Thanks,

Michael

**Comment by brikis98** [comment]
Hm, no, I don't think so. We've mainly been using Terratest with Linux/SSH. I don't think we have support for Windows/RDP yet.

**Comment by MichaelSmyth0184** [comment]
Thanks @brikis98,

I thought as much, was looking into possibly installing OpenSSH on the Windows AMIs as a workaround but not sure if it will work.

Thanks Anyways.
