### ISSUE TITLE
varfile.tfvars in a separate folder

### ISSUE THREAD

**Issue by yorinasub17** [gruntwork-io/terratest#266]
From @SandyLQ

> Hello, I have a question, when I put the "varfile.tfvars" file not in the same folder with the terraform script, then it always tell me cannot find the file even i point to the right path, why is that?

https://github.com/gruntwork-io/terratest/commit/6e2e51618f4ed266f598dc5f7c624fe4c56772e7#commitcomment-32871552

**Comment by yorinasub17** [comment]
Hi @SandyLQ,

Is the path you are using a relative path or absolute path? When using relative paths, one thing to note is that the `VarFiles` key of the `terraform.Options` is sourced relative to the terraform code, NOT the go test code OR the cwd where you are running the tests.

The reason for this is that the `VarFiles` key is passed in directly to the `terraform` call, which is running out of the directory with the terraform code (e.g our examples folder).

**Comment by SandyLQ** [comment]
Hello @yorinasub17 , Thanks a lot for the quick feedback. So you mean that the varFiles path should be the relative one to where the TerraformDir is? In that case then finally I understand that why in another project it was working for me, seems accidentally the path of the varfile is in the right place. I thought it is the relative path of the test code. Now it makes sense, Thanks a lot again.!

**Comment by yorinasub17** [comment]
@SandyLQ Yup that is what I meant! I am going close this issue, but feel free to open if you still run into challenges getting the `VarFiles` to work.

**Comment by bj-1795** [comment]
@yorinasub17  I have mentioned my tfvars in same dir as my tf module which contains multiple folders, I am still getting does not exist error.
