### ISSUE TITLE
Can I call ApplyandInit multiple times within one Test?

### ISSUE THREAD

**Issue by SandyLQ** [gruntwork-io/terratest#269]
Hello, I am using terratest for some testing work, first I called applyandInit, and it was good, but I need to create extra resources after the first was created  to be able to assert, is it possible that I called once InitAndApply(), and I define a new options, and call again InitAndApply within the same test?

**Comment by SandyLQ** [comment]
BTW, I tried it out, it seems that it was trying to apply the second script also, but before that, it was trying to destroy the first one that created , which in the test I commented out the destroy command...

**Comment by yorinasub17** [comment]
Hi @SandyLQ,

Yes you can all `InitAndApply` as many times as you want, and it will do exactly that: run `terraform init` and then `terraform apply` with the parameters specified in `terraform.Options`.

In terms of the destruction behavior you are seeing, I probably need more context. Without seeing your code, my best guess as to what is happening is that the second script is running with parameters that modifies which resources are enabled (possibly using a `count`?) **from the same module path**. Is that what you are doing?

**Comment by SandyLQ** [comment]
@yorinasub17  Hello, you are right, accidently in my second script, when I was setting up the backend (which I cipied from the first one), and that was the problem, it shared the same tfstate, and it was trying to destroying everything first, after I modified the back end configuration, it works fine. Thank you agian for the quick response!

**Comment by yorinasub17** [comment]
@SandyLQ Great! Glad to help!
