### ISSUE TITLE
client-go is not enough arguments when call

### ISSUE THREAD

**Issue by naviat** [gruntwork-io/terratest#276]
I switch to run terratest with go module (not use dep), it's ok when used for the basic and http example, but when I create ssh example, I got an error about `k8s.io/client-go/rest`

```
# k8s.io/client-go/rest
../../../pkg/mod/k8s.io/client-go@v11.0.0+incompatible/rest/request.go:598:31: not enough arguments in call to watch.NewStreamWatcher
	have (*versioned.Decoder)
	want (watch.Decoder, watch.Reporter)
```

**Comment by brikis98** [comment]
FWIW, we have not yet switched to go.mod; we will once it is enabled by default (which it should be in Go 1.13).

I think @yorinasub17 had hit similar issues with the K8S libraries before; see https://github.com/gruntwork-io/terratest/pull/270.

**Comment by yorinasub17** [comment]
Hi @naviat ,

Looking at the error message, it looks like it is pulling in `k8s.io/client-go` version `11.0`. We depend on the `9.0` track (for compatibility reasons with EKS, which runs an older version of kubernetes). You need to lock the versions of the libraries to those that are specified in [our `Gopkg.toml` file](https://github.com/gruntwork-io/terratest/blob/master/Gopkg.toml).

**Comment by yorinasub17** [comment]
Also see https://github.com/gruntwork-io/terratest/pull/264.

**Comment by naviat** [comment]
Thanks @brikis98  @yorinasub17  It's OK now.
