### ISSUE TITLE
Feature request: Packer -var-file option

### ISSUE THREAD

**Issue by bflugon** [gruntwork-io/terratest#285]
We're currently using -var-file in packer to build our images with different accounts in AWS. Would it be possible to add this support to terratest too, instead of having to specify each var separately?

**Comment by yorinasub17** [comment]
That sounds like a useful addition. We haven't planned on implementing it, but a PR would be welcome!

This could be done by adding the option to [packer.Options](https://github.com/gruntwork-io/terratest/blob/master/modules/packer/packer.go#L16) and updating [formatPackerArgs](https://github.com/gruntwork-io/terratest/blob/master/modules/packer/packer.go#L136) to utilize it.

**Comment by yorinasub17** [comment]
Released in https://github.com/gruntwork-io/terratest/releases/tag/v0.15.6
