### ISSUE TITLE
Feature Request: Add functionality to check S3 bucket versioning

### ISSUE THREAD

**Issue by drmmarsunited** [gruntwork-io/terratest#288]
In the current `aws` module, the helper functions available for looking at / checking S3 bucket attributes are non-existent.  In the first of a few checks, I'd like to start adding support for people to ensure buckets they roll out meet their defined configuration.

PR link coming shortly

**Comment by drmmarsunited** [comment]
PR linking complete

**Comment by drmmarsunited** [comment]
Also going to be adding a PR to check for existence of bucket policies

**Comment by zackproser** [comment]
Thanks for your contribution! I'm going to close this issue now as your PR was successfully merged.
