### ISSUE TITLE
http helper - to enable InsecureSkipVerify option

### ISSUE THREAD

**Issue by spanspan** [gruntwork-io/terratest#292]
I have a use case where I need to check an insecure url. 
currently http_helper doesn't have option to set InsecureSkipVerify to true.

**Comment by brikis98** [comment]
That would be a good addition. PR welcome!

**Comment by yorinasub17** [comment]
FYI @geass was working on this in https://github.com/gruntwork-io/terratest/pull/282, but there are a few changes that need to be made there.

**Comment by drmmarsunited** [comment]
Working on this under #336 as #282 looks like it went stale

**Comment by yorinasub17** [comment]
This was released in https://github.com/gruntwork-io/terratest/releases/tag/v0.18.0
