### ISSUE TITLE
Error with passing variables as list of string to terraform commands

### ISSUE THREAD

**Issue by s012sameer** [gruntwork-io/terratest#293]
Hi!
I am trying to test my **AWS IAC** using terratest.
But whenever I'm trying to pass a list of strings from **terratest** to **terraform**. I'm getting error of wrong syntax from terraform.

Terraform version - Terraform v0.11.11

**some variables i'm using** : 
expectedSecurityGroupNames  := []string {"terratest_eth0_security_group", "terratest_eth1_security_group"}
subnetCidrBlocks     := map[string]string {   "terratest_eth0" : "10.1.1.0/24", "terratest_eth1" : "10.1.2.0/24" }

**this is what getting passed to terraform -** 
Running terraform [apply -input=false -lock=false -auto-approve -var vpc_name=terratest-vpc-XAZAD9 -var enable_dns_support=true -var az=ap-southeast-1c -var subnet_names=[terratest_eth0, terratest_eth1] -var map_public_ip_on_launch={terratest_eth0 = false, terratest_eth1 = false} -var source_dest_check_list=[true, false] -var region=ap-southeast-1 -var profile=default -var vpc_cidr_block=10.1.0.0/16 -var enable_dns_hostnames=true -var subnet_cidr_blocks={terratest_eth0 = 10.1.1.0/24, terratest_eth1 = 10.1.2.0/24} -var security_group_names=[terratest_eth0_security_group, terratest_eth1_security_group] -var private_ips_count_list=[1, 0]]

**This is expected -** 
Running terraform [apply -input=false -lock=false -auto-approve -var vpc_cidr_block="10.1.0.0/16" -var enable_dns_hostnames="true" -var enable_dns_support="true" -var subnet_cidr_blocks={terratest_eth0 = "10.1.1.0/24", terratest_eth1 = "10.1.2.0/24"} -var map_public_ip_on_launch={terratest_eth0 = "false", terratest_eth1 = "false"} -var source_dest_check_list=["true", "false"] -var vpc_name="terratest-vpc-psnigE" -var profile="default" -var az="ap-southeast-1c" -var subnet_names=["terratest_eth0", "terratest_eth1"] -var security_group_names=["terratest_eth0_security_group", "terratest_eth1_security_group"] -var private_ips_count_list=["1", "0"] -var region="ap-southeast-1"]

I'm facing this issue from last week only after few changes in [format.go](https://github.com/gruntwork-io/terratest/blob/master/modules/terraform/format.go) file.

**Error I got**  -

invalid value "security_group_names=[terratest_eth0_security_group, terratest_eth1_security_group]" for flag -var: Cannot parse value for variable ("[terratest_eth0_security_group, terratest_eth1_security_group]") as valid HCL: At 1:6: unexpected token while parsing list: IDENT

**Comment by yorinasub17** [comment]
Hey @tonerdo , it looks like this is a regression from the tf12 update. Do you know if the list and map inputs work on tf12?

**Comment by tonerdo** [comment]
@yorinasub17 will test this out with T12 and see if I need to do a sorta version check before passing variables

**Comment by yorinasub17** [comment]
Fixed in release https://github.com/gruntwork-io/terratest/releases/tag/v0.15.8
