### ISSUE TITLE
Question: How do I add a terratest module for alicloud resurces used in terraform

### ISSUE THREAD

**Issue by kamalika-majumder** [gruntwork-io/terratest#296]
Hello,
I would like to use terratest to test my terraform alicloud resources and modules. Can you provide some pointers on how to add it.

**Comment by robmorgan** [comment]
Hi @kamalika-majumder, thanks for offering to help. The best example I can give you is probably the pull request I made when I added Google Cloud support. You could use this as an example to start writing the `alicloud` module: https://github.com/gruntwork-io/terratest/pull/141

**Comment by kamalika-majumder** [comment]
Awesome !!! Thanks a lot for sharing Rob.

This is very helpful.

Regards
Kamalika

**Comment by robmorgan** [comment]
NP, I'll close for now.
