### ISSUE TITLE
AWS: GetEc2InstanceIdsByTag includes terminated EC2 instances to output

### ISSUE THREAD

**Issue by klebediev** [gruntwork-io/terratest#301]
No filtering criteria based on instance state, so terminated instances also included:
https://github.com/gruntwork-io/terratest/blob/c02722cd1f957a7c7c180d32d1962aeb0e7f9308/modules/aws/ec2.go#L183-L188
I think, this behavior is not expected, right?

A straightforward solution could something like:
```go
	// exclude EC2 instances in state "terminated"
	instanceStateFilter := &ec2.Filter{
		Name: aws.String("instance-state-name"),
		Values: []*string{aws.String("pending"),
			aws.String("running"),
			aws.String("shutting-down"),
			aws.String("stopping"),
			aws.String("stopped"),
		},
	}

	output, err := client.DescribeInstances(&ec2.DescribeInstancesInput{Filters: []*ec2.Filter{instanceStateFilter, tagFilter}})
```

**Comment by yorinasub17** [comment]
I am not too sure if we want to hard code a filter like that. E.g what if we want to look for tagged instances that were terminated recently? Or what if we want to also exclude stopped instances?

I think another, more flexible approach would be to extend our API to take a variadic argument which is a `map[string][]*string`, which you can use to extend the filter. Each entry in the map is a pair of `Name` (keys) and `Values` to pass into the filter. This way, you have more control over if you which instances you want to look at (e.g if you also want to ignore `stopped` instances), and can compose filters.

Alternatively, we could rework our APIs to be more centered on constructing the filters, as opposed to directly retrieving the instances. E.g:

```
filters := ec2.Filter{}
ExtendFilterWithTagsLookup(&filters, tagName, tagValue)
ExtendFilterWithInstanceStateLookup(&filters, "running", "shutting-down", "stopping")
instanceIds := GetEc2InstanceIdsByFilters(t, region, filters)
```

The benefit of the second approach is that you can compose additional tag lookups.

What do others on the team think? @Etiene  @brikis98 @robmorgan

**Comment by robmorgan** [comment]
I vote for not hardcoding filters directly in the method and instead passing in a `map` of args. I also find the EC2 filtering a bit verbose so it might be nice to layer a simple API on top like the one you proposed @yorinasub17.

**Comment by klebediev** [comment]
Yes, I implied this, but didn't write it: hardcoding is a bad idea.
Personally, I like the idea or reworking API by adding `GetEc2InstanceIdsByFilters` which will add a level of flexibility to the API / ability for users to set some custom filtering criteria.

Also, we could used a generalized `ExtendFilters` function which takes `Name` and a list of `Values` and and adds them into existing filters list.

And the rest of `GetEc2..By..` could be wrappers around `GetEc2InstanceIdsByFilters` with some presets.

**Comment by yorinasub17** [comment]
> And the rest of GetEc2..By.. could be wrappers around GetEc2InstanceIdsByFilters with some presets.

That's a great idea! Would you be up for a PR implementing this approach?

**Comment by klebediev** [comment]
> Would you be up for a PR implementing this approach?
yes, just need to find some free time for this :)

**Comment by klebediev** [comment]
Required functionality implemented, closing the issue.
Thank you for collaboration @yorinasub17 and @robmorgan
