### ISSUE TITLE
[aws] Support for different authentication methods 

### ISSUE THREAD

**Issue by klebediev** [gruntwork-io/terratest#312]
Hi!

I can see `NewAuthenticatedSessionFromRole` function implemented in [modules/aws/auth.go](https://github.com/gruntwork-io/terratest/blob/master/modules/aws/auth.go), which handles authentication usung sts assume role method, but `NewAuthenticatedSession` is used for authentication in the rest of `modules/aws/*.go` 

In my environment using assume role method is a preferred way to authenticate. 
Are there plans to do this or how could we add support for different authentication methods in aws-related functionality?  

[Thinking of something like adding `*session.Session` as an "optional" parameter for aws functions (via variadic args, for example) and if not set, then create a session using  `NewAuthenticatedSession()` inside the function]

Sample function signature:
```go
func GetPrivateIpOfEc2Instance(t *testing.T, instanceID string, awsRegion string, sess ...*session.Session) string {
...
}
```

**Comment by yorinasub17** [comment]
We generally recommend setting up the authentication outside of terratest, before executing the `go test` call. For example if you were using `aws-vault`, you can do:

```
aws-vault exec sandbox -- go test -timeout 60m .
```

The main reason for this is that it is one less thing to manage in your test, while leveraging the plethora of tools out there for AWS CLI authentication.

**Comment by klebediev** [comment]
thanks for quick reply @yorinasub17!
My point is that Terraform AWS Provider gives us [a number of options for AWS auth](https://www.terraform.io/docs/providers/aws/index.html), what means that people will use them.
So, as for me, it would be reasonable if testing framework supported the same options directly

**Comment by yorinasub17** [comment]
Fair point.

However, requiring the session to be passed in to all the aws functions is a major backwards incompatible change that adds extra calls to all test code. Can you come up with a different design that doesn't require passing through the session?

**Comment by klebediev** [comment]
Yes, understand your concerns. 
Although, the solution above with passing session via variadic argument `...*session.Session` doesn't isn't backwards incompatible, such notion of optional parameters isn't supported by the philosophy of Golang. Plus such API isn't clear as for me..

Currently, `NewAuthenticatedSession(region)` is used everywhere in `aws` module. 
```
account.go:	sess, err := NewAuthenticatedSession(region)
acm.go:	sess, err := NewAuthenticatedSession(awsRegion)
asg.go:	sess, err := NewAuthenticatedSession(region)
cloudwatch.go:	sess, err := NewAuthenticatedSession(region)
ec2.go:	sess, err := NewAuthenticatedSession(region)
ecs.go:	sess, err := NewAuthenticatedSession(region)
iam.go:	sess, err := NewAuthenticatedSession(region)
kms.go:	sess, err := NewAuthenticatedSession(region)
rds.go:	sess, err := NewAuthenticatedSession(region)
s3.go:	sess, err := NewAuthenticatedSession(region)
s3.go:	sess, err := NewAuthenticatedSession(region)
sns.go:	sess, err := NewAuthenticatedSession(region)
sqs.go:	sess, err := NewAuthenticatedSession(region)
ssm.go:	sess, err := NewAuthenticatedSession(region)
```
So, looks like behavior of `NewAuthenticatedSession(region)` itself might be changed. 
For example, on startup it may be checking for a number of environment variables, something like `TT_AWS_ASSUME_ROLE_ARN` etc.
Can't say it's a very nice solution though..

Another idea, maybe these advanced auth methods maybe configured somehow (don't know how at this point..) in `init()` fucntion of `aws` package

Any better ideas?

**Comment by yorinasub17** [comment]
> passing session via variadic argument ...*session.Session doesn't isn't backwards incompatible

Using variadic parameters for this purpose prevents us from defining functions that can use that for other purposes.

> Any better ideas?

Personally, in this particular case, I think environment variables are the way to go. We need to make a tradeoff between backwards compatibility and "elegant design." I think it is important to keep the maintainence / upgrade burden a minimum for a test tool like this, so I am leaning towards taking a compromise solution that allows the new feature in a way that is tolerable, but still maintains the old interface.

As far as naming of the IAM role var goes, I think it should be called `TERRATEST_IAM_ROLE`, to [mimic terragrunt](https://github.com/gruntwork-io/terragrunt#configuring-terragrunt-to-assume-an-iam-role).

**Comment by yorinasub17** [comment]
Released in https://github.com/gruntwork-io/terratest/releases/tag/v0.16.1

**Comment by klebediev** [comment]
Thank you @yorinasub17 !
