### ISSUE TITLE
(Question) Can we specify backend=false

### ISSUE THREAD

**Issue by neilpeterson** [gruntwork-io/terratest#318]
I see options for passing backend configuration to terraform init.

```
BackendConfig            map[string]interface{} // The vars to pass to the terraform init command for extra configuration for the backend
```

However, cannot figure out how to suppress backend configuration. This would be equivalent to `terraform init -backend=false`.

Thanks

**Comment by brikis98** [comment]
The `-backend` param is not currently exposed in `terraform.Options`. PR to add it is welcome!

**Comment by vivekab** [comment]
Is this issue resolved?

**Comment by dnitsch** [comment]
> The `-backend` param is not currently exposed in `terraform.Options`. PR to add it is welcome!

@brikis98  - I need this too - submitting a PR in the next 10mins. 

Also to avoid any future holdups like this we should extend the options with an arbitrary flags that get appended to the TF commands.
