### ISSUE TITLE
[terraform] Different signatures for InitAndApply/Destroy and InitAndPlan

### ISSUE THREAD

**Issue by klebediev** [gruntwork-io/terratest#319]
Hi!
`InitAndApply` and `Destroy` functions (and all the functions related to them) have the same signatures:
```go
// InitAndApply runs terraform init and apply with the given options and return stdout/stderr from the apply command.
func InitAndApply(t *testing.T, options *Options) string {}

// Destroy runs terraform destroy with the given options and return stdout/stderr.
func Destroy(t *testing.T, options *Options) string {}
```
But the signature of`InitAndPlan` is different, and doesn't correspond to what is stated in its `godoc` (it returns retcode instead of stdout/stderr):
```go
// InitAndPlan runs terraform init and plan with the given options and return stdout/stderr from the apply command.
func InitAndPlan(t *testing.T, options *Options) int {}
```

I need stdout/stderr from `InitAndPlan` (or some `.*Plan.*`) in order to implement `GetResourceCount` as a part on #236 func for `apply`, `plan`, `destroy` commands, but not able to do this because of this inconsistency

**Comment by yorinasub17** [comment]
Hi @klebediev,

You are right! In this case, even though it is backwards incompatible, I'd be ok with updating `InitAndPlan` to return stdout/stderr so it is consistent with the others, and rename the existing ones to `InitAndPlanWithExitCode` as a clear migration path.

**Comment by klebediev** [comment]
Hi @yorinasub17 !
I like this idea, let me find some free time for this and I'll submit PR
