### ISSUE TITLE
Support for helm upgrade and rollback operations

### ISSUE THREAD

**Issue by Saurabh-16** [gruntwork-io/terratest#334]
For the helm module , https://github.com/gruntwork-io/terratest/tree/master/modules/helm
Can we have support for helm upgrade and rollback operations also.
Currently I see support for install and delete only.

**Comment by yorinasub17** [comment]
That's a good idea to add! We are pretty buried at the moment so won't get to this in the short term, but any PRs if people are willing and able are welcome!

**Comment by Saurabh-16** [comment]
I will try to put up a PR after few rounds of local testing.

**Comment by yorinasub17** [comment]
This was released in https://github.com/gruntwork-io/terratest/releases/tag/v0.17.6
