### ISSUE TITLE
how can I pass provider to terraformOptions 

### ISSUE THREAD

**Issue by odedpriva** [gruntwork-io/terratest#337]
Hi, 

I want my module to be able to work with different provider setups

Is there a way to pass provider explicitly terraformOptions ? 

```
provider "aws" {
  region = "us-west-1"
}

# A non-default, or "aliased" configuration is also defined for a different
# region.
provider "aws" {
  alias  = "usw2"
  region = "us-west-2"
}

# An example child module is instantiated with the _aliased_ configuration,
# so any AWS resources it defines will use the us-west-2 region.
module "example" {
  source    = "./example"
  providers = {
    aws = "aws.usw2"
  }
}
```

https://www.terraform.io/docs/configuration/modules.html#passing-providers-explicitly

**Comment by yorinasub17** [comment]
AFAIK, there isn't a way to set up the provider through command line options.

What I would suggest here is to setup wrapper modules that call out to the underlying module with different provider options, and target your tests against those wrappers. For example, suppose you had a module `server` and you wanted to test it against the regions `us-east-1` and `us-west-1`. You could define two different modules, `server-us-east-1` and `server-us-west-1` that has the code:

```
# server-us-east-1/main.tf

provider "aws" {
  region = "us-east-1"
}

module "server" {
  source = "../server"
}
```

```
# server-us-west-1

provider "aws" {
  region = "us-west-1"
}

module "server" {
  source = "../server"
}
```

You would then write your tests to target `server-us-east-1` and `server-us-west-1`.

Note that this pattern is generally useful for modules that have dependencies. For example, if your module depended on a VPC being passed in, your wrapper module can define the VPC resource and pass in to the module call.

We use this pattern a lot at Gruntwork. All our modules are divided into `examples` and `modules`. The `examples` are self contained deployable modules that define all the dependencies for consuming the modules in the `modules` folder, and we write our tests against the `examples`. See our [terraform-aws-couchbase module for example](https://github.com/gruntwork-io/terraform-aws-couchbase).

**Comment by jghal** [comment]
I ran into this issue while trying to get rid of our "test" Terraform code and move all that configuration into the Terratest code, since all the TF code in the test folder was very redundant with the main module code. What I settled on was to put a _provider.tf_ file in the test directory with my Terratest code, and then I copy it to the Terraform config directory (and set .gitignore to ignore the destination path) with a deferred delete

```go
package test

import (
    "testing"
    "os"
    "github.com/gruntwork-io/terratest/modules/files"
    "github.com/gruntwork-io/terratest/modules/ssh"
    "github.com/gruntwork-io/terratest/modules/terraform"
    "github.com/stretchr/testify/assert"
)

func TestAz(t *testing.T) {
    t.Parallel()

    // Installl the provider.tf with defered deletion
    defer os.Remove("../test-provider.tf")
    files.CopyFile("provider.tf", "../test-provider.tf")

    // Configure Terraform setting up a path to Terraform code.
    terraformOptions := &terraform.Options{
        // The path to where our Terraform code is located
        TerraformDir: "..",

        Vars: map[string]interface{}{
            ...
        }
    }

    // At the end of the test, run `terraform destroy` to clean up any resources that were created
    defer terraform.Destroy(t, terraformOptions)

    // Run `terraform init` and `terraform apply`. Fail the test if there are any errors.
    terraform.InitAndApply(t, terraformOptions)

    // Test outputs and resources
    ...
}
```
