### ISSUE TITLE
Wrong log message for GCP zonal instance groups

### ISSUE THREAD

**Issue by Etiene** [gruntwork-io/terratest#338]
This confused the hell out of me when working on a nomad module that was still using zonal instance groups. 

The method `getRandomInstanceE` can be called by both types of instance groups (Regional and Zonal) but the log has a hardcoded mention to Regional 

* https://github.com/gruntwork-io/terratest/blob/71a1fe923037323023f8b59368eca5a3bb3423d1/modules/gcp/compute.go#L560

* https://github.com/gruntwork-io/terratest/blob/71a1fe923037323023f8b59368eca5a3bb3423d1/modules/gcp/compute.go#L565

**Comment by j4ng5y** [comment]
I have a PR ready for this, but I need to clean up my local repo before I issue it :smile:

**Comment by robmorgan** [comment]
@j4ng5y sure 👍
