### ISSUE TITLE
SSHing with username and password - unclear as to how/if possible

### ISSUE THREAD

**Issue by jlucktay** [gruntwork-io/terratest#339]
I'm trying to set up a test around a Terraform module which handles Linux VMs.
Public/private keys aren't in use by this client; they join Linux machines to domains and run auth that way, so the module doesn't have key functionality written into it.

From looking at the [Terratest module](https://godoc.org/github.com/gruntwork-io/terratest/modules/ssh) and [x/crypto/ssh](https://godoc.org/golang.org/x/crypto/ssh) godocs on SSH, I can see there is a [Password AuthMethod](https://godoc.org/golang.org/x/crypto/ssh#Password) but it's not clear to me if this can be leveraged by Terratest.

I'd also like to say thanks very much for the Terratest package as a whole, it's a valuable part of our pipeline!

**Comment by yorinasub17** [comment]
Unfortunately we don't currently support this, but it should be fairly straightforward to add if you are open to create a PR. The idea would be to add the password to the host options (https://github.com/gruntwork-io/terratest/blob/master/modules/ssh/ssh.go#L24), and then to update [createAuthMethodsForHost](https://github.com/gruntwork-io/terratest/blob/master/modules/ssh/ssh.go#L517) to add the PasswordAuthMethod if that var is set.

**Comment by jlucktay** [comment]
OK, thank you for the directions! I'll see what I can come up with for a PR.
