### ISSUE TITLE
Change from dep to Go mod

### ISSUE THREAD

**Issue by BrendanThompson** [gruntwork-io/terratest#345]
As the standard for Go dependency management has moved to `go mod` `terratest` should also pivot to this. Further, this will remove the requirement to have the TF files in the `$GOPATH`.

**Comment by brikis98** [comment]
We plan to do this once Go 1.13 is out.

**Comment by clvx** [comment]
This is discussed in #264.

**Comment by yorinasub17** [comment]
This is done in https://github.com/gruntwork-io/terratest/releases/tag/v0.21.0
