### ISSUE TITLE
error while executing .go file. "use of internal package not allowed"

### ISSUE THREAD

**Issue by vermaaakansha** [gruntwork-io/terratest#349]
[main.go.txt](https://github.com/gruntwork-io/terratest/files/3485280/main.go.txt)

Go is a new language for me , plus I'm a core infra person and not a developer. due to some project requirement I'm trying to learn it at least for the required purpose. 
Attaching a small Go program which will list all the Storage account from my azure resource group in a subscription. I have already installed all the packages required to execute this program but while executing, I'm getting below error.  Even after searching a lot on internet, I'm not getting what the issue is. 

![image](https://user-images.githubusercontent.com/50359777/62763698-d35f7a80-baa9-11e9-9ad3-f6b7610ef9d7.png)

I request you to please help me on this and guide me if I'm doing something wrong. Thank you so much. 🙂

**Comment by brikis98** [comment]
See the section on "internal packages" in https://blog.learngoprogramming.com/special-packages-and-directories-in-go-1d6295690a6b
