### ISSUE TITLE
Question: Test output to JUnit

### ISSUE THREAD

**Issue by BrendanThompson** [gruntwork-io/terratest#350]
Would be great to see an example or some documentation on how to get the interleaved output to work, keen to get JUnit report go into my CI system and at this stage can't quite work it out.

**Comment by yorinasub17** [comment]
You can use the `terratest_log_parser` for this, which outputs the Junit report. See [Debugging interleaved test output](https://github.com/gruntwork-io/terratest#debugging-interleaved-test-output) in the README for more details.

**Comment by yorinasub17** [comment]
Here is an example from our circleCI script of terratest using it: https://github.com/gruntwork-io/terratest/blob/master/.circleci/config.yml#L151. Note how we pipe the test output to a file first: https://github.com/gruntwork-io/terratest/blob/master/.circleci/config.yml#L149

**Comment by BrendanThompson** [comment]
Thanks @yorinasub17
