### ISSUE TITLE
[Help] Helper func. for verifying if (AWS) subnet is private?

### ISSUE THREAD

**Issue by kasia-kittel** [gruntwork-io/terratest#361]
Would that make sense to have a helper function for verifying if the subnetwork is private/public? 
My use case is as follows: I have a networking module that outputs IDs of subnetworks: `private-subnet-id` and `public-subnet-id`. The public subnet has a route to IGW in its routing table, the private doesn't

I want to avoid errors like:
```
output "private-subnet-id" {
  value = aws_subnet.public.id
  description = "The private subnet id"
}
```

I want my test to verify if I can trust that private subnet is indeed private.
It could look like this:
```golang
func VerifyContainPublicRoute(routes []Route, igwId string) bool {
	found := false

	for _, r := range routes {
		if (r.DestinationCidrBlock == "0.0.0.0/0" && r.GatewayId == igwId && r.State == "active"){
			found = true
		}
	}

	return found
}
```

Is this a valid use case for the terratest?

**Comment by yorinasub17** [comment]
Yup that seems like a good idea, although IIRC, all you need is a route to an Internet Gateway for a subnet to be public.

It would be nice if the interface was much simpler though. I think the type signature want is `IsPublic(subnetID string) bool`. What you have now requires:

- Getting the route table
- Getting Internet gateways
- Iterating cross product of routes and internet gateway

which seems cumbersome.

**Comment by yorinasub17** [comment]
This was addressed in https://github.com/gruntwork-io/terratest/releases/tag/v0.19.3
