### ISSUE TITLE
http_helper with retries have empty body after first request

### ISSUE THREAD

**Issue by jendrikjoe** [gruntwork-io/terratest#364]
The way http_helper is implement, it is using io.Reader for all functions, even the retry ones.
If the retry is actually triggered, the body of the request is empty from the second request onwards as the reader is empty. 
I missed that case when opening #355. I will take care of implementing the retry functions such that they take `[]byte` as arguments and writing a test that is making sure this doesn't happen again :slightly_smiling_face:

**Comment by yorinasub17** [comment]
Fixed in https://github.com/gruntwork-io/terratest/releases/tag/v0.19.0
