### ISSUE TITLE
Terratest for EKS Cluster in AWS

### ISSUE THREAD

**Issue by ashyankee** [gruntwork-io/terratest#374]
My team has created a terraform resource file to create an EKS cluster. I’m looking for examples and I found one where a kubernetes cluster is created with kubectl. This setup does not work for me. I need to access this eks cluster through terratest and verify things like name, tags, subnet ids.. things like that.. Looking at Terratest’s aws package I don’t see a getekscluster method. Is this possible with terratest at all? Or am i looking at it the wrong way?

**Comment by yorinasub17** [comment]
We usually recommend using the AWS SDK Go library directly for making checks on the EKS cluster itself. We do have a lot of functions that wrap those into a better interface, but if we wrapped every function of the SDK, it would be redundant and not very maintainable.

So we typically only expose functions of routines that we find are especially hard or unintuitive to do directly with the SDK. Given that, we've found that the EKS resource is actually simple to use, so we didn't find the need to wrap it.

With that said, if you find that it would be useful for terratest to wrap it, it would help if you could share:

- Use case: what is the property that you want to verify on the EKS cluster?
- Challenges with the SDK: what makes it hard to use the AWS SDK directly to verify the EKS cluster?
- Ideal interface: What is the ideal interface for accessing EKS clusters through terratest?

This would help us decide if it is worth maintaining a separate terratest interface for accessing the EKS cluster.
