### ISSUE TITLE
Invalid region name "southfricawest" in Azure module

### ISSUE THREAD

**Issue by MathieuBuisson** [gruntwork-io/terratest#375]
Hi,

There is what looks like a typo here :  
https://github.com/gruntwork-io/terratest/blob/dc53986f3d6e3b87089dd88c0aaca851af7dac09/modules/azure/region.go#L58

This may result in errors like the following when we use `azure.GetRandomStableRegion()` in our tests :  

> Operation to create resource group terratest-example-rg failed. Details : {“error”:{“code”:”LocationNotAvailableForResourceGroup”,”message”:”The provided location ‘southfricawest’ is not available for resource group. ...

The valid name for the region **South Africa West** is : `southafricawest`.

I'd be happy to submit a PR to fix this issue.

**Comment by brikis98** [comment]
Good catch! A PR to fix this is very welcome!

**Comment by MathieuBuisson** [comment]
@brikis98 Great, I will submit a PR for this fix.

**Comment by MathieuBuisson** [comment]
Given that the PR fixing this issue has been merged, I suppose we can close it.

**Comment by robmorgan** [comment]
@MathieuBuisson thanks 👍
