### ISSUE TITLE
How to use CleanupTestData to cleanup

### ISSUE THREAD

**Issue by njunxuan** [gruntwork-io/terratest#383]
Hi,

I am using `test_structure` and the `Save*Option` functions to manage my terraform and k8 options. At the end of the test, I want to delete the `.test-data` directory. I have tried something along the lines of:
`test_structure.CleanupTestData(workingDir)`, where `workingDir` is the path I passed to the `Save` functions.

However, I get errors about how the directory is not empty, which seems odd to me as I thought the purpose of the function is to clean up the directory. How should I go about using the CleanupTestData function?

Thanks.

**Comment by brikis98** [comment]
Ah, I can see the confusion. The `CleanupTestData` takes a file path as an argument and expects to delete a single file, not a folder. E.g., if you created `.test-data/data.json`, it expects to delete `.test-data/data.json`, but not `.test-data`. 

Perhaps we should add a `CleanupTestDataFolder` method specifically to handle your use case?

**Comment by njunxuan** [comment]
I see. So I would have to explicitly pass the `.test-data` folder created by terratest to the function. I would personally like (and happy to contribute) a function that takes the `workingDir` that the user passed to the `Save` functions, and deletes the `.test-data` inside it (and optionally also the provided `workingDir` folder itself).

My use case is roughly that I have multiple tests running in parallel and each test uses a different `workingDir` based on a randomly generated id. After a test is complete, it would teardown both the `workingDir` and `.test-data` in it.

I am happy to write the code if such a function is inline with the project's goals 😃

**Comment by brikis98** [comment]
A PR  to add `CleanupTestDataFolder` is very welcome, thanks!
