### ISSUE TITLE
error when running remote apply "Error: error retrieving queue: resource not found"

### ISSUE THREAD

**Issue by Enjolras67** [gruntwork-io/terratest#387]
I'm using terratest to run tests remotely on terraform enterprise. I ran into "Error: error retrieving queue: resource not found" periodically, when executing the following code. 
`terraform.InitAndApply(t, terraformBootstartOptions)
`
Error message:
<img width="1219" alt="Screen Shot 2019-10-04 at 5 18 07 PM" src="https://user-images.githubusercontent.com/44093010/66241000-013cf600-e6cc-11e9-8e97-531d82685f7e.png">

Actually, the plan was queued successfully in terraform enterprise
<img width="1318" alt="Screen Shot 2019-10-04 at 4 36 16 PM" src="https://user-images.githubusercontent.com/44093010/66240624-2aa95200-e6cb-11e9-9774-53072c4d5611.png">

**Comment by brikis98** [comment]
As best as I can tell, this is a Terraform Enterprise error. Perhaps contact HashiCorp support for more info on what the error means?
