### ISSUE TITLE
Resource might not cleaned up during parallel testing

### ISSUE THREAD

**Issue by pjuanda** [gruntwork-io/terratest#394]
Here is my test file called `bucket_versioning_test.go`

```
package test

import (
	"fmt"
	"strings"
	"testing"

	"github.com/gruntwork-io/terratest/modules/aws"
	"github.com/gruntwork-io/terratest/modules/random"
	"github.com/gruntwork-io/terratest/modules/terraform"
	"github.com/stretchr/testify/assert"
)

func TestEnableBucketVersioning(t *testing.T) {
	t.Parallel()

	bucket := fmt.Sprintf("testing-enable-versioning-%s", strings.ToLower(random.UniqueId()))
	options := &terraform.Options{
		TerraformDir: "./../",
		Vars: map[string]interface{}{
			"name":              bucket,
			"enable_versioning": "true",
		},
	}

	terraform.InitAndApply(t, options)
	defer terraform.Destroy(t, options)

	aws.AssertS3BucketExists(t, "ap-southeast-1", bucket)
	aws.AssertS3BucketVersioningExists(t, "ap-southeast-1", bucket)
}

func TestDisableBucketVersioning(t *testing.T) {
	t.Parallel()

	bucket := fmt.Sprintf("testing-disable-versioning-%s", strings.ToLower(random.UniqueId()))
	options := &terraform.Options{
		TerraformDir: "./../",
		Vars: map[string]interface{}{
			"name":              bucket,
			"enable_versioning": "false",
		},
	}

	terraform.InitAndApply(t, options)
	defer terraform.Destroy(t, options)

	aws.AssertS3BucketExists(t, "ap-southeast-1", bucket)

	err := aws.AssertS3BucketVersioningExistsE(t, "ap-southeast-1", bucket)
	if assert.Error(t, err) {
		assert.Equal(t, aws.NewBucketVersioningNotEnabledError(bucket, "ap-southeast-1", "Suspended"), err)
	}
}
```

Issue:
- When running the test with `parallel` enabled, the bucket "sometime" not get destroyed even though we have called `defer terraform.Destroy()`.

Question:
- Has anybody face the same issue ? 
- Is it possible due to both of them sharing the same statefile and they're facing race condition when `terraform.Destroy()` being called ?

**Comment by yorinasub17** [comment]
> Is it possible due to both of them sharing the same statefile and they're facing race condition when terraform.Destroy() being called ?

This is actually the reason. When you run multiple tests against a common terraform module in parallel, you will run into many issues due to state file collision. To avoid this, you want to use [CopyTerraformFolderToTemp in test-structure](https://github.com/gruntwork-io/terratest/blob/master/modules/test-structure/test_structure.go#L42) to set up a temp directory with your terraform code.

**Comment by pjuanda** [comment]
Noted. I'll take a look into the `CopyTerraformFolderToTemp`. Thanks
