### ISSUE TITLE
Add support to run remote commands using an SSM agent

### ISSUE THREAD

**Issue by remilapeyre** [gruntwork-io/terratest#400]
We are using AWS SSM to connect to our instances and disable SSH so it would be great to have some equivalent of `ssh.CheckSshCommand()` and others that uses SSM so that we can test them.

I will start writing those if I can find the time for that.

**Comment by yorinasub17** [comment]
As Terratest has grown, we've had to think more about what types of helper functions we want in the library to make sure it doesn't become so big as to be unusable. Please check out the updated contribution guidelines, especially the part about [infrastructure and validation helpers](https://github.com/gruntwork-io/terratest/blob/master/CONTRIBUTING.md#types-of-contributions).

Specifically, to decide if we want to add something like this to terratest, we need to pass four tests:

- [Platforms] Is the function for one of the supported platforms?
- [Creating infrastructure] Is the function validating infrastructure (as opposed to creating or modifying)?
- [Complexity] Is the function complex to implement directly with the existing APIs?
- [Popularity] Is the function a popular use case?

I think this passes the litmus test for "platforms", "creating infrastructure", and "popularity", but what about "complexity"? What is it about the current SSM APIs that make it difficult to implement this directly using the existing terratest + AWS SDK APIs?

**Comment by remilapeyre** [comment]
Hi @yorinasub17, the SSM API to create an SSM session gives you an URL to a websocket that you can use to send commands or get results (https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_StartSession.html#API_StartSession_ResponseElements).

How to interact with this websocket is not documented and I could not find helper functions in the Go SDK. It may be easy but I did not have time to try to do it yet, I will and come back with the results.

There is a way to get an SSH connection through AWS SSM (https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager-getting-started-enable-ssh-connections.html) but this requires to have a running SSH daemon and credentials set and we disable the daemon on our infrastructure. We could keep it for the tests and remove it later but we would like to avoid testing one AMI and deploying another.

**Comment by remilapeyre** [comment]
Hi @yorinasub17, I spend some time to implement a working solution:

```go
package test

import (
	"context"
	"encoding/json"
	"fmt"
	"regexp"
	"testing"
	"time"

	"github.com/gruntwork-io/terratest/modules/logger"
	"github.com/gruntwork-io/terratest/modules/retry"
	"github.com/gruntwork-io/terratest/modules/terraform"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/aws/external"
	"github.com/aws/aws-sdk-go-v2/service/ssm"
)

func TestECS(t *testing.T) {
	awsRegion := "eu-central-1"
	amiID := "ami-0dfb91c22210e3d95"

	terraformOptions := &terraform.Options{
		TerraformDir: "../example",
		Vars: map[string]interface{}{
			"ami": amiID,
		},
	}

	// At the end of the test, run `terraform destroy` to clean up any resources that were created
	defer terraform.Destroy(t, terraformOptions)

	// This will run `terraform init` and `terraform apply` and fail the test if there are any errors
	terraform.InitAndApply(t, terraformOptions)

	instanceID := terraform.Output(t, terraformOptions, "instance_id")

	config, err := external.LoadDefaultAWSConfig()
	if err != nil {
		t.Fatalf("failed to load AWS config: %v", err)
	}
	config.Region = awsRegion

	// Check the instance is working correctly
	stdout, _ := checkSsmCommand(t, config, instanceID, "echo hello world")
	logger.Logf(t, "Result of the command: '%s'", stdout)

	stdout, stderr, err := checkSsmCommandE(t, config, instanceID, "this_command_does_not_exists")
	if err == nil || err.Error() != "Failed" {
		t.Fatalf("got wrong error: %v", err)
	}
	expected := ""
	if stdout != expected {
		t.Fatalf("was expecting '%s' but got '%s'", expected, stdout)
	}
	expected = `this_command_does_not_exists: command not found
failed to run commands: exit status 127`
	if stderr != expected {
		t.Fatalf("was expecting '%s' but got %#v", expected, stderr)
	}
}

type result struct {
	Stdout string
	Stderr string
}

func checkSsmCommand(t *testing.T, config aws.Config, instanceID string, command string) (string, string) {
	stdout, stderr, err := checkSsmCommandE(t, config, instanceID, command)
	if err != nil {
		t.Fatal(err)
	}
	return stdout, stderr
}

func checkSsmCommandE(t *testing.T, config aws.Config, instanceID string, command string) (string, string, error) {
	// TODO: Make this a parameter
	maxRetries := 30
	timeBetweenRetries := 2 * time.Second
	description := fmt.Sprintf("Waiting for %s to appear in the SSM inventory", instanceID)

	// We must first wait for the instance to appear in the AWS SSM inventory
	retry.DoWithRetry(t, description, maxRetries, timeBetweenRetries, func() (string, error) {
		client := ssm.New(config)
		key := "AWS:InstanceInformation.InstanceId"
		req := client.GetInventoryRequest(&ssm.GetInventoryInput{
			Filters: []ssm.InventoryFilter{
				{
					Key:    &key,
					Type:   "Equal",
					Values: []string{instanceID},
				},
			},
		})
		resp, err := req.Send(context.TODO())
		if err != nil {
			return "", nil
		}

		if len(resp.Entities) != 1 {
			return "", fmt.Errorf("%s is not in the SSM inventory", instanceID)
		}

		return "", err
	})

	// Now that we know the instance in the SSM inventory, we can send the command
	client := ssm.New(config)
	comment := "Terratest SSM"
	documentName := "AWS-RunShellScript"
	req := client.SendCommandRequest(&ssm.SendCommandInput{
		Comment:      &comment,
		DocumentName: &documentName,
		InstanceIds:  []string{instanceID},
		Parameters: map[string][]string{
			"commands": []string{command},
		},
	})
	resp, err := req.Send(context.TODO())
	if err != nil {
		return "", "", err
	}

	// Wait for the result
	description = "Waiting for the result of the command"
	retryableErrors := map[string]string{
		"InvocationDoesNotExist": "InvocationDoesNotExist",
		"bad status: Pending":    "bad status: Pending",
		"bad status: InProgress": "bad status: InProgress",
		"bad status: Delayed":    "bad status: Delayed",
	}
	out, err := retry.DoWithRetryableErrorsE(t, description, retryableErrors, maxRetries, timeBetweenRetries, func() (string, error) {
		client := ssm.New(config)
		req := client.GetCommandInvocationRequest(&ssm.GetCommandInvocationInput{
			CommandId:  resp.Command.CommandId,
			InstanceId: &instanceID,
		})
		resp, err := req.Send(context.TODO())
		if err != nil {
			return "", err
		}

		// Remove the SSM prefix from stderr
		stdErr := *resp.StandardErrorContent
		prefix := regexp.MustCompile(`/var/lib/amazon/ssm/.*/_script\.sh: line 1: `)
		stdErr = prefix.ReplaceAllString(stdErr, "")

		b, err := json.Marshal(result{
			Stdout: *resp.StandardOutputContent,
			Stderr: stdErr,
		})
		if err != nil {
			return "", err
		}

		if resp.Status == "Success" {
			return string(b), nil
		}

		if resp.Status == "Failed" {
			return string(b), fmt.Errorf("Failed")
		}

		return "", fmt.Errorf("bad status: %s", resp.Status)
	})
	var r result
	unmarshallErr := json.Unmarshal([]byte(out), &r)
	if unmarshallErr != nil {
		return "", "", unmarshallErr
	}

	if err != nil {
		return r.Stdout, r.Stderr, err.(retry.FatalError).Underlying
	}

	return r.Stdout, r.Stderr, nil
}
```

I must say that I haven't find it to be straightforward, let me know what you think.

**Comment by yorinasub17** [comment]
Yup that is definitely not straightforward at all. Thanks for sharing this! I have a few suggestions for improvements (e.g separating out the wait for SSM into its own function), but I am convinced that we should have a terratest module for this.

We are a bit buried to implement this anytime soon, but happy to review a PR with this change. I think we can get this merged if you (or whoever else is interested) can take what you have and:

- refactor out the pieces where it is waiting for the instance to be registered to SSM into a separate function
- use [NewSsmClient](https://github.com/gruntwork-io/terratest/blob/master/modules/aws/ssm.go#L56) so you don't need to pass in `aws.Config` and instead just the region
- add a top level terraform example and corresponding test that tests the functions

Thanks for the suggestion and working with me to provide the context!

**Comment by remilapeyre** [comment]
Ok, I will work on this as we improve tests on our infrastructure. I should have a PR ready in a few weeks, ping me if I forget.
