### ISSUE TITLE
helm/testing: helm 3 support

### ISSUE THREAD

**Issue by StupidScience** [gruntwork-io/terratest#403]
Hello.
Do you consider for helm3 support? If yes any ETA on this?

**Comment by yorinasub17** [comment]
We have not explored helm 3 yet, but we will get to it shortly after it is GA. A PR that explores this and starts to map out the work required would be greatly appreciated!

**Comment by StupidScience** [comment]
@yorinasub17 what is your thoughts about implementation? How to handle breaking changes?

**Comment by robmorgan** [comment]
Hi @StupidScience, just a heads up - @yorinasub17 is out on vacation for a few weeks, so I'm sure he'll respond here when he's back again.

**Comment by StupidScience** [comment]
No problem.
PS. Helm 3 is GA :)

**Comment by yorinasub17** [comment]
Apologies for the long delay in responding here!

> what is your thoughts about implementation? How to handle breaking changes?

I would start by looking into see how much the CLI args have changed. Based on a glance at the release notes, I don't think a lot has changed such that there are too many breaking changes in terratest.

For any incompatibilities, there should be a fork that uses different CLI args for similar purposes, similar to what we have for managing terraform outputs when tf12 rolled out (see [here](https://github.com/gruntwork-io/terratest/blob/master/modules/terraform/output.go#L73) for example). We will want to support Helm 2 for at least this year before completely dropping support, given that many tools are still catching up (the [terraform helm provider hasn't been updated yet](https://github.com/terraform-providers/terraform-provider-helm/pull/378) for example).

---

FWIW, we are planning to do a deep dive for updating everything in the Gruntwork stack to Helm 3 in the next two quarters.

**Comment by autero1** [comment]
One thing I noticed was that the `releaseName` introduced in https://github.com/gruntwork-io/terratest/releases/tag/v0.23.0 no longer works with Helm 3, as the release name is now mandatory as part of the command. Rendering templates gives `Error: unknown flag: --name`.

**Comment by autero1** [comment]
Another one: https://github.com/helm/helm/issues/5887
Support for partial template execution is removed.

**Comment by yorinasub17** [comment]
Thanks Petri! That is helpful for revamping terratest when we tackle this.

**Comment by mhuang0711** [comment]
Hi, we are using terratest as our helm chart integration test framework. We already migrated to helm 3, may I ask when will you release your GA with helm 3?

**Comment by robmorgan** [comment]
Hi @mhuang0711, thanks for your question. We are aware of a few backward incompatibilities broken with helm 3 and plan on updating terratest in the near future (within the next 3 months, likely sooner). In the meantime, you're more than welcome to contribute a pull request.

**Comment by yorinasub17** [comment]
PR for helm 3 support is here: https://github.com/gruntwork-io/terratest/pull/467

**Comment by robmorgan** [comment]
Cool! 🎉 cc @mhuang0711

**Comment by yorinasub17** [comment]
This is done as https://github.com/gruntwork-io/terratest/releases/tag/v0.25.0

**Comment by StupidScience** [comment]
Great news @yorinasub17 
Thank you
