### ISSUE TITLE
GetRandomStableRegion doesn't seem to set AWS_DEFAULT_REGION correctly

### ISSUE THREAD

**Issue by durangogt** [gruntwork-io/terratest#407]
I'm pretty new at using Terratest. I can hard code the ``` awsRegion := "us-east-1" ``` and all works but when using the random region, which I want to use, I get the resources created and destroyed consistently without error but then the assertions run and error out. It seems like the AWS_DEFAULT_REGION isn't being used. I'm using an AWS ECS Fargate container with an Admin IAM policy attached to its ECS_Task_Execution role to run these tests.. Has anyone seen this before?

Not sure if I need to pass in awsRegion specifically to the terratest calls like we do to the aws SDK calls.
```
TestTerraformAwsEcs1Example 2019-11-10T19:35:32Z command.go:158: aws_ecs_cluster.example: Destroying... [id=arn:aws:ecs:us-east-1:xxxx:cluster/terratest-aws-ecs-example-cluster-6BCIRm]
TestTerraformAwsEcs1Example 2019-11-10T19:35:32Z command.go:158: aws_ecs_task_definition.example: Destroying... [id=terratest]
TestTerraformAwsEcs1Example 2019-11-10T19:35:32Z command.go:158: aws_ecs_task_definition.example: Destruction complete after 0s
TestTerraformAwsEcs1Example 2019-11-10T19:35:32Z command.go:158: aws_iam_role.execution: Destroying... [id=terratest-aws-ecs-example-cluster-6BCIRm-ecs-execution]
TestTerraformAwsEcs1Example 2019-11-10T19:35:32Z command.go:158: aws_ecs_cluster.example: Destruction complete after 0s
TestTerraformAwsEcs1Example 2019-11-10T19:35:32Z command.go:158: aws_iam_role.execution: Destruction complete after 0s
TestTerraformAwsEcs1Example 2019-11-10T19:35:32Z command.go:158: 
TestTerraformAwsEcs1Example 2019-11-10T19:35:32Z command.go:158: Destroy complete! Resources: 5 destroyed.
--- FAIL: TestTerraformAwsEcs1Example (55.89s) 
ecs.go:15:  
Error Trace:	ecs.go:15 
terraform_aws_ecs_1_test.go:51 
Error: Received unexpected error: 
Expected to find 1 ECS cluster named 'terratest-aws-ecs-example-cluster-6BCIRm' in region 'eu-west-1', but found '0' 
Test: TestTerraformAwsEcs1Example 
FAIL 
FAIL	test	55.899s 
FAIL 
```
Here is my whole script - just using one of the Terratest simple examples for testing with a simple ECS Fargate cluster setup:
```
package test

import (
	"fmt"
	"testing"

	"github.com/gruntwork-io/terratest/modules/aws"
	"github.com/gruntwork-io/terratest/modules/random"
	"github.com/gruntwork-io/terratest/modules/terraform"

	awsSDK "github.com/aws/aws-sdk-go/aws"
	"github.com/stretchr/testify/assert"
)

// An example of how to test the Terraform module in examples/terraform-aws-ecs-example using Terratest.
func TestTerraformAwsEcs1Example(t *testing.T) {
	t.Parallel()

	expectedClusterName := fmt.Sprintf("terratest-aws-ecs-example-cluster-%s", random.UniqueId())
	expectedServiceName := fmt.Sprintf("terratest-aws-ecs-example-service-%s", random.UniqueId())

	// Pick a random AWS region to test in. This helps ensure your code works in all regions.
	// awsRegion := aws.GetRandomStableRegion(t, []string{"us-east-1", "eu-west-1"}, nil)
	awsRegion := "us-east-1"

	terraformOptions := &terraform.Options{
		// The path to where our Terraform code is located
		TerraformDir: "../examples/ecs_1",

		// Variables to pass to our Terraform code using -var options
		Vars: map[string]interface{}{
			"cluster_name": expectedClusterName,
			"service_name": expectedServiceName,
		},

		// Environment variables to set when running Terraform
		EnvVars: map[string]string{
			"AWS_DEFAULT_REGION": awsRegion,
		},
	}

	// At the end of the test, run `terraform destroy` to clean up any resources that were created
	defer terraform.Destroy(t, terraformOptions)

	// This will run `terraform init` and `terraform apply` and fail the test if there are any errors
	terraform.InitAndApply(t, terraformOptions)

	// Run `terraform output` to get the value of an output variable
	taskDefinition := terraform.Output(t, terraformOptions, "task_definition")

	// Look up the ECS cluster by name
	cluster := aws.GetEcsCluster(t, awsRegion, expectedClusterName)

	assert.Equal(t, int64(1), awsSDK.Int64Value(cluster.ActiveServicesCount))

	// Look up the ECS service by name
	service := aws.GetEcsService(t, awsRegion, expectedClusterName, expectedServiceName)

	assert.Equal(t, int64(0), awsSDK.Int64Value(service.DesiredCount))
	assert.Equal(t, "FARGATE", awsSDK.StringValue(service.LaunchType))

	// Look up the ECS task definition by ARN
	task := aws.GetEcsTaskDefinition(t, awsRegion, taskDefinition)

	assert.Equal(t, "256", awsSDK.StringValue(task.Cpu))
	assert.Equal(t, "512", awsSDK.StringValue(task.Memory))
	assert.Equal(t, "awsvpc", awsSDK.StringValue(task.NetworkMode))
}
```

**Comment by yorinasub17** [comment]
It's a bit hard to debug this without seeing your terraform code, but one thing about `AWS_DEFAULT_REGION` is that it has the lowest precedence. For example, if you have the region hardcoded in your terraform code, `AWS_DEFAULT_REGION` won't do anything.

**Comment by durangogt** [comment]
Thanks for the quick response. 

No problem - I understand, I do believe it's some kind of precedence issue but just not sure yet. I don't have region in my aws provider section & there is a REGION env variable but not AWS_DEFAULT_REGION. The terraform/terratest is on a Docker container on Linux via ECS Fargate w/ an IAM Role as credentials - where does that play in the precedence? I thought it took priority. I really believe this is where the problem is..but thought maybe there was another env var or something I need to pass in..

The Terraform state is basically the example w/ the provider aws in there because that is my workaround, that is hardcoding the region. Here it is:

```
provider "aws" {
  #region = "us-east-1"
  # assume_role {
  #   role_arn = "arn:aws:iam::xxxxxxx:role/cross_account_admin"
  # }
}

# ---------------------------------------------------------------------------------------------------------------------
# DEPLOY INTO THE DEFAULT VPC AND SUBNETS
# To keep this example simple, we are deploying into the Default VPC and its subnets. In real-world usage, you should
# deploy into a custom VPC and private subnets.
# ---------------------------------------------------------------------------------------------------------------------

data "aws_vpc" "default" {
  default = true
}

data "aws_subnet_ids" "all" {
  vpc_id = "${data.aws_vpc.default.id}"
}

# ---------------------------------------------------------------------------------------------------------------------
# CREATE THE ECS CLUSTER
# ---------------------------------------------------------------------------------------------------------------------

resource "aws_ecs_cluster" "example" {
  name = "${var.cluster_name}"
}

# ---------------------------------------------------------------------------------------------------------------------
# CREATE THE ECS SERVICE AND ITS TASK DEFINITION
# ---------------------------------------------------------------------------------------------------------------------

resource "aws_ecs_service" "example" {
  name            = "${var.service_name}"
  cluster         = "${aws_ecs_cluster.example.arn}"
  task_definition = "${aws_ecs_task_definition.example.arn}"
  desired_count   = 0
  launch_type     = "FARGATE"

  network_configuration {
    subnets = "${data.aws_subnet_ids.all.ids}"
  }
}

resource "aws_ecs_task_definition" "example" {
  family                   = "terratest"
  network_mode             = "awsvpc"
  cpu                      = 256
  memory                   = 512
  requires_compatibilities = ["FARGATE"]
  execution_role_arn       = "${aws_iam_role.execution.arn}"
  container_definitions    = <<-JSON
    [
      {
        "image": "terraterst-example",
        "name": "terratest",
        "networkMode": "awsvpc"
      }
    ]
  JSON
}

# ---------------------------------------------------------------------------------------------------------------------
# CREATE THE ECS TASK EXECUTION ROLE AND ATTACH APPROPRIATE AWS MANAGED POLICY
# ---------------------------------------------------------------------------------------------------------------------

resource "aws_iam_role" "execution" {
  name               = "${var.cluster_name}-ecs-execution"
  assume_role_policy = "${data.aws_iam_policy_document.assume-execution.json}"
}

resource "aws_iam_role_policy_attachment" "execution" {
  role       = "${aws_iam_role.execution.id}"
  policy_arn = "arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy"
}

data "aws_iam_policy_document" "assume-execution" {
  statement {
    effect  = "Allow"
    actions = ["sts:AssumeRole"]
    principals {
      type        = "Service"
      identifiers = ["ecs-tasks.amazonaws.com"]
    }
  }
}
```

**Comment by yorinasub17** [comment]
> there is a REGION env variable but not AWS_DEFAULT_REGION

Do you mean you have `REGION` or `AWS_REGION` set in the container environment? If so, that has precedence over `AWS_DEFAULT_REGION`.

One thing you can try is to update your terraform module to take in region as an input variable, and pass it in using `Vars`.

**Comment by divavatsa** [comment]
Hi Team,
I am getting below error; for my test -- FAIL: TestTerraformVolumetricMdlExample (38.12s)
    lambda.go:15: 
        	Error Trace:	lambda.go:15
        	            				terraform_volumetric_mdl_example_test.go:43
        	Error:      	Received unexpected error:
        	            	Unhandled error invoking lambda function: [123 34 101 114 114 111 114 77 101 115 115 97 103 101 34 58 32 34 66 97 100 32 104 97 110 100 108 101 114 32 39 116 101 114 114 97 116 101 115 116 45 118 111 108 117 109 101 116 114 105 99 45 109 100 108 45 101 120 97 109 112 108 101 45 108 97 109 98 100 97 39 58 32 110 111 116 32 101 110 111 117 103 104 32 118 97 108 117 101 115 32 116 111 32 117 110 112 97 99 107 32 40 101 120 112 101 99 116 101 100 32 50 44 32 103 111 116 32 49 41 34 44 32 34 101 114 114 111 114 84 121 112 101 34 58 32 34 82 117 110 116 105 109 101 46 77 97 108 102 111 114 109 101 100 72 97 110 100 108 101 114 78 97 109 101 34 125]
        	Test:       	TestTerraformVolumetricMdlExampl and please find the test code as below 
  
package test

import (
        "testing"
	"github.com/gruntwork-io/terratest/modules/aws"
	"github.com/gruntwork-io/terratest/modules/terraform"
	"github.com/stretchr/testify/assert"
)

// An example of how to test the Terraform module in examples/terraform-aws-lambda-example using Terratest.
func TestTerraformVolumetricMdlExample(t *testing.T) {
	t.Parallel()

	// Give this lambda function a unique ID for a name so we can distinguish it from any other lambdas
	// in your AWS account
	functionName := "terratest-volumetric-mdl-example-lambda"
	// Pick a random AWS region to test in. This helps ensure your code works in all regions.
	awsRegion := "us-east-1"

	terraformOptions := &terraform.Options{
		// The path to where our Terraform code is located
		TerraformDir: "../examples/terraform-volumetric-mdl-example",

		// Variables to pass to our Terraform code using -var options
		Vars: map[string]interface{}{
			"function_name": functionName,
		},

		// Environment variables to set when running Terraform
		EnvVars: map[string]string{
			"aws_region": awsRegion,
		},
	}

	// At the end of the test, run `terraform destroy` to clean up any resources that were created
	defer terraform.Destroy(t, terraformOptions)

	// This will run `terraform init` and `terraform apply` and fail the test if there are any errors
	terraform.InitAndApply(t, terraformOptions)

	// Invoke the function, so we can test its output
	response := aws.InvokeFunction(t, awsRegion, functionName, ExampleFunctionPayload{ShouldFail: false, Echo: "hi!"})

	// This function just echos it's input as a JSON string when `ShouldFail` is `false``
	assert.Equal(t, `"hi!"`, string(response))



}

type ExampleFunctionPayload struct {
	Echo       string
	ShouldFail bool
}

**Comment by Emil-jonsson** [comment]
I got the exact error as you did. Were you able to solve it in some way? also trying to invoke and test a lambda function. Whats up with all them numbers xD
