### ISSUE TITLE
Adding support to run and test docker stop command

### ISSUE THREAD

**Issue by dhwaneetbhatt** [gruntwork-io/terratest#421]
I am using terratest to test images which run a node server, and at the end of every test I stop the container and run it again in another test using different combinations.

For it, I would need a way to stop the container, I currently do it by running `docker stop` using Go's built in exec command, but it does make sense to bake it into the framework.

I have implemented this locally and its working. If it is good enough to be added to the framework, I'll raise a PR for it.

**Comment by yorinasub17** [comment]
Please check out [our contribution guide](https://github.com/gruntwork-io/terratest/blob/master/CONTRIBUTING.md#types-of-contributions). To avoid Terratest from becoming massive and bloated, we need to be picky about the helpers we add.

A `docker.Stop` helper function passes the litmus test for "platforms", "popularity", and "creating infrastructure", but I am not sure it passes the test for "complexity." If you look at the docker helpers we currently have, there is not a lot of code surrounding the `run` and `build` commands: most of the heavy lifting is done by the `shell` module.

So a quick sanity check: would it simplify your logic some more if you use the `shell` module as opposed to the `exec` function?

**Comment by dhwaneetbhatt** [comment]
@yorinasub17 yes that's correct, it doesn't pass the test of complexity. I would be okay using terratest shell for the use case. Thanks for providing a good workaround, its much easier to use than Go's exec.

Also, I would sooner or later need to use docker exec as well to verify few things once the container is running. I could use shell for that too but do you think it passes litmus test for all the parameters to be added to the terratest docker module?

**Comment by brikis98** [comment]
@yorinasub17 One thought: while we certainly don't want Terratest to get too bloated, I wonder if our contribution guidelines are missing a balance of "API is reasonably complete and coherent." E.g., if we have a `docker run` helper, a `docker stop` helper seems like it should be part of the API too, even if it's not overly complicated to write. That said, we don't need to support *every* Docker CLI method; just the major ones, and those that would often be used in tandem. WDYT?

**Comment by dhwaneetbhatt** [comment]
For context, I mostly test containers which run services, run I have to run them in detach mode, and then test a couple of things, and then stop them before the test ends.

For some cases, I also use `docker exec` to run commands inside the container to assert a few things (proper versions of libraries installed, directories exist etc). I consider `docker stop` to be a core docker CLI command, but I do not consider `docker exec` to be a core CLI method, but `docker exec` is sufficiently more complex so it passes the litmus test for complexity.

When I started using terratest, I was surprised it did not have a `docker stop` (I doubted by auto-completion), but then it wasn't so big of a deal so I ended up using Go's exec, but as @yorinasub17 suggested, using `shell` is much less boilerplate.

**Comment by dhwaneetbhatt** [comment]
@yorinasub17 @brikis98 by any change were you guys able to come to an agreement?

**Comment by yorinasub17** [comment]
Sorry for the delay as we were out for the holidays.

> I wonder if our contribution guidelines are missing a balance of "API is reasonably complete and coherent."

That makes sense, and in that regard, adding a `Stop` function would be in line with that.

---

FWIW, I do think the `docker` terratest functionality could use an overhaul given that those only map the structs to CLI args which IMO is not really providing a lot of value beyond what `shell` provides. I have some thoughts on this that might be worth an RFC, but probably won't come out any time soon.

**Comment by dhwaneetbhatt** [comment]
Thanks for confirming @yorinasub17, I'll raise a PR.

**Comment by yorinasub17** [comment]
Released in https://github.com/gruntwork-io/terratest/releases/tag/v0.23.2

**Comment by zackproser** [comment]
> Please check out [our contribution guide](https://terratest.gruntwork.io/docs/community/contributing/). To avoid Terratest from becoming massive and bloated, we need to be picky about the helpers we add.
> 
> A `docker.Stop` helper function passes the litmus test for "platforms", "popularity", and "creating infrastructure", but I am not sure it passes the test for "complexity." If you look at the docker helpers we currently have, there is not a lot of code surrounding the `run` and `build` commands: most of the heavy lifting is done by the `shell` module.
> 
> So a quick sanity check: would it simplify your logic some more if you use the `shell` module as opposed to the `exec` function?

Updated with new link to [Terratest contribution guidelines](https://terratest.gruntwork.io/docs/community/contributing/).
