### ISSUE TITLE
Add support for non standard ssh ports

### ISSUE THREAD

**Issue by malmanzor** [gruntwork-io/terratest#433]
I need to test ssh access using a port other than 22 and it looks like the ssh module is hard coded to use port 22 in a few places such as https://github.com/gruntwork-io/terratest/blob/master/modules/ssh/ssh.go#L103 .

I am willing to make a PR for this if others think it would be a good enhancement. My thought was to add an optional `CustomPort` field to the Host struct. I would then add a `getPort` function to the host struct that would return the `CustomPort` if it is set or 22.

**Comment by brikis98** [comment]
A PR for this would be very welcome and the approach you described sounds reasonable. Thanks!

**Comment by yorinasub17** [comment]
PR is merged and released as https://github.com/gruntwork-io/terratest/releases/tag/v0.23.3
