### ISSUE TITLE
Question and best practices

### ISSUE THREAD

**Issue by ismferd** [gruntwork-io/terratest#438]
Hi there,

I have just started to use terratest and I would like to know which will be a best practices for example testing a RDS Database which creation is really hard.
When an AWS resource takes longer than 5 minutes (aprox.) which can we do?

**Comment by yorinasub17** [comment]
Checkout this talk, which covers best practices for testing infrastructure code: https://www.infoq.com/presentations/automated-testing-terraform-docker-packer/

In general, you won't be able to avoid the long integration tests if your goal is test completeness/correctness. However, there are ways to mitigate those especially during local test development using test stages.
