### ISSUE TITLE
Kubernetes LoadBalancer service health check

### ISSUE THREAD

**Issue by aamirganihar** [gruntwork-io/terratest#449]
Hey guys! 

I'm a newbie to Terratest as well as Kubernetes. Have been trying my hands on to get an understanding of both the technologies for a project I'm working on. Since a couple of days I have been struggling to get one of the examples for Kubernetes defined in the Terratest Quick Start (https://terratest.gruntwork.io/examples/) to work. The test creates a Hello world deployment as well as a service of LoadBalancer type, which worked perfectly on my side. The next step in the test is to look for the service and execute an HTTP request. What fails is that the test keeps waiting for the service to be provisioned, even though the service is up and running already. I executed a curl request on the service and it returned a successful response. I then changed the type of the service from LoadBalancer to ClusterIP, and suddenly the service was able to be detected. What am I doing wrong here? I followed the exact steps mentioned in the examples document. In fact it works perfectly for a non-LoadBalancer type of service. Are there any additional steps that I need to perform?

**Comment by yorinasub17** [comment]
Can you share the following info?

- Which kubernetes are you using to test? Cloud, on-prem, or local? And if local, Docker Desktop k8s, minikube, or something else?

- What OS are you using to test on? Mac, Linux, Windows, or something else?

- There should be a URL in the test logs. What's the URL for load balancer?

My best guess as to what might be happening is that the load balancer hostname is not set up correctly in your k8s environment. One known issue is if you use `minikube` with Mac OSX: since `minikube` runs in its own VM on VirtualBox, the `minikube` hostname only works on the VM and not on the host machine, so you have to manually add the host to `/etc/hosts` to route to `$(minikube ip)`.

**Comment by aamirganihar** [comment]
1. I have a local Kubernetes setup with minikube
2. Its Mac OSX Catalina
3. This is the URL for the load balancer for the hello world service I deployed: http://192.168.64.4:31920.

I did add the minikube host entry in /etc/hosts, as shown below:

192.168.64.4 minikube

But it still seems to fail the test.

**Comment by yorinasub17** [comment]
> This is the URL of the load balancer for the hello world service I deployed: http://192.168.64.4:31920.

That looks like a `ClusterIP` URL. Can you share what it is for `LoadBalancer` where it doesn't work?

**Comment by aamirganihar** [comment]
I don't see a URL for the LoadBalancer. I'm attaching a couple of screenshots, maybe they might help

The output of `kubectl get svc`

![image](https://user-images.githubusercontent.com/7565257/73772502-8ae6f800-4780-11ea-8f3f-f7464127cf2c.png)

The output of `minikube service list`

![image](https://user-images.githubusercontent.com/7565257/73772622-c97cb280-4780-11ea-8b7d-e062a1dbd162.png)

And finally the output of `kubectl describe hello-world-service `

![image](https://user-images.githubusercontent.com/7565257/73772668-e3b69080-4780-11ea-8774-641f9da93815.png)

**Comment by yorinasub17** [comment]
Ah you know what, `LoadBalancer` doesn't actually behave the way I thought it did on minikube: it automatically converts it to `NodePort`, and thus does not have `ingress` set, which means `k8s.IsServiceAvailable` never returns true.

I am not sure I want to add custom logic for `minikube`, but nonetheless this is a bug in the hello world example!

**Comment by aamirganihar** [comment]
Okay. But I also tried running the tests against other services I had deployed. The results were the same. So how do I go ahead now? Should I create an `Ingress` for the `LoadBalancer` to work?

**Comment by yorinasub17** [comment]
Wait for https://github.com/gruntwork-io/terratest/pull/450 to merge.

**Comment by yorinasub17** [comment]
FYI it is now merged and released as: https://github.com/gruntwork-io/terratest/releases/tag/v0.23.5

Can you try that version and see if you still get the same issue?

**Comment by aamirganihar** [comment]
Works perfectly now!!

**Comment by yorinasub17** [comment]
Thanks for closing the loop!

**Comment by aamirganihar** [comment]
Facing the same issue again with a `LoadBalancer` type of service. Pulled the latest Terratest version using the command `go get -d -v github.com/gruntwork-io/terratest@v0.26.1`. The content of the go.mod file is as shown below:

module Terratest
  
```
go 1.13

require (
        github.com/go-sql-driver/mysql v1.4.1
        github.com/gruntwork-io/terratest v0.26.1
)
```

Is there anything that I am missing?

**Comment by bartek-lopatka** [comment]
I'm facing the same issue - `LoadBalancer` type of service is not discoverable while `ClusterIP` works just fine.
