### ISSUE TITLE
No valid credential sources found for AWS Provider when running terratest in github actions

### ISSUE THREAD

**Issue by 211217613** [gruntwork-io/terratest#453]
I'm trying to run terratest against localstack in github actions. When running natively on my laptop everything works fine. But when run in github actions I get the following error.

```
TestTerraformS3 2020-02-07T15:48:45Z command.go:158: rerun this command to reinitialize your working directory. If you forget, other
TestTerraformS3 2020-02-07T15:48:45Z command.go:158: commands will detect it and remind you to do so if necessary.
TestTerraformS3 2020-02-07T15:48:45Z retry.go:72: terraform [get -update]
TestTerraformS3 2020-02-07T15:48:45Z command.go:87: Running command terraform with args [get -update]
TestTerraformS3 2020-02-07T15:48:45Z command.go:158: - s3_test in ../../../s3_bucket
TestTerraformS3 2020-02-07T15:48:45Z command.go:158: - s3_test.tagging in ../../../tagging
TestTerraformS3 2020-02-07T15:48:45Z retry.go:72: terraform [apply -input=false -lock=false -auto-approve]
TestTerraformS3 2020-02-07T15:48:45Z command.go:87: Running command terraform with args [apply -input=false -lock=false -auto-approve]
TestTerraformS3 2020-02-07T15:48:48Z command.go:158: 
TestTerraformS3 2020-02-07T15:48:48Z command.go:158: Error: No valid credential sources found for AWS Provider.
TestTerraformS3 2020-02-07T15:48:48Z command.go:158: 	Please see https://terraform.io/docs/providers/aws/index.html for more information on
TestTerraformS3 2020-02-07T15:48:48Z command.go:158: 	providing credentials for the AWS Provider
TestTerraformS3 2020-02-07T15:48:48Z command.go:158: 
TestTerraformS3 2020-02-07T15:48:48Z command.go:158:   on main.tf line 4, in provider "aws":
TestTerraformS3 2020-02-07T15:48:48Z command.go:158:    4: provider "aws" {
TestTerraformS3 2020-02-07T15:48:48Z command.go:158: 
TestTerraformS3 2020-02-07T15:48:48Z command.go:158: 
TestTerraformS3 2020-02-07T15:48:48Z retry.go:80: Returning due to fatal error: FatalError{Underlying: exit status 1}
```

The terraform file under test is:
```
provider "aws" {
  region                      = "us-east-1"
  skip_credentials_validation = true
  skip_metadata_api_check     = true
  s3_force_path_style         = true
  endpoints {
    s3 = "http://localhost:4572"
  }
}

terraform {
  backend "local" {}
}

resource "aws_s3_bucket" "name" {
  bucket = "my-tf-test-bucket"
  acl    = "private"
}
```

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 19.10
Release:	19.10
Codename:	eoan
```

**Comment by yorinasub17** [comment]
If it is working locally but not in localstack, then my guess is that the localstack server is not up. Can you use curl or something to validate localstack is up before invoking `go`?

**Comment by 211217613** [comment]
> If it is working locally but not in localstack

I'm spinning up localstack via docker-compose in the terratest code. You can see the output here:
```
=== RUN   TestTerraformS3
TestTerraformS3 2020-02-07T15:48:02Z region.go:91: Using region ca-central-1
TestTerraformS3 2020-02-07T15:48:02Z command.go:87: Running command docker-compose with args [--project-name TestTerraformS3 up -d]
TestTerraformS3 2020-02-07T15:48:03Z command.go:158: Creating network "testterraforms3_default" with the default driver
TestTerraformS3 2020-02-07T15:48:04Z command.go:158: Pulling localstack (localstack/localstack:latest)...
TestTerraformS3 2020-02-07T15:48:04Z command.go:158: latest: Pulling from localstack/localstack
TestTerraformS3 2020-02-07T15:48:24Z command.go:158: Digest: sha256:2137f290c73e839e9fce162040374f71308c99fe222b2cf422fd8370032499b2
TestTerraformS3 2020-02-07T15:48:25Z command.go:158: Status: Downloaded newer image for localstack/localstack:latest
TestTerraformS3 2020-02-07T15:48:25Z command.go:158: Creating localstack ... 
TestTerraformS3 2020-02-07T15:48:32Z command.go:158: 
Creating localstack ... done
```

**Comment by yorinasub17** [comment]
> Is this because terratest aws sdk is looking for creds in $HOME/.aws/ and that doesn't exist in the github runner?

Ah yes. Regardless of using localstack or not, the aws sdk requires some credentials. I think it will work if you just set the env vars AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY to random strings in the github action environment.

**Comment by 211217613** [comment]
Is their a way to bypass all aws credential checks with terratest **or** should I just setup all fake creds.

I'm getting this error now:
```

    s3.go:21: 
        	Error Trace:	s3.go:21
        	            				s3_test.go:57
        	Error:      	Received unexpected error:
        	            	NoCredentialProviders: no valid providers in chain. Deprecated.
        	            		For verbose messaging see aws.Config.CredentialsChainVerboseErrors
        	Test:       	TestTerraformS3
```

 I also added fake creds to envVars in my terratest code:
```
	terraformOptions := &terraform.Options{
		TerraformDir: "./s3_test_localstack",

		EnvVars: map[string]string{
			"AWS_DEFAULT_REGION": awsRegion,
			"AWS_ACCESS_KEY_ID": "AKIAIOSFODNN7EXAMPLE",
			"AWS_SECRET_ACCESS_KEY": "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY",
		},
	}
```

**Comment by yorinasub17** [comment]
> Is their a way to bypass all aws credential checks 

This check is embedded in aws-sdk-go when you create new credentials, so there is no way for us to work around it. I would suggest using fake vars.

**Comment by yorinasub17** [comment]
Note that we don't use local stack or github actions internally, so the amount of help we can provide here is limited. We don't quite have the time to dig in deep here, but will keep this open to see if anyone else who has used either can help out.

**Comment by 211217613** [comment]
So the problem is with `aws-sdk-go`. Even though the terraform code has the ```  skip_credentials_validation = true
  skip_metadata_api_check     = true
  skip_requesting_account_id  = true
``` 
these values set, the sdk still needs something to check. I added 

```
      - name: aws cli config
        run: |
          pip install wheel
          pip install awscli
          aws configure set aws_access_key_id AKIAIOSFODNN7EXAMPLE -> this is fake
          aws configure set aws_secret_access_key wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY -> this is fake
          aws configure set default.region us-east-1
```

**Comment by yorinasub17** [comment]
Yes since the full configuration is isolated in your terraform config, I would classify this as an issue with the terraform provider and not terratest. One thing to try to fully validate that hypothesis is to cut terratest out of the equation and call terraform directly in the script (running just a plan so nothing gets deployed for example) and see if it still works. If it works, then it must be how terratest is passing the args so we can take a look; if it doesn't work then it's a terraform issue and you should file a ticket in the provider repo: https://github.com/terraform-providers/terraform-provider-aws/
