### ISSUE TITLE
Azure Fails with "Invoking Azure CLI failed with the following error: ERROR: Please run 'az login' to setup account"

### ISSUE THREAD

**Issue by SiobhanBaynes** [gruntwork-io/terratest#454]
Hi,

I'm trying to get a Terratest with Azure working and I'm following the example at https://github.com/gruntwork-io/terratest/tree/master/examples/terraform-azure-example.  I've added environment variables for ARM_CLIENT_ID, ARM_CLIENT_SECRET, ARM_SUBSCRIPTION_ID, ARM_TENANT_ID.

The process appears to work, I can see resources being created and destroyed in Azure but the final result appears to fail with no obvious underlying cause.

The error message is `Received unexpected error:
                                Invoking Azure CLI failed with the following error: ERROR: Please run 'az login' to setup account.`

A full sanitised log is attached.

I'd appreciate any assistance you can give.

[terratest_log.txt](https://github.com/gruntwork-io/terratest/files/4171992/terratest_log.txt)

**Comment by yorinasub17** [comment]
Hi take a look at https://github.com/TsuyoshiUshio/terratest/tree/feature/aks/examples/terraform-azure-aks-example#prerequisite-setup-azure-cli-access, which is a more complete setup guide for Azure terratest. This is a contribution currently in PR review that is slated to merge shortly.

**Comment by SiobhanBaynes** [comment]
I fixed this by adding ARM_SUBSCRIPTION_ID, ARM_CLIENT_ID, and ARM_CLIENT_SECRET environment variables inside the script and removing az login completely.

**Comment by nidhi5885** [comment]
Hi All, I am facing the same issue but with terragrunt. I have checked all the environment variables are already set.

**Comment by yorinasub17** [comment]
Can you file a new issue in `terragrunt` with a link to this issue? Thanks!

**Comment by daddula** [comment]
> I fixed this by adding ARM_SUBSCRIPTION_ID, ARM_CLIENT_ID, and ARM_CLIENT_SECRET environment variables inside the script and removing az login completely.

Hello, I am running into exact same issue. I am trying to understand where to add these environment variables in the script. Could you please share a snippet of your code for this part?

**Comment by yorinasub17** [comment]
> I am trying to understand where to add these environment variables in the script. 

We recommend adding these in outside the go test, in the test runner. This could be either:

- Your CI script. E.g., see how we set it up for the github action from the secrets: https://github.com/gruntwork-io/terratest/blob/master/.github/workflows/ci.yml#L75

- A helper script that knows how to configure these statically that you run prior to `go test` (see https://github.com/gruntwork-io/terratest/tree/master/examples/azure#review-environment-variables)
