### ISSUE TITLE
Helm3 Support for terratest

### ISSUE THREAD

**Issue by artisood** [gruntwork-io/terratest#455]
With Helm3  cannot run the example tests to begin with because the module (github.com/gruntwork-io/terratest/modules/helm) does not work with helm3.  Helm3 (helm template) does not have some switches that were available in helm2.

We have upgraded to helm3 so intent is to use terratest to write tests for helm charts.

It will be very helpful if you could please give estimated time line for enabling helm3 support in the helm module of terratest.
------- 
https://github.com/gruntwork-io/terratest-helm-testing-example
github.com/gruntwork-io/terratest/modules/helm -- Used latest release v0.24.2
Error below:-
go test -v -run TestPodTemplateRendersContainerImage
=== RUN   TestPodTemplateRendersContainerImage
TestPodTemplateRendersContainerImage 2020-02-09T12:48:56-05:00 command.go:87: Running command helm with args [template --set image=nginx -x templates/pod.yaml ../charts/minimal-pod]
TestPodTemplateRendersContainerImage 2020-02-09T12:48:56-05:00 command.go:158: Error: unknown shorthand flag: 'x' in -x
--- FAIL: TestPodTemplateRendersContainerImage (0.06s)
    template.go:20: 
        	Error Trace:	template.go:20
        	            				minimal_pod_template_test.go:23
        	Error:      	Received unexpected error:
        	            	exit status 1
        	Test:       	TestPodTemplateRendersContainerImage
FAIL
exit status 1

**Comment by yorinasub17** [comment]
Thanks for reporting! We are aware of a few backwards incompatibilities broken with helm 3 and plan on updating terratest in the near future (within the next 3 months, likely sooner).

Since we already have a helm 3 ticket (https://github.com/gruntwork-io/terratest/issues/403) closing this as a duplicate.
