### ISSUE TITLE
Ordering tests in terratest

### ISSUE THREAD

**Issue by nandac** [gruntwork-io/terratest#456]
Hi Terratest team,

Let me first take the opportunity to congratulate you on building this package. It is given me a lightweight package for testing infrastructure instead of resorting to Chef/kitchen-terraform or inspec. 

I have the need to order tests such as running Terraform code validation and code formatting tests before running Terraform plan and Terraform apply tests.

According to the testify package the tests run in alphabetical order due to the implementation of reflect.

Since we are not actually writing unit tests but integration tests when testing infrastructure what would you suggest is the best way to order tests so that they run in sequence apart from changing the names of the tests to be alphabetical.

FYI, I am using a test suite to run my tests.

Looking forward to your thoughts.

**Comment by yorinasub17** [comment]
You can use [go's subtesting ability](https://blog.golang.org/subtests) to do this:

```
func TestModule(t *testing.T) {
    // These functions should terminate the test with `require` or `t.Fatal` if they fail so the rest of the test function does not execute.
    terraformValidate(t)
    terraformFormat(t)

    // Only if the above two pass will it get to here
    for _, testFuncs := range []struct{
        name string
        tfunc func(*testing.T)
    }{ {"TestA", testA}, {"TestB", testB}, {"TestC", testC} } {
        t.Run(testFuncs.name, testFuncs.tfunc)
    }
}
```

**Comment by nandac** [comment]
Thanks, @yorinasub17  for your reply.

The only issue is I need to figure out how to use the above approach within a test suite or remove the suite altogether and run the tests individually to get the control I need.

**Comment by yorinasub17** [comment]
AFAIK this is the only way to have full control over the execution order of tests. Otherwise you are depending on go internals, which could change.

**Comment by nandac** [comment]
Agreed. I am a newbie to golang and just wanted to know if they were other approaches.

Thanks @yorinasub17.

**Comment by robmorgan** [comment]
I'm marking this as closed.
