### ISSUE TITLE
GetAccountId method gets the master account and not the current account

### ISSUE THREAD

**Issue by brucedvgw** [gruntwork-io/terratest#461]
As part of my test I want to grab the account ID of the IAM user that is running the test.  However when I use ` aws.GetAccountId(t)` it returns the master account account ID and not the current account.

Below is the test:
```go
accountID := aws.GetAccountId(t)
logGroupArn := terraform.Output(t, terraformOptions, "log_group_arn")

expectedLogGroupArn := "arn:aws:logs:eu-west-1:" + accountID + ":log-group:/aws/lambda/logGroup1-" + environment + ":*"

assert.Equal(t, expectedLogGroupArn, logGroupArn)
```

Result:
```bash
expected: "arn:aws:logs:eu-west-1:12345678:log-group:/aws/lambda/LogGroup1-environment-NXHqQX:*"
actual  : "arn:aws:logs:eu-west-1:87654321:log-group:/aws/lambda/LogGroup1-environment-NXHqQX:*"
```

note: `environment` is a uniqueID

**Comment by brikis98** [comment]
That [method](https://github.com/gruntwork-io/terratest/blob/master/modules/aws/account.go#L28) calls `get-caller-identity` in STS, so it should return whatever user is authenticated for your tests. Try to compare it to running `aws sts get-caller-identity` with the AWS CLI.

**Comment by brucedvgw** [comment]
Thanks Yevgeniy I will do some more digging as to why I am getting the master account and not the child account the IAM User is in.
