### ISSUE TITLE
Command line argument [build failed]

### ISSUE THREAD

**Issue by jawoponlenuigalwaycom** [gruntwork-io/terratest#466]
![Screenshot_20200226_215246](https://user-images.githubusercontent.com/56373264/75391702-81b1fc80-58e2-11ea-8bc5-4e09637b9967.jpg)

**Comment by yorinasub17** [comment]
Thanks for understanding and posting a new issue!

So the project id is the GCP project that you want to deploy the resources into. In the console, you should be able to see the project ID in the project info card when you load the project:

<img width="1425" alt="Home_–_development_–_Google_Cloud_Platform_-_Mozilla_Firefox" src="https://user-images.githubusercontent.com/430092/75392232-6de5a680-58a0-11ea-9247-b576b601e766.png">

You then want to set that as an environment variable. E.g:

```bash
GOOGLE_CLOUD_PROJECT=foo-asdf1234 go test -v -timeout 90m
```

or

```bash
export GOOGLE_CLOUD_PROJECT=foo-asdf1234
go test -v -timeout 90m
```

**Comment by jawoponlenuigalwaycom** [comment]
Thanks a million , I'll try that when I get back into work!!!!

**Comment by jawoponlenuigalwaycom** [comment]
![image](https://user-images.githubusercontent.com/56373264/75428828-afc62980-5940-11ea-92bf-f5de13c635bd.png)
 I tried your solution and definitely got further, I'm concerned with the configuration errors mentioned first, thnx

**Comment by robmorgan** [comment]
@jawoponlenuigalwaycom which version of Terraform are you running? Is it greater than 0.12?

**Comment by jawoponlenuigalwaycom** [comment]
![image](https://user-images.githubusercontent.com/56373264/75435125-7db9c500-594a-11ea-82fe-e4a38883d286.png)
looks like its out of date , i'll update it and see if that works,thanks

**Comment by jawoponlenuigalwaycom** [comment]
didn't do the trick

**Comment by robmorgan** [comment]
@jawoponlenuigalwaycom could you do the following for me?

1. Go to the `~/go/src/terratest-master/examples/terraform-gcp-hello-world-example` directory.
2. Run `terraform version`.
3. Run `terraform init`.
4. Post a screenshot of your terminal here.

**Comment by jawoponlenuigalwaycom** [comment]
![image](https://user-images.githubusercontent.com/56373264/75450012-f2e6c380-5965-11ea-8f5c-91ef8dc5d9a3.png)

**Comment by robmorgan** [comment]
@jawoponlenuigalwaycom okay can you try running the test again and post the output?

**Comment by jawoponlenuigalwaycom** [comment]
![image](https://user-images.githubusercontent.com/56373264/75452272-e6646a00-5969-11ea-9b21-e3b5df562dd8.png)
great I got a new issue instead, that's progress.btw my credentials are in this format 
![image](https://user-images.githubusercontent.com/56373264/75452437-380cf480-596a-11ea-9ae7-e1696d183ddf.png)

**Comment by robmorgan** [comment]
@jawoponlenuigalwaycom okay I have a feeling now the latest error is maybe your credentials aren't proper JSON. Can you try to validate the JSON syntax somehow in your credentials file?

**Comment by robmorgan** [comment]
@jawoponlenuigalwaycom okay I have a feeling now the latest error is maybe your credentials aren't proper JSON. Can you try to validate the JSON syntax somehow in your credentials file?

**Comment by jawoponlenuigalwaycom** [comment]
@robmorgan , it works beautifully , Just wow thanks a million!!!!

**Comment by jawoponlenuigalwaycom** [comment]
@robmorgan , it works beautifully , Just wow thanks a million!!!!

**Comment by robmorgan** [comment]
Ok cool bananas 😎! I'm going to close this issue.
