### ISSUE TITLE
Passing nested/complex structures as Vars

### ISSUE THREAD

**Issue by oijr** [gruntwork-io/terratest#475]
In the variables for the module that I'm testing, I have:

```
variable "foo" {
    type = list(object({
        mystring: string
        mybool: bool
    }))
    default = []
}

variable "bar" {
    type = object({
        mylist: list(string)
        mysecondstring: string
    })
}
```

When I invoke the module in Terratest, I need to pass values to these variables from the Go test function. How do I create/denote these complex variables within my Go code - there are also maps and sets - which aren't native to the datatypes in Go.
I've looked through the existing Terratest documentation, and I can't find anything relating to this.

**Comment by yorinasub17** [comment]
This is a golang limitation of the type system, but basically you want to abuse `interface{}`. E.g.,

```go
terraform.Options{
  Vars: map[string]interface{}{
    "foo": map[string]interface{}{
      "mystring": "foo-string",
      "mybool": true,
    },
    "bar": map[string]interface{}{
      "mylist": []string{"foo", "bar"},
      "mysecondstring": "bar-string",
    },
  },
}
```
