### ISSUE TITLE
IsPodAvailable returns true if the pod is running.

### ISSUE THREAD

**Issue by developer-guy** [gruntwork-io/terratest#479]
I think this is the wrong way to get pod's health status because when i deploy my app with health checks i mean with liveness&readiness probes it will wait for seconds defined in "initialDelaySeconds" field and during this time pod will not be ready but when i checked my phase field of status field of my Pod, it says its Running, this is the problem, and in pod.go at line 138 in Terratest there is a code like below :

```
// IsPodAvailable returns true if the pod is running.
func IsPodAvailable(pod *corev1.Pod) bool {
	return pod.Status.Phase == corev1.PodRunning
}
```

this is the screenshots for demo.
<img width="809" alt="Screen Shot 2020-03-21 at 18 17 13" src="https://user-images.githubusercontent.com/16693043/77229694-62845300-6ba0-11ea-8577-a35012084db8.png">
<img width="730" alt="Screen Shot 2020-03-21 at 18 17 41" src="https://user-images.githubusercontent.com/16693043/77229699-67e19d80-6ba0-11ea-89eb-413a0984708a.png">

**Comment by yorinasub17** [comment]
Good point! Are you free to submit a PR to enhance this? Otherwise, we are a bit buried at the moment, but will get to it at our earliest convenience.

**Comment by developer-guy** [comment]
Yeah, i will try to fix that bug as soon as possible , thank you @yorinasub17 .

**Comment by developer-guy** [comment]
i realized that within pod spec there is a containerStatuses field inside spec field: 

> containerStatuses:
>   - containerID: containerd://07acb5e5b197e2fbce8765c6e2040b67856a34fb3ef70b4d47ad2532ddf1c8c5
>     image: sfrontregistry.trendyol.com/trendyol-consul-template-injector-server:health
>     imageID: sha256:dca841e9cf3657e091853f81cf12b8ca2742c8e26965cf4c91b2ff5f29309394
>     lastState: {}
>     name: injector-chart
>     ready: true
>     restartCount: 0
>     started: true
> 

and here is two fields are important for us to understand pod status and these are **ready** and **started**.

I think we should check the ready field all of containers inside the pod then we can say pod is running if all of them ready.  @yorinasub17 

here is the screenshots above describes this situation:  

1 - I deployed my application and waiting for healthchecks for 50 seconds
![Screen Shot 2020-03-23 at 12 06 04](https://user-images.githubusercontent.com/16693043/77300301-dd638000-6cfe-11ea-85aa-1a2dda3f1e2b.png)
2 - Checked the containerStatuses field , you notice that ready:false
![Screen Shot 2020-03-23 at 12 06 22](https://user-images.githubusercontent.com/16693043/77300319-e3f1f780-6cfe-11ea-8959-08175744ed3f.png)
3 - Then pod is running now
![Screen Shot 2020-03-23 at 12 06 46](https://user-images.githubusercontent.com/16693043/77300415-0dab1e80-6cff-11ea-8b4d-9638aea9026d.png)
4 - Checked again containerStatuses field, you notice that ready:true
![Screen Shot 2020-03-23 at 12 07 01](https://user-images.githubusercontent.com/16693043/77300465-21568500-6cff-11ea-8546-ec170816d61c.png)

**Comment by developer-guy** [comment]
@yorinasub17 , i opened a PR #480 for this bug like i said , can you please review it when you are available , thanks.

**Comment by yorinasub17** [comment]
Released as https://github.com/gruntwork-io/terratest/releases/tag/v0.26.1
