### ISSUE TITLE
Question: Mocking Strategy for module libraries

### ISSUE THREAD

**Issue by TsuyoshiUshio** [gruntwork-io/terratest#481]
Hello, 

I have a question about the mocking strategy. In the module directory, I can find the test. However, I can't see any mock related testing. 
I'm planning to contribute this repo for the azure related new modules, 
Do you have any preference for a mocking strategy for the module unit testing? 

For example, I usually use Monkey Patch https://github.com/bouk/monkey . 

@rguthriemsft @QuickNS

**Comment by brikis98** [comment]
To answer your main question, I don't think we are using any mocking libraries right now. Monkey Patching also seems... risky. What use case did you have in mind for that?

You also mentioned adding support for Azure modules. Please be sure to read this: https://github.com/gruntwork-io/terratest/issues/89#issuecomment-582494195
