### ISSUE TITLE
Tests failing when change profile in use

### ISSUE THREAD

**Issue by pisarenko91** [gruntwork-io/terratest#485]
Hey all, 
I'm authenticating to AWS accounts via shared credentials file, stored in regular path(/home/$USERNAME/.aws/credentials). When I run my simple test that is checking if 4 created subnets are public using "default" profile(my testing AWS account) it all works well, test is passing.
When I change the profile used to clients AWS profile, passing this info as variable in provider block:

provider "aws" {
  region  = var.region
  profile = var.profile
}

Test is failing... Interesting fact, when i check AWS console in parallel with test, I see with my own eyes that everything is deployed correctly to correct AWS account, but for some strange reason test is reporting that there are 0 subnets present, when it is expecting 4. Questionable code block from test:

func TestLaunchpadDrVpc(t *testing.T) {
	t.Parallel()

	// Define variables for passing into Terraform
	// These variables are expected by Terraform and must be provided
	dRsubnet1Cidr := "***.***.***.***/**"
	dRsubnet2Cidr := "***.***.***.***/**"
	dRsubnet3Cidr := "***.***.***.***/**"
	dRsubnet4Cidr := "***.***.***.***/**"
	dRawsRegion := "eu-west-1"
	dRawsProfile := "clientname"
	// billingTag := "clientname"
	// envTag := "testing-dr"

	terraformOptions := &terraform.Options{
		TerraformDir: "../examples/test-example",

		Vars: map[string]interface{}{
			"subnet1_cidr_block": dRsubnet1Cidr,
			"subnet2_cidr_block": dRsubnet2Cidr,
			"subnet3_cidr_block": dRsubnet3Cidr,
			"subnet4_cidr_block": dRsubnet4Cidr,
			"region": dRawsRegion,
			"profile": dRawsProfile,
			// "billing_code_tag": billingTag,
			// "environment_tag": envTag,
		},
	}

	// This will run when test end - terraform destroy
	defer terraform.Destroy(t, terraformOptions)

	// Initalizing and applying terraform code
	terraform.InitAndApply(t, terraformOptions)

	dRsubnet1Id := terraform.Output(t, terraformOptions, "subnet1_id")
	dRsubnet2Id := terraform.Output(t, terraformOptions, "subnet2_id")
	dRsubnet3Id := terraform.Output(t, terraformOptions, "subnet3_id")
	dRsubnet4Id := terraform.Output(t, terraformOptions, "subnet4_id")
	dRvpcID := terraform.Output(t, terraformOptions, "vpc_id")

	dRsubnets := aws.GetSubnetsForVpc(t, dRvpcID, dRawsRegion)

	require.Equal(t, 4, len(dRsubnets))

	assert.True(t, aws.IsPublicSubnet(t, dRsubnet1Id, dRawsRegion))
	assert.True(t, aws.IsPublicSubnet(t, dRsubnet2Id, dRawsRegion))
	assert.True(t, aws.IsPublicSubnet(t, dRsubnet3Id, dRawsRegion))
	assert.True(t, aws.IsPublicSubnet(t, dRsubnet4Id, dRawsRegion))
}

When I change region that is being used, with default profile, it all works. Issue starts when I change the profile(AWS account) that is used.

Bare in mind that my knowledge of Go is close to 0.

Please help...

**Comment by yorinasub17** [comment]
This is an issue with how terratest handles authentication in the `aws` modules. Specifically, currently there is no way to modify which profile it assumes in the code.

We built it this way because the philosophy behind terratest is that which account you run the tests in should be provided to it from the environment, as opposed to in the test code. So the suggested way to handle your use case is to set the environment variable `AWS_PROFILE` when calling out to go test:

```
AWS_PROFILE=clientname go test -v -timeout 90m .
```

**Comment by pisarenko91** [comment]
> This is an issue with how terratest handles authentication in the `aws` modules. Specifically, currently there is no way to modify which profile it assumes in the code.
> 
> We built it this way because the philosophy behind terratest is that which account you run the tests in should be provided to it from the environment, as opposed to in the test code. So the suggested way to handle your use case is to set the environment variable `AWS_PROFILE` when calling out to go test:
> 
> ```
> AWS_PROFILE=clientname go test -v -timeout 90m .
> ```

I confirm that this solved my issue... Closing this thread...
Thank you very much!

**Comment by sekka1** [comment]
Just for the next person that runs into this and putting a note here about it.  If you are assuming a role via a `source_profile` like:

```
[profile1]
aws_access_key_id = aaaaaaaaaaaaaaaaaaa
aws_secret_access_key = bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb

[profile2]
role_arn = arn:aws:iam::111111111111:role/my-role
source_profile = profile1
role_session_name = profile1-session-name
```
You will need to set the `AWS_SDK_LOAD_CONFIG` envar like:

```
AWS_SDK_LOAD_CONFIG=1 AWS_PROFILE=clientname go test -v -timeout 90m .
```

This doc gives you more information on why: https://pkg.go.dev/github.com/aws/aws-sdk-go/aws/session#hdr-Shared_Config_Fields
