### ISSUE TITLE
Kubernetes Load Balancer type of service is not being recognized by Terratest tests

### ISSUE THREAD

**Issue by aamirganihar** [gruntwork-io/terratest#487]
I have a test that creates a Kubernetes deployment and a service of LoadBalancer type. The test then looks for this service to execute an HTTP request. The test keeps waiting for the service to be provisioned, even though the service is up and running and then eventually fails. I executed a curl request on the service and it returned a successful response. On changing the service type from LoadBalancer to ClusterIP, leads to a success result. I had logged the same bug a couple of months ago and it had worked perfectly for version 0.23.5. I pulled the newest Terratest version (0.26.1) yesterday and suddenly this issue cropped up. Am I missing any step here? I am new to both Terratest and Go, so I am not sure if I am following the right steps. I pulled the latest Terratest version using the command `go get -d -v github.com/gruntwork-io/terratest@v0.26.1`. The content of the go.mod file is as shown below:

```
module Terratest

go 1.13

require (
        github.com/go-sql-driver/mysql v1.4.1
        github.com/gruntwork-io/terratest v0.26.1
)
```
The last time, all I had done was to run the go get command with version 0.23.5 and it had started to work.

**Comment by yorinasub17** [comment]
What Kubernetes cluster are you targeting? We recently updated the logic for getting the host name of `LoadBalancer` service types in https://github.com/gruntwork-io/terratest/releases/tag/v0.24.2, and it is possible the new logic broke it for you. But the fix is unclear to me without knowledge of the Kubernetes cluster since the behavior of `LoadBalancer` is highly dependent on the platform.

**Comment by aamirganihar** [comment]
I am using a single cluster setup on Minkube

**Comment by yorinasub17** [comment]
Hmm that is strange, as we use minikube internally for testing and it works perfectly fine. Can you share:

- Which OS?
- What version of Minikube?
- The return value of `k8s.GetServiceEndpoint`?

**Comment by aamirganihar** [comment]
OS: MacOS Catalina 10.5.1
Minikube version: 1.8.2

I have the following lines in the code:

```
service := k8s.GetService(t, options, "conduit-frontend-lb")
endpoint := k8s.GetServiceEndpoint(t, options, service, 80)
fmt.Sprintf("http://%s", endpoint)
```

Since the test case fails to find the service and the endpoint function needs this service in order to run the function, I am not being able to find the return value of the service endpoint. Below is the error message that I receive:

```
TestConduitFrontEndServiceExample: service.go:106: 
        	Error Trace:	service.go:106
        	            				conduit_frontend_service_test.go:40
        	Error:      	Received unexpected error:
        	            	Service conduit-frontend-lb is not available
        	Test:       	TestConduitFrontEndServiceExample
--- FAIL: TestConduitFrontEndServiceExample (0.12s)
FAIL
```

I ran the same set of code against a `ClusterIP` type of service and it worked perfectly. Below are the service and endpoint details, if they are of any help

```
TestConduitFrontEndServiceExample 2020-04-02T10:22:17+02:00 client.go:33: Configuring kubectl using config file /Users/aamirganihar/.kube/config with context 
&Service{ObjectMeta:{kubernetes  default /api/v1/namespaces/default/services/kubernetes 82ac679a-ae67-478e-8101-21e300e0a430 152 0 2020-03-29 12:29:52 +0200 CEST <nil> <nil> map[component:apiserver provider:kubernetes] map[] [] []  []},Spec:ServiceSpec{Ports:[]ServicePort{ServicePort{Name:https,Protocol:TCP,Port:443,TargetPort:{0 8443 },NodePort:0,},},Selector:map[string]string{},ClusterIP:10.96.0.1,Type:ClusterIP,ExternalIPs:[],SessionAffinity:None,LoadBalancerIP:,LoadBalancerSourceRanges:[],ExternalName:,ExternalTrafficPolicy:,HealthCheckNodePort:0,PublishNotReadyAddresses:false,SessionAffinityConfig:nil,IPFamily:nil,TopologyKeys:[],},Status:ServiceStatus{LoadBalancer:LoadBalancerStatus{Ingress:[]LoadBalancerIngress{},},},}

10.96.0.1:80--- PASS: TestConduitFrontEndServiceExample (0.03s)
PASS
```

**Comment by aamirganihar** [comment]
This is the output of `kubectl get services` for the `LoadBalancer` service: 

![image](https://user-images.githubusercontent.com/7565257/78227164-2b317280-74cd-11ea-9e94-f25dea6f24b8.png)

**Comment by aamirganihar** [comment]
Do you need any other information? I have already wasted a lot of time getting Terratest to work. There aren't also clearly documented steps provided in the Quick Start Guide.

**Comment by yorinasub17** [comment]
Apologies for the frustrations and delay in responding. I had been extremely buried and only now getting back to going through terratest and terragrunt issues.

I think what is failing is the `IsMinikube` check [here](https://github.com/gruntwork-io/terratest/blob/master/modules/k8s/service.go#L126). For minikube, it is supposed to skip the service availability check and directly assume it is a `NodePort`. What's the result of calling `IsMinikubeE`?

What is confusing to me is that I can't repro the issue you are running into. I have OSX 1.15.3, and I tried minikube version 1.4.3 (which was already on my machine) and also upgrading to latest (1.9.2), but in both cases `GetServiceEndpoint` successfully returned an endpoint.

> Could you maybe list down the steps from scratch that I need to follow, in order to get this to work?

Assuming you are using go 1.13+, the steps to start from scratch are exactly the same as https://terratest.gruntwork.io/docs/getting-started/quick-start/#setting-up-your-project. You can also run `go mod tidy` right before calling `go test` to ensure you have all the dependencies installed at the latest version.

**Comment by aamirganihar** [comment]
So, I called the function `IsMinikubeE`, but it was unable to detect the Minikube instance. I have the following piece of code:

```
isMinikube, err := k8s.IsMinikubeE(t, options)
        if err != nil {
               fmt.Println("TRUE")
        } 
        if isMinikube {
               fmt.Println("TRUE")

        } else {
               fmt.Println("FALSE")
        }
```

The response was FALSE. How are then the tests with ClusterIP functioning, if its not being able to detect the Minikube instance at all? Am I using a wrong version of Minikube (in my case its 1.8.2), or the wrong version of the Minikube driver? I followed the setup instructions through and through, but now I am totally lost.

**Comment by yorinasub17** [comment]
Can you give me the output of `kubectl get nodes`? It determines if it is running on `minikube` by checking if the hostname is `minikube`, which seems to be consistent across the different versions of minikube I've used, both on OSX and Linux. Do you have some kind of special configuration to adjust that?

**Comment by aamirganihar** [comment]
Here is the output of `kubectl get nodes `

```
NAME   STATUS   ROLES    AGE   VERSION
m01    Ready    master   9d    v1.17.3
```
I used a hyperkit driver to install minikube. Do you think its got to do anything with that?

**Comment by yorinasub17** [comment]
Ah ok I was not aware that there were installation methods for minikube that doesn't mark the node as `minikube`. I'll look into seeing if there are other ways to know if the cluster is Minikube.

**Comment by yorinasub17** [comment]
Can you also run `kubectl get nodes -o yaml` and see if the node has labels with keys that start with `minikube.k8s.io`?

**Comment by aamirganihar** [comment]
Yes there are certain labels with keys that start with `minikube.k8s.io`. Below is a snippet of the output of the `kubectl get nodes -o yaml `command:

```
apiVersion: v1
items:
- apiVersion: v1
  kind: Node
  metadata:
    annotations:
      kubeadm.alpha.kubernetes.io/cri-socket: /var/run/dockershim.sock
      node.alpha.kubernetes.io/ttl: "0"
      volumes.kubernetes.io/controller-managed-attach-detach: "true"
    creationTimestamp: "2020-03-29T10:29:51Z"
    labels:
      beta.kubernetes.io/arch: amd64
      beta.kubernetes.io/os: linux
      kubernetes.io/arch: amd64
      kubernetes.io/hostname: m01
      kubernetes.io/os: linux
      minikube.k8s.io/commit: eb13446e786c9ef70cb0a9f85a633194e62396a1
      minikube.k8s.io/name: minikube
      minikube.k8s.io/updated_at: 2020_03_29T12_29_54_0700
      minikube.k8s.io/version: v1.8.2
      node-role.kubernetes.io/master: ""
    name: m01
    resourceVersion: "546935"
    selfLink: /api/v1/nodes/m01
    uid: 75bd397c-815b-4219-8741-1ca8c0f2ab35
```

**Comment by yorinasub17** [comment]
Hi I just released https://github.com/gruntwork-io/terratest/releases/tag/v0.26.3 as a potential fix for this. Can you try it out? It should work if you bump the version tag in `go.mod`.

**Comment by aamirganihar** [comment]
Its working perfectly now!!

**Comment by yorinasub17** [comment]
Great! Thanks for working through this with us (with lots of patience too)! Will mark this as closed.
