### ISSUE TITLE
Underlying: bufio.Scanner: token too long when reading terraform plan as json with Azure ARM template resource

### ISSUE THREAD

**Issue by nitinmuteja** [gruntwork-io/terratest#493]
I am using terraform azure arm templates as a resource in one module https://www.terraform.io/docs/providers/azurerm/r/template_deployment.html
When I create a plan and run the show command as json using the plan file, I get the following error:
Underlying: bufio.Scanner: token too long

TestUT_VerifyResourceNamingConventions 2020-04-07T19:41:19+05:30 command.go:158: 
2020/04/07 19:41:20 Ran terraform plan command
TestUT_VerifyResourceNamingConventions 2020-04-07T19:41:20+05:30 retry.go:72: terraform [show -json terraform.tfplan]
TestUT_VerifyResourceNamingConventions 2020-04-07T19:41:20+05:30 command.go:87: Running command terraform with args [show -json terraform.tfplan]
TestUT_VerifyResourceNamingConventions 2020-04-07T19:41:22+05:30 retry.go:80: Returning due to fatal error: FatalError{Underlying: bufio.Scanner: token too long}

V 0.26.2

**Comment by nitinmuteja** [comment]
shell.command outputmaxlinesize is not set from terraform.options.outputmaxlinesize

**Comment by brikis98** [comment]
Would you be up for a quick PR to fix this?

**Comment by nitinmuteja** [comment]
Yes I can.

**Comment by yorinasub17** [comment]
Fixed in https://github.com/gruntwork-io/terratest/releases/tag/v0.26.4
