### ISSUE TITLE
Terragrunt init feature not available here

### ISSUE THREAD

**Issue by DiptiPrakash** [gruntwork-io/terratest#503]
Hello ,
  My project is migrated to terragrunt . If we have some thing like  terragrunt init support then my problem is solved  . I can see we have "terraform.TgApplyAllE"  but we don't have terragrunt init support by this framework . Is it possible to add this feature .

Thanks
Dipti Prakash

**Comment by yorinasub17** [comment]
You can set [TerraformBinary](https://github.com/gruntwork-io/terratest/blob/master/modules/terraform/options.go#L11) to `terragrunt` and use the regular functions (e.g. `terraform.InitAndApply`).

**Comment by DiptiPrakash** [comment]
@yorinasub17 
Could you please explain little more with one example.

**Comment by yorinasub17** [comment]
To run `terragrunt init`, you can do the following:

```
  terraformOptions := &terraform.Options {
    // The path to where your Terragrunt code is located
    TerraformDir: "../web-server",
    TerraformBinary: "terragrunt",
  }
  terraform.Init(t, terraformOptions)
```

**Comment by DiptiPrakash** [comment]
Thanks @yorinasub17  . It's working now .

**Comment by zackproser** [comment]
Glad to hear @yorinasub17 's solution worked for you. I'm going to close this issue now - but please feel free to open new issues in the future should you come across anything else.
