### ISSUE TITLE
AWS client using AWS_PROFILE

### ISSUE THREAD

**Issue by gadelkareem** [gruntwork-io/terratest#516]
I am trying to select an AWS profile while calling NewEc2Client
```
os.Setenv("AWS_PROFILE", "some-profile")
ec2Client := taws.NewEc2Client(t, region)
```

The only way I see is to set the env var but is there a way to use it implicitly in the code so I can do parallel tests?

**Comment by yorinasub17** [comment]
For this use case, we recommend going directly with the AWS SDK. We don't expose all the configurations in terratest to avoid having a bloated API and only support the ones that are most common. Getting a new session for the SDK from a profile directly is relatively simple to do so we don't see a need to wrap it. You can get this with the following code:

```go
sess, err := session.NewSessionWithOptions(session.Options{
	  Profile: "some-profile",
})
require.NoError(t, err)
ec2Client := ec2.New(sess)
```

**Comment by gadelkareem** [comment]
Got it thanks!
