### ISSUE TITLE
Support OutputStruct for JSON struct matching

### ISSUE THREAD

**Issue by solarmosaic-kflorence** [gruntwork-io/terratest#523]
Provide an API like:

```go
func OutputStruct(t *testing.T, options *Options, key string, out interface{})
```

Where `out` would be a pointer. So the usage of it would be something like:

```go
type Example struct {
  foo string
  bar int
}

var example Example
terraform.OutputStruct(t *testing.T, options, "example", &example)
```

_Originally posted by @brikis98 in https://github.com/gruntwork-io/terratest/pull/513#issuecomment-627833280_

**Comment by bcatubig** [comment]
Why not use https://github.com/mitchellh/mapstructure to render a `map[string]interface{}` to a struct of your choice?

**Comment by solarmosaic-kflorence** [comment]
@bcatubig sorry, I am new to the Go ecosystem. Can you provide a quick example of how you would use that?

**Comment by solarmosaic-kflorence** [comment]
Resolved by https://github.com/gruntwork-io/terratest/pull/569
