### ISSUE TITLE
Terratest output returns command instead of output value

### ISSUE THREAD

**Issue by sdebruyn** [gruntwork-io/terratest#527]
When I run my terratest locally, it works without issues. But when I run it in GitHub Actions, my tests are failing because the Terraform output values are not what they should be. However, it looks like the issue is rather in running/parsing then in the output value itself.

```
2020-05-25T12:26:29.6692633Z         	Error:      	Not equal: 
2020-05-25T12:26:29.6692804Z         	            	expected: "tfadlthezcrt"
2020-05-25T12:26:29.6693850Z         	            	actual  : "[command]/home/runner/work/_temp/10e2cdd0-48f1-4e8b-93e2-e71c0d4d0a1d/terraform-bin output -no-color name\ntfadlthezcrt\n::debug::Terraform exited with code 0.\n::debug::stdout: tfadlthezcrt%0A\n::debug::stderr: \n::debug::exitcode: 0\n::set-output name=stdout::tfadlthezcrt%0A\n::set-output name=stderr::\n::set-output name=exitcode::0"
```

Relevant [code](https://github.com/datarootsio/terraform-module-azure-datalake/blob/0acee4555b34dd369b1c26803e69eab7d876d31d/test/terraform_apply_destroy_test.go):
```go
func TestApplyAndDestroyWithSamples(t *testing.T) {
	t.Parallel()

	name, options, err := getDefaultTerraformOptions(t)
	assert.NoError(t, err)

	defer terraform.Destroy(t, options)
	_, err = terraform.InitAndApplyE(t, options)
	assert.NoError(t, err)

	outDataLakeName, err := terraform.OutputE(t, options, "name")
	assert.NoError(t, err)

	assert.Equal(t, name, outDataLakeName)
}
```

You can see them in action here: https://github.com/datarootsio/terraform-module-azure-datalake/pull/76

E.g. in [this run](https://github.com/datarootsio/terraform-module-azure-datalake/actions/runs/114693076) one test failed, but the other one should have succeeded.

**Comment by yorinasub17** [comment]
I think this is a regression from the logging updates introduced in [0.27.3](https://github.com/gruntwork-io/terratest/releases/tag/v0.27.3). Does it work if you downgrade terratest to `0.27.2`?

**Comment by yorinasub17** [comment]
Ok actually, after investigating your github action, I have determined that it has nothing to do with the loggers in terratest.

I believe the issue has to do with the `terraform_wrapper` installed in https://github.com/hashicorp/setup-terraform . This wrapper is throwing off terratest because it is logging additional stuff in stdout for the purposes of setting variables in github actions. It should work if you either turn off `terraform_wrapper`, or set the `TerraformBinary` attribute on `terraform.Options` directly to the terraform binary installed.

**Comment by sdebruyn** [comment]
Thank you @yorinasub17 for pointing me in the right direction, that was the issue indeed!

**Comment by karthikeyansundararajan-agi** [comment]
Wasted a day because of the same issue. Thanks for documenting here.
