### ISSUE TITLE
Possible wrong test library

### ISSUE THREAD

**Issue by cairesvs** [gruntwork-io/terratest#538]
I was looking into the `test` files and realize that terratest is using `github.com/magiconair/properties/assert` and `github.com/stretchr/testify` assert. This is the correct behavior?

Related:
https://github.com/gruntwork-io/terratest/blob/master/test/docker_hello_world_example_test.go#L7
https://github.com/gruntwork-io/terratest/blob/master/test/packer_hello_world_example_test.go
https://github.com/gruntwork-io/terratest/blob/master/modules/terraform/apply_test.go#L6
https://github.com/gruntwork-io/terratest/blob/master/modules/gcp/compute_test.go#L12

**Comment by yorinasub17** [comment]
Ah that is indeed a mistake: we've been standardizing on the `stretchr/testify` library and those should indeed be from `testify`.

https://github.com/gruntwork-io/terratest/pull/539
