### ISSUE TITLE
Terratest incompatible with Terraform Cloud

### ISSUE THREAD

**Issue by dallinwright** [gruntwork-io/terratest#541]
I cannot seem to find anywhere in the documentation terraform workspace support for using `remote` as a backend. This is terrform cloud, for example here is my remote backend declaration.

```
# Terraform cloud integration. Note the resources must already exist below for this to work.
terraform {
  backend "remote" {
    hostname     = "app.terraform.io"
    organization = "xxxxxxx"

    workspaces {
      name = "workspace_name"
    }
  }
}
```

```
--- FAIL: TestTerraformOutputs (15.41s)
    apply.go:13:
        	Error Trace:	apply.go:13
        	            				xxxxxxxx.go:16
        	Error:      	Received unexpected error:
        	            	FatalError{Underlying: error while running command: exit status 1;
        	            	Error: Apply not allowed for workspaces with a VCS connection

        	            	A workspace that is connected to a VCS requires the VCS-driven workflow to
        	            	ensure that the VCS remains the single source of truth.
        	            	}
        	Test:       	TestTerraformOutputs
```

Is there support for this planned? I cannot run in my pipelines terratest as it seems to assume a certain back end type. Is this support planned? Or is this a terraform specific error or something I am missing? I did try this:

	`terraform.WorkspaceSelectOrNew(t, terraformOptions, "workspace_name")` 

but it still fails in my test file with the above error.

**Comment by bwhaley** [comment]
My understanding is that when you connect a VCS to a workspace in TFC, you can't just kick off a `terraform apply`. It has to commence with a commit to the repository that was connected. It should work if you use a workspace without a VCS connection. See the [CLI-driven Run Workflow documentation](https://www.terraform.io/docs/cloud/run/cli.html).

**Comment by dallinwright** [comment]
Ah yes it worked you were correct. Thanks!
