### ISSUE TITLE
Receiving the below error when using go version 1.10.

### ISSUE THREAD

**Issue by nnolan** [gruntwork-io/terratest#542]
# github.com/gruntwork-io/terratest/modules/shell
gopath/src/github.com/gruntwork-io/terratest/modules/shell/command.go:161:84: undefined: io.StringWriter
FAIL	command-line-arguments [build failed]

Please advise what should be done to mitigate this issue.

**Comment by yorinasub17** [comment]
Terratest dropped compatibility with go 1.10 a while ago. Is it possible for you to upgrade your environment to at least go 1.13? Otherwise, try version https://github.com/gruntwork-io/terratest/releases/tag/v0.20.1 (note: this requires using `dep` for dependency management).

**Comment by yorinasub17** [comment]
Related: https://github.com/gruntwork-io/terratest/issues/544
