### ISSUE TITLE
Test Case failure

### ISSUE THREAD

**Issue by vikaskoppineedi** [gruntwork-io/terratest#544]
Test cases stopped working not sure of the root cause. 
================================================
Failed Test Case dependecies and their versions 
dep init
  Locking in v1.6.0 (004e3cb) for transitive dep github.com/stretchr/testify
  Locking in v3 (e307989) for transitive dep gopkg.in/yaml.v3
  Locking in v1.0.0 (792786c) for transitive dep github.com/pmezard/go-difflib
  Locking in v1.1.1 (8991bc2) for transitive dep github.com/davecgh/go-spew
  Locking in master (627f964) for transitive dep golang.org/x/net
  Using ^0.28.2 as constraint for direct dep github.com/gruntwork-io/terratest
  Locking in v0.28.2 (a8cc331) for direct dep github.com/gruntwork-io/terratest
  Locking in master (279210d) for transitive dep golang.org/x/crypto
  Locking in master (6fdc65e) for transitive dep golang.org/x/sys

+ go test -v
test/vendor/github.com/gruntwork-io/terratest/modules/shell
vendor/github.com/gruntwork-io/terratest/modules/shell/command.go:161:84: undefined: io.StringWriter
FAIL	test [build failed]
================================================

Successfully Test cases and their dependencies and versions. 

+ dep init
  Locking in master (7e3656a) for transitive dep golang.org/x/net
  Locking in v1.5.1 (3ebf1dd) for transitive dep github.com/stretchr/testify
  Locking in v1.0.0 (792786c) for transitive dep github.com/pmezard/go-difflib
  Locking in v2.3.0 (0b1645d) for transitive dep gopkg.in/yaml.v2
  Locking in v1.1.1 (8991bc2) for transitive dep github.com/davecgh/go-spew
  Using ^0.27.2 as constraint for direct dep github.com/gruntwork-io/terratest
  Locking in v0.27.2 (dac0027) for direct dep github.com/gruntwork-io/terratest
  Locking in master (06a226f) for transitive dep golang.org/x/crypto
  Locking in master (417ce23) for transitive dep golang.org/x/sys
[Pipeline] sh
+ dep ensure
[Pipeline] sh
+ go test -v
The Test cases work. 
================================================

The same exact test case passed for Terragrunt version v0.27.2 whereas it fails now v0.28.2.

**Comment by yorinasub17** [comment]
Please upgrade your go version to at least 1.12. `io.StringWriter` was introduced in go 1.12.

Since v0.16.0, we've switched to using go modules. With this switch, we've standardized our internal testing of terratest to target go 1.13+. We don't plan on testing or supporting older versions of go, so your options are to either update your go version, or lock your versions to `0.27.2`.
