### ISSUE TITLE
terratest in container

### ISSUE THREAD

**Issue by tenderitaf** [gruntwork-io/terratest#546]
terratest for azure example fail while running in a container vs natively.

is azure cli mandatory in order to run the tests ?

**Comment by tsalright** [comment]
How are you authenticating to Azure? Running locally it defaults to Azure CLI and as a dev, we are usually always signed into it. But Terraform recommends using Azure's Managed Service Identity (MSI) or a Service Principal when connecting. I ran into this when trying to automate my own terratests against Azure modules I am building. Here is the security I had to setup. https://www.terraform.io/docs/providers/azurerm/guides/service_principal_client_secret.html

I was running my CI on hosted Azure DevOps agents and they all have Azure CLI on them, but I don't think it is required. I would try setting up the environment variables the link above suggests with a service principal that has access to provision resources in your subscription.

**Comment by tenderitaf** [comment]
Hi,
the problem is fixed, azure go sdk actually needs azure cli.
authentication are done via service principals and and expect specific env var to be set (was not documented)

AZURE_SUBSCRIPTION_ID
AZURE_CLIENT_SECRET
AZURE_TENANT_ID
AZURE_CLIENT_ID

**Comment by tsalright** [comment]
Good to know. I am just starting to explore azure go sdk. I had to set those environment variables up in my CI pipeline in order to work with Terraform too.

**Comment by tsalright** [comment]
So I have more details for anyone trying to automate tests against Azure with Terratest
You need an SPN that can do the provisioning and you need to setup two sets of environment variables.

These are the environment variables that Terraform is looking for:
ARM_SUBSCRIPTION_ID
ARM_CLIENT_SECRET
ARM_TENANT_ID
ARM_CLIENT_ID
See  https://www.terraform.io/docs/providers/azurerm/guides/service_principal_client_secret.html for details on authenticating with Terraform.

For the Azure SDK for Go, you need to configure a different set of environment variables.
AZURE_SUBSCRIPTION_ID
AZURE_CLIENT_SECRET
AZURE_TENANT_ID
AZURE_CLIENT_ID
See https://docs.microsoft.com/en-us/azure/developer/go/azure-sdk-authorization for details on authenticating with Azure SDK for Go.

**Comment by brikis98** [comment]
Please see https://github.com/gruntwork-io/terratest/issues/89 for the status on Terratest with Azure. In particular, we're [starting some work](https://github.com/gruntwork-io/terratest/issues/89#issuecomment-650052374) around it, and when that work is done, we'll be able to come back to this question!

**Comment by yorinasub17** [comment]
Closing as the original issue was solved.
