### ISSUE TITLE
Does terratest support checking that no changes happen a second apply?

### ISSUE THREAD

**Issue by shadycuz** [gruntwork-io/terratest#551]
I search but didn't find anything relevant.

**Comment by brikis98** [comment]
That's not a helper currently built-in, but that seems like a nice feature to add by calling `Apply` and then `Plan`. PR welcome!

**Comment by shadycuz** [comment]
@brikis98 yeah let me see what I can do 👀 *sketchy PR inbound*

**Comment by brikis98** [comment]
Thanks!

**Comment by yorinasub17** [comment]
For reference, here is what we do internally for this:

```go
		terraform.InitAndApply(t, options)
		counts := terraform.GetResourceCount(t, terraform.Plan(t, options))
		assert.Equal(t, 0, counts.Change)
		assert.Equal(t, 0, counts.Destroy)
		assert.Equal(t, 0, counts.Add)
```

**Comment by shadycuz** [comment]
oh thats nice @yorinasub17. I didn't see this in time or I might have gone down this road. Instead I used the exitCode of plan.

```go
exitCode := PlanExitCode(t, options)

	if exitCode != 0 {
		return "", errors.New("terraform configuration not idempotent")
	}
```
