### ISSUE TITLE
http_helper.HttpGetWithRetry does not use global proxy settings

### ISSUE THREAD

**Issue by miranius** [gruntwork-io/terratest#553]
A proxy has been configured on my machine (env http_proxy etc), about the test run, the method cannot reach my ec2 machine and the http.Get method can. Judging by the source, it looks like the library uses its [own](https://github.com/gruntwork-io/terratest/blob/master/modules/http-helper/http_helper.go#L35) http transport and does not use the global proxy settings, as Go himself [does](https://github.com/golang/go/blob/master/src/net/http/transport.go#L43). Correct me if I'm wrong

**Comment by brikis98** [comment]
Here's how we initialize `http.Transport`: https://github.com/gruntwork-io/terratest/blob/master/modules/http-helper/http_helper.go#L35-L37. Would you be up for a PR to use the defaults for from `DefaultTransport`?

**Comment by miranius** [comment]
Do let me make it's clear: I have a Terraform module that deploys an EC2 machine to AWS and a Go test that sends a request to this machine (code is below). The problem is the EC2 machine is available to me only through the proxy that I configured.

**My code:**
```
url: = terraform.Output (t, terraformOptions, "url")
status: = 200
text: = "Hello, World"
retries: = 5
sleep: = 40 * time.Second
http_helper.HttpGetWithRetry (t, url, nil, status, text, retries, sleep)
```
**Steps to reproduce:**
You need a remote machine that is not accessible without a proxy

**Current behavior:**
```
[...]
TestWebServer 2020-06-10T16:42:39+04:00 retry.go:72: HTTP GET to URL http://54.162.238.165:8080
TestWebServer 2020-06-10T16:42:39+04:00 http_helper.go:32: Making an HTTP GET call to URL http://54.162.238.165:8080
TestWebServer 2020-06-10T16:42:49+04:00 retry.go:84: HTTP GET to URL http://54.162.238.165:8080 returned an error: Get "http://54.162.238.165:8080": context deadline exceeded (Client.Timeout exceeded while awaiting headers). Sleeping for 40s and will try again.
TestWebServer 2020-06-10T16:43:29+04:00 retry.go:72: HTTP GET to URL http://54.162.238.165:8080
TestWebServer 2020-06-10T16:43:29+04:00 http_helper.go:32: Making an HTTP GET call to URL http://54.162.238.165:8080
TestWebServer 2020-06-10T16:43:39+04:00 retry.go:84: HTTP GET to URL http://54.162.238.165:8080 returned an error: Get "http://54.162.238.165:8080": context deadline exceeded (Client.Timeout exceeded while awaiting headers). Sleeping for 40s and will try again.
[...]
```
**Expected behavior:**
```
[...]
Making an HTTP GET call to URL http:///54.162.238.165:8080
Success!
[...]
```

**Comment by brikis98** [comment]
Yup, I understand! I think the only way to support that for now with Terratest helpers is to modify how we configure `http.Transport` to leverage `DefaultTransport`: https://github.com/gruntwork-io/terratest/blob/master/modules/http-helper/http_helper.go#L35-L37. If you're up for a PR to do that, we'd welcome it!

**Comment by alexkayabula** [comment]
@miranius @brikis98  I believe the cause of issue is that when initializing `http.Transport`, the `Proxy` field value was not set with the configured proxy `http_proxy` on your machine. 
I have a raised a pull request [560](https://github.com/gruntwork-io/terratest/pull/560) to address this issue.
