### ISSUE TITLE
getting "build constraints exclude all Go files in"

### ISSUE THREAD

**Issue by danseo-reisys** [gruntwork-io/terratest#557]
running go test on azure example getting the error

"build constraints exclude all Go files in"

can you provide some guidance on this error?

**Comment by brikis98** [comment]
Please see https://github.com/gruntwork-io/terratest/issues/89 for the status on Terratest with Azure. In particular, we're [starting some work](https://github.com/gruntwork-io/terratest/issues/89#issuecomment-650052374) around it, and when that work is done, we'll be able to come back to this question!

**Comment by AnishJS** [comment]
Hi,

I've been having this issue, any update on it please? @brikis98

**Comment by brikis98** [comment]
Could you provide more details? What commands are you running, exactly?

**Comment by yorinasub17** [comment]
Does it work if you run `go test -tags azure .`?

**Comment by robcamer** [comment]
@yorinasub17.  It does not work still.

**Comment by yorinasub17** [comment]
@robcamer which folder are you running the command in? Note that we moved all azure tests to `/test/azure`, so you need to run that go test call there.

**Comment by robcamer** [comment]
Actually, I was able to resolve the build tags issue.  Thanks!

**Comment by yorinasub17** [comment]
Thanks for closing the loop! Given that this ticket has the sufficient info now, will be closing as resolved.
