### ISSUE TITLE
k8s.GetServiceEndpoint returns only port

### ISSUE THREAD

**Issue by bartek-lopatka** [gruntwork-io/terratest#559]
I was trying to run [kubernetes_basic_example_service_check_test.go](https://github.com/gruntwork-io/terratest/blob/master/test/kubernetes_basic_example_service_check_test.go), but it's not working as expected. Nginx deployment and service are being deployed correctly, but then when I try to get endpoint, as per example (`endpoint := k8s.GetServiceEndpoint(t, options, service,80)`), it returns only port, so HTTP requests fail:

`TestSimpleNetworkCheck 2020-06-17T12:18:44+02:00 retry.go:72: HTTP GET to URL http://:31194
TestSimpleNetworkCheck 2020-06-17T12:18:44+02:00 http_helper.go:32: Making an HTTP GET call to URL http://:31194
TestSimpleNetworkCheck 2020-06-17T12:18:44+02:00 retry.go:84: HTTP GET to URL http://:31194 returned an error: Get http://:31194: dial tcp :31194: connect: connection refused. Sleeping for 10s and will try again.
TestSimpleNetworkCheck 2020-06-17T12:18:54+02:00 retry.go:72: HTTP GET to URL http://:31194
`

My code:

```
package simple_network_check

import (
	"crypto/tls"
	"fmt"
	http_helper "github.com/gruntwork-io/terratest/modules/http-helper"
	"github.com/gruntwork-io/terratest/modules/k8s"
	"github.com/stretchr/testify/require"
	"testing"
	"time"
)

func TestSimpleNetworkCheck (t *testing.T) {
	t.Parallel()

	kubeResourcePath := "./simple-webapp-deployment.yaml"

	options := k8s.NewKubectlOptions("","", "default")


	k8s.KubectlApply(t, options, kubeResourcePath)

	defer k8s.KubectlDelete(t, options, kubeResourcePath)


	k8s.WaitUntilServiceAvailable(t, options, "nginx-service", 5, 10*time.Second)

	service := k8s.GetService(t, options, "nginx-service")
	require.Equal(t, service.Name, "nginx-service")

	endpoint := k8s.GetServiceEndpoint(t, options, service,80)

	// Setup a TLS configuration to submit with the helper, a blank struct is acceptable
	tlsConfig := tls.Config{}

	// Test the endpoint for up to 5 minutes. This will only fail if we timeout waiting for the service to return a 200
	// response.
	http_helper.HttpGetWithRetryWithCustomValidation(
		t,
		fmt.Sprintf("http://%s", endpoint),
		&tlsConfig,
		30,
		10*time.Second,
		func(statusCode int, body string) bool {
			return statusCode == 200
		},
	)

}
```

I'm trying to run it on an EKS cluster, my OS is Mac and I'm using Go 1.13 and terratest v0.28.5

**Comment by brikis98** [comment]
Hm, that's really weird as we use nearly identical code to test endpoints on EKS... Can you share any more info about your EKS cluster or nginx deployment (e.g., the manifest for it)?

**Comment by bartek-lopatka** [comment]
What additional info about EKS you need? 

Nginx deployment manifest is basically taken from you examples folder:

`---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.15.7
          ports:
            - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      targetPort: 80
      port: 80
  type: NodePort`

**Comment by brikis98** [comment]
Thanks for the update. If you are using a `NodePort`, I believe the [`findEndpointForNodePortService`](https://github.com/gruntwork-io/terratest/blob/8f4c38b027dc70d4e0bb3a5100b54f1979938ffb/modules/k8s/service.go#L151) method is getting called. That method, in turn, uses [`FindNodeHostnameE`](https://github.com/gruntwork-io/terratest/blob/8f4c38b027dc70d4e0bb3a5100b54f1979938ffb/modules/k8s/service.go#L196) to get the hostname, and in your case, is getting an empty string. You could add some logging there (e.g., in your local Terratest checkout in `vendor`) to get more visibility into what's happening. 

Are you using an EKS cluster with self-managed worker nodes? AWS-managed? Or Fargate? Perhaps, depending on the configuration of the worker nodes (e.g., no public IP), we're failing to get the hostname.

**Comment by bartek-lopatka** [comment]
Huh. Yeah, we are running EKS with self-managed worker nodes without public IPs, so you are right, that's why there is no hostname here. I thought this function would return Endpoint URL that nginx service gets assigned on the kubernetes side, not the public hostname from AWS EC2.

Are there any workarounds/recommendations to make that work without having public IP for worker nodes?

**Comment by brikis98** [comment]
> Huh. Yeah, we are running EKS with self-managed worker nodes without public IPs, so you are right, that's why there is no hostname here. I thought this function would return Endpoint URL that nginx service gets assigned on the kubernetes side, not the public hostname from AWS EC2.

That's actually the design of [`NodePort`](https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types)! It's a way to expose a K8S service on the IPs of the worker nodes. 

If you're looking for a way to expose the service publicly, then you probably want `LoadBalancer` instead; this will deploy a load balancer of some sort and return its hostname. The type of load balancer depends on your K8S configuration; with EKS, you probably want to install something like the [ALB ingress controller](https://github.com/kubernetes-sigs/aws-alb-ingress-controller) into your cluster, which will result in an ALB being used as the load balancer.

**Comment by brikis98** [comment]
BTW, @yorinasub17, even if the worker nodes don't have public IPs, it still seems like a bug for Terratest to return an empty string, right?

**Comment by yorinasub17** [comment]
> even if the worker nodes don't have public IPs, it still seems like a bug for Terratest to return an empty string, right?

Yes that is a bug, as it is supposed to fallback to the node hostname when it is empty. Will look into it.

**Comment by yorinasub17** [comment]
Ok I repro'd the issue and have a fix in https://github.com/gruntwork-io/terratest/pull/563 . Note that this will now return the private DNS of the node.

**Comment by yorinasub17** [comment]
This should now be fixed in https://github.com/gruntwork-io/terratest/releases/tag/v0.28.7

**Comment by bartek-lopatka** [comment]
Thanks @yorinasub17  and @brikis98 !
