### ISSUE TITLE
gruntwork-io/terratest/modules/shell/command.go:161:84: undefined: io.StringWriter

### ISSUE THREAD

**Issue by thomasbeaumont** [gruntwork-io/terratest#561]
Hi developers! Not sure what is causing that one on my system but wanted to let you know

**Comment by yorinasub17** [comment]
Please check out https://github.com/gruntwork-io/terratest/issues/544, specifically https://github.com/gruntwork-io/terratest/issues/544#issuecomment-638838958 .

Closing as duplicate.
