### ISSUE TITLE
Question: How to specify the provider path for Terratest

### ISSUE THREAD

**Issue by virtualbubble** [gruntwork-io/terratest#565]
We do not have direct access to the internet to download the providers. Normally when we initialise Terraform we will use the following command:

`terraform.exe init -plugin-dir=".\plugins"`

Can we use TerraformOptions to specify a plugins directory that contains the required providers?

**Comment by yorinasub17** [comment]
We don't currently have a first class option exposed to set this, but I don't see why we can't.

With that said, as a workaround, I think you can use  [TF_CLI_ARGS](https://www.terraform.io/docs/commands/environment-variables.html#tf_cli_args-and-tf_cli_args_name), set in `EnvVars`.

**Comment by virtualbubble** [comment]
Thanks that worked for me.

**Comment by cbuto** [comment]
I ran into this same issue and figured it would be pretty straight forward to support it as a configuration option. 

I started on implementing it but i'm having a hard time figuring out the best way to implement a test that would be easy to maintain long term. Testing that the `-plugin-dir` option is actually working requires having pre-downloaded providers. I wrote a test that uses a fixture with a pre-downloaded provider but i don't think committing the actual provider binary to the repo is a viable solution.

Do you have any thoughts on how a test could be written for this @yorinasub17?
