### ISSUE TITLE
Feature Request: Packer/Terraform/Docker/Other? Minimum Version Checks

### ISSUE THREAD

**Issue by CpuID** [gruntwork-io/terratest#566]
Add helper functions for Packer/Terraform/Docker (and maybe others) to ensure a minimum version is installed for use on a system.

**Comment by brikis98** [comment]
That does seem like a reasonable feature to have. PR(s) welcome!

**Comment by yorinasub17** [comment]
This was implemented in https://github.com/gruntwork-io/terratest/releases/tag/v0.40.10
