### ISSUE TITLE
git.GetCurrentBranchName returns HEAD when on a release tag

### ISSUE THREAD

**Issue by yorinasub17** [gruntwork-io/terratest#574]
When you are running a build from a release tag, `git.GetCurrentBranchName` will return `HEAD` because you are not on a branch (detached state). This makes it difficult to run certain operations that depend on checking out the specific `ref`.

As a proposed remedy:

- `git.GetCurrentBranchName` should return `""` when we are not on a specific branch.
- Implement `git.GetCurrentGitRef` which will return the branch if on a branch (using `git.GetCurrentBranchName`), the underlying tag is not on a branch (`git.GetCurrentBranchName(t) == ""`), or the commit SHA if not on a tag.

**Comment by colens3** [comment]
Hi @yorinasub17 ,
I would like to contribute to this one if it's still relevant? :)

Question:
- For `git.GetCurrentBranchName` you had in mind to add just "Head" string comparison, or something else?

**Comment by yorinasub17** [comment]
That would be great @colens3 !

> For git.GetCurrentBranchName you had in mind to add just "Head" string comparison, or something else?

Yup that is exactly what I had in mind.
