### ISSUE TITLE
ssh using bastion

### ISSUE THREAD

**Issue by gadelkareem** [gruntwork-io/terratest#582]
Anyway to SSH using a bastion instance?

**Comment by yorinasub17** [comment]
You should be able to use the [ssh.CheckPrivateSshConnection](https://pkg.go.dev/github.com/gruntwork-io/terratest@v0.28.12/modules/ssh?tab=doc#CheckPrivateSshConnection) function for this.

**Comment by gadelkareem** [comment]
I used that but how can I use that ssh session to ssh into another instance?
```
publicHost := ssh.Host{
		Hostname:    publicInstanceIP,
		SshKeyPair:  &ssh.KeyPair{PrivateKey: keypairPrivKey},
		SshUserName: "ec2-user",
	}

privateHost := ssh.Host{
		Hostname:    privateInstanceIP,
		SshKeyPair:  &ssh.KeyPair{PrivateKey: keypairPrivKey},
		SshUserName: "ec2-user",
                 SshTunnelHost: publicHost, // <--- something like this
	}
```

**Comment by yorinasub17** [comment]
This is doing exactly that. That is, the private host is already jumped from the public host.

**Comment by gadelkareem** [comment]
got it thanks!
