### ISSUE TITLE
Terratest multiple targets

### ISSUE THREAD

**Issue by ahmedfourti** [gruntwork-io/terratest#598]
Hello,

I managed to run multiple target in my tests but noticed that at the end of tests, only the last target is destroyed, I can't find a way to destroy all modules.

I asked for help in stackoverflow but no answer, can this be done through terratest or should I implement some code to do it ?

Here is my code :

https://stackoverflow.com/questions/63775990/terratest-multiple-targets

Thanks for your help guys

**Comment by brikis98** [comment]
Answered on StackOverflow. Let's continue the discussion there: https://stackoverflow.com/a/63807269/483528
