### ISSUE TITLE
Add Azure Disk Module

### ISSUE THREAD

**Issue by davidkpiano** [gruntwork-io/terratest#614]
**Purpose:** Expanding Terratest coverage for [Azure Disk Storage](https://azure.microsoft.com/en-us/services/storage/disks/)

**Comment by HadwaAbdelhalem** [comment]
@brikis98  would you please close this issue, PR was merged

**Comment by HadwaAbdelhalem** [comment]
@brikis98  would you please close this issue, PR was merged

**Comment by yorinasub17** [comment]
Thanks! Closing.
