### ISSUE TITLE
Include Tags in GetEcsCluster

### ISSUE THREAD

**Issue by particleflux** [gruntwork-io/terratest#643]
Is there a specific reason why tags are not returned in the `GetEcsCluster` method?

So far as I can see it would only require a little change to the SDK input:
https://github.com/gruntwork-io/terratest/blob/c5ca9ef8e4e66f723e40c8b4cab06f82310618cd/modules/aws/ecs.go#L25-L29

Adding the `TAGS` value to the `Include` field should do the trick.

ref: https://docs.aws.amazon.com/sdk-for-go/api/service/ecs/#DescribeClustersInput

**Comment by brikis98** [comment]
We probably weren't using it before in the tests. It might be worth adding, though it probably does change the IAM permissions you'll need to call that method. Perhaps add a new method that takes in the list of `Include` fields?

**Comment by particleflux** [comment]
Might have a look into that when I got time. Any preferences for a method name there?

Like, `GetEcsClusterWithInclude` ?

**Comment by brikis98** [comment]
Great, thanks! That name seems reasonable.
