### ISSUE TITLE
terraform_azure_example_test.go does not set prefix before executing test

### ISSUE THREAD

**Issue by rguthriemsft** [gruntwork-io/terratest#646]
While running multiple CIs in parallel we discovered that this test was breaking CI because it is not randomizing resource names.  I also found that the terraform example does not follow other examples for resource randomization.  This issue is to put in a fix to unblock CI and I will also open a second issue to fix the terraform and then update the test.  

Area of test that is not setting prefix correctly.
https://github.com/gruntwork-io/terratest/blob/c5ca9ef8e4e66f723e40c8b4cab06f82310618cd/test/azure/terraform_azure_example_test.go#L21

**Comment by rguthriemsft** [comment]
Issue to fix naming in the example #648

**Comment by HadwaAbdelhalem** [comment]
@brikis98 , would you please close this issue. Fix PR was merged

**Comment by yorinasub17** [comment]
Thanks! Closing.
