### ISSUE TITLE
terraform-azure-example uses inconsistent naming convention for resources

### ISSUE THREAD

**Issue by rguthriemsft** [gruntwork-io/terratest#648]
The terraform-azure-example does not follow other examples for naming convention.  Here is an example 

name     = "${var.prefix}-resources"

should be

name.    = var.resource_group_name

with a corresponding entry in variables.tf so that it can be overridden with a unique name in test as all other examples follow.

**Comment by lekansogunle** [comment]
A possible solution will be to add a resource_group_name variable to variables.tf and default it to be `"${var.prefix}-resources"` . Will this suffice and also be required for other examples like ` terraform-azure-network-example` where a postfix is being used instead? @brikis98 @rguthriemsft

**Comment by HadwaAbdelhalem** [comment]
@brikis98 , would you please close this issue. It was fixed

**Comment by yorinasub17** [comment]
Thanks! Closing.
