### ISSUE TITLE
Add a dns-helper module

### ISSUE THREAD

**Issue by askainet** [gruntwork-io/terratest#660]
I'm struggling to write reliable tests for k8s deployments with public ingresses, i.e. http retry requests to public DNS hostnames asynchronously created by external-dns for ingresses in those deployments:

1. Install helm chart for a web application, including an ingress resource with a custom public DNS name.
2. Wait until ingress is ready and get its public DNS name.
2.1. Eventually, some tool in k8s like external-dns creates a public DNS record pointing to the ingress. **Terratest doesn't provide a reliable way to wait for this yet.**
3. Start retrying http requests to public DNS name...

If the DNS record has not been created/updated yet when the first http request is sent, chances are the system where the test runs caches the negative/old reply for a very long time (some systems behave worse than others, not even honoring original TTL set by authoritative nameservers), and the test will most likely fail.

To avoid being affected by this local DNS cache issues, a dns-helper module could provide a way of waiting until the authoritative nameservers for the domain reply as expected to the DNS record.

**Comment by yorinasub17** [comment]
This was released in https://github.com/gruntwork-io/terratest/releases/tag/v0.30.14
