### ISSUE TITLE
Terratest aws | undefined: "testing".TestingT

### ISSUE THREAD

**Issue by almezquita12** [gruntwork-io/terratest#662]
When running my module.go i have the following error:

```
$ go test -run kms.go
kms.go
.\kms.go:8:2: imported and not used: "github.com/gruntwork-io/terratest/modules/aws" as terraaws
.\kms.go:25:18: undefined: "testing".TestingT
.\kms.go:35:19: undefined: "testing".TestingT
.\kms.go:53:21: undefined: "testing".TestingT
.\kms.go:62:22: undefined: "testing".TestingT
.\kms.go:63:15: undefined: NewAuthenticatedSession
```
[test.zip](https://github.com/gruntwork-io/terratest/files/5306211/test.zip)

I can't find any NewAuthenticatedSession and the terratest aws package that fixes this ...

thanks

**Comment by yorinasub17** [comment]
Closing as we are already discussing this in https://github.com/gruntwork-io/terratest/issues/659. Will continue the conversation there.
