### ISSUE TITLE
managing dependency of modules while using terratest

### ISSUE THREAD

**Issue by rishabhanand26** [gruntwork-io/terratest#695]
I am working on  2 modules, one module that creates vpc works fine, while the other module is dependent on the output of the vpc module, how can i manage to have the outputs of the vpc module to be used as input for the other like its being used in terraform. can someone please help?

**Comment by brikis98** [comment]
There are multiple ways to handle this, but probably the most common would be:

1. Create a `opts1 := terraform.Options` instance that points to the first module.
1. Run `terraform.Apply(t, opts1)` to deploy the first module.
1. Use `terraform.Output(t, opts1, "<OUTPUT>")` to read each output you need from the first module.
1. Create a `opts2 := terraform.Options` instance that points to the second module, setting variables using the `Vars` field of `terraform.Options` with the outputs you read from the first module.
1. Run `terraform.Apply(t, opts2)` to deploy the second module.

```hcl
opts1 := &terraform.Options {
  TerraformDir: "../path-to-first-module",
}

defer terraform.Destroy(t, opts1)
terraform.InitAndApply(t, opts1)

output1 := terraform.Output(t, opts1, "output1")
output2 := terraform.Output(t, opts1, "output2")

opts2 := &terraform.Options {
  TerraformDir: "../path-to-second-module",
  Vars: map[string]interface{}{
    "var1": output1,
    "var2": output2,
  },
}

defer terraform.Destroy(t, opts2)
terraform.InitAndApply(t, opts2)
```

**Comment by rishabhanand26** [comment]
Hi Thanks, it worked. Thank you for the help :)

**Comment by brikis98** [comment]
Great to hear!
