### ISSUE TITLE
Support for `OutputMaxLineSize`

### ISSUE THREAD

**Issue by bwhaley** [gruntwork-io/terratest#707]
Terratest used to support an `OutputMaxLineSize` option. It looks like support for this was removed in [this commit](https://github.com/gruntwork-io/terratest/commit/2284ed00a07d256710b2aafb3a0b341c79d81235), but then [the struct field in `modules/terraform/options.go`](https://github.com/gruntwork-io/terratest/blob/master/modules/terraform/options.go#L63) snuck back in at some point even though the functionality isn't present.

Would it make sense to add support for a max line length back in? The reason I'm asking is related to the new [plan testing feature](https://github.com/gruntwork-io/terratest/pull/694). I've found that for very large plans with hundreds of resources, the `show` command prints the JSON plan in output, which gets to be very, very long. It would be nice to have an option to limit the line length or at least chop off the plan output to the screen.

**Comment by yorinasub17** [comment]
The `OutputMaxLineSize` was used for a different reason (to set a limit for the writer buffer) and not necessarily to chop off output.

I think an alternative feature is to have an option in `TerraformOptions` (or the `Show` function) to silence the output and prevent it from showing up in the logs.

**Comment by bwhaley** [comment]
I worked around this by setting the logger to discard.

```
terraformOptions.Logger = logger.Discard
defer func() { terraformOptions.Logger = nil }
```
