### ISSUE TITLE
Issue with OutputMapOfObjects with Azure

### ISSUE THREAD

**Issue by dumiller-sourced** [gruntwork-io/terratest#709]
We encountered this issue a little while and have been tracking it in our internal documentation, here is our breakdown of the issue:

=====

We have ran into issues with the Terratest framework where it will fail if you try and fetch a Terraform output containing a list of scalar values (as opposed to a list of objects). Here is a summary.

Terraform does support the output of (and iteration of if you're looking for a good way to handle dependent loops) entire Terraform objects. This is useful if you want to get all of the properties of an object at once without having to use multiple output blocks. This works really well on flat objects without embedded child objects or sub configurations, but there is some "weirdness" around the way Terratest and/or Terraform formats outputs

output "example_output" {
value = azurerm_virtual_network.example_vnet
}

Ideally, you want to use the OutputMapOfObjects Terratest function to grab your example outputs from state. The issue we discovered yesterday is that not all objects support this. As an example Policy Definitions, Policy Set Definitions and Resource Groups support it, Policy Assignments and Virtual Networks do not support it. We're unsure if this down to the way Terratest reads and formats these objects or the way Terraform formats the output, but you'll know right away if the object you're trying to output doesn't support OutputMapOfObjects when you run your test. If the object does NOT support OutputMapOfObjects you'll have to use OutputMap which gives you all the same data, but as a map of strings rather then a map of objects. This means you'll have to do some parsing if you want to make it work in the same way.

Once you Output your map of objects it still doesn't just "work", you'll still need to do some casting. This example is from my Public IP Initiative tests: 

assert.Equal(t, policyDefinitionList["Deny-PublicIP"].(map[string]interface{})["id"].(string), "/providers/Microsoft.Management/managementgroups/test_management_group_"+postfix+"/providers/Microsoft.Authorization/policyDefinitions/"+policyDefinitionList["Deny-PublicIP"].(map[string]interface{})["display_name"].(string))

Here, you're grabbing the object called Deny-PublicIP from the map, but in order to grab the parameter id you need to first cast it to an interface and then cast the value of that interface to a string policyDefinitionList["Deny-PublicIP"].(map[string]interface{})["id"].(string). Further on in this line it grabs a different parameter from the same object display_name using the same method.

We have narrowed down the issue to this line https://github.com/gruntwork-io/terratest/blob/0c883d74782fecaf8e5987a760f5aa9e06a04a7f/modules/terraform/output.go#L103 basically if Terratest sees a list when parsing TF outputs it tries to parse it as a list of maps and doesn’t check if values in the list are scalars like string or integers.

Possible solution(s):
Implement a fix by extending the parseMaps function to check if list is a list of scalars first and then parsing it as such before attempting to parse it as a list of maps.

**Comment by brikis98** [comment]
Most of the `Output<TYPE>` methods in Terratest are relatively limited in the degree of nesting they support. If you have a complicated structure you need to read, give `OutputStruct` a shot!

**Comment by infraredgirl** [comment]
Closing this as the solution was provided, but @dumiller-sourced  feel free to reopen if using `OutputStruct` didn't solve your issue!
