### ISSUE TITLE
TF 0.14.0 String Output leaves double quotes

### ISSUE THREAD

**Issue by dee-kryvenko** [gruntwork-io/terratest#717]
Using `v0.30.27`. Having a simple tf `v0.14.0` code:

```
output "hello_world" {
  value = "Hello, World!"
}
```

Trying to:

```
output := terraform.Output(t, terraformOptions, "hello_world")
assert.Equal(t, "Hello, World!", output)
```

Fails with:

```
                Error:          Not equal: 
                                expected: "Hello, World!"
                                actual  : "\"Hello, World!\""
                            
                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -1 +1 @@
                                -Hello, World!
                                +"Hello, World!"
```

**Comment by brikis98** [comment]
Ah, bummer, Terraform 0.14 changed its output format.

For:

```hcl
output "foo" {
  value = "Hello, World"
}
```

With Terraform 0.13:

```
$ terraform output foo
Hello, World
```

And with Terraform 0.14:

```
$ terraform output foo
"Hello, World"
```

I don't see that in their release notes, but that seems like a significant API change...

**Comment by brikis98** [comment]
I filed https://github.com/hashicorp/terraform/issues/27100 to see if this change was intentional or not...

**Comment by dee-kryvenko** [comment]
@brikis98 seems like they confirmed the change was intentional. Here's a proposed fix: https://github.com/gruntwork-io/terratest/pull/718

**Comment by wylie-ucb** [comment]
I know I'm a little late to the party here, is there a recommended resolution for this?  I'm seeing this after upgrading to TF14, using 0.14.10.  Thanks so much.
