### ISSUE TITLE
Question to validate tags on all resources.

### ISSUE THREAD

**Issue by jarnohenneman** [gruntwork-io/terratest#734]
Hello,

I'm wondering if Terratest is the right path to go on if we want to check if all our AWS Terraform resources have tags.
Or would you recommend another solution for this?

We would like to know it before we deploy our resources, and avoid using AWS Config rules for it.

**Comment by yorinasub17** [comment]
This depends on what you want to accomplish. You can certainly write terratest tests that validate a given terraform module has tags. To accomplish tag checks, you would run a plan test (see [this example](https://github.com/gruntwork-io/terratest/blob/master/test/terraform_aws_example_plan_test.go)), and validate the plan contains the tags using something like [openpolicyagent](https://www.openpolicyagent.org/).

But this is only as good as the test you write. E.g., it won't be a useful test to have a policy that checks if the resource `resource "aws_instance" "some_pet_resource"` has tags configured, as writing that test would basically be the same as adding `tags` attribute to the `aws_instance` test.

So the test you probably want to write is something that has a list of resource types it wants to enforce the check on, and then validate that for all resources that match that type, a tag is in place.

Note that there is also [conftest](https://github.com/open-policy-agent/conftest), which allows you to write OPA rules directly against the HCL code, which would lead to much lighterweight tests as they are doing static analysis and don't require a plan.

**Comment by jarnohenneman** [comment]
Thank you for the advice @yorinasub17. Will do some reading up on these topics you shared, much appreciated!

**Comment by akhan4u** [comment]
Hey @jarnohenneman, Were you able to get something out of `conftest`. I am working on a similar problem statement to check for a particular tag type on all resources provisioned with terraform, more on a shift-left approach. If you can give me some pointers, that would be really helpful.
