### ISSUE TITLE
How can i load my AWS EC2 Key pair PEM file to my GoLang terratest script to perform AWS EC2 SSH connection validation

### ISSUE THREAD

**Issue by pandubiet** [gruntwork-io/terratest#735]
I am writing GoLang terratest script to validate SSH connection for AWS EC2 instance

I already have AWS EC2 keypair PEM file in my local

I am able to launch and destroy EC2 instance using terraform.TgApplyAll() and terraform.TgDestroyAll() methods and fetch the output variables using terraform.Output() method

My local AWS EC2 keypair PEM file is used for creating EC2 instance in AWS

Now I am trying to **validate EC2 SSH connection** Programmatically from **terratest GoLang** script

I am NOT able to load my local AWS EC2 Key pair to sshKeyPair variable in GoLang terratest script

I used below code snippet but no use because i have PEM file but below code tried to read JSON

https://github.com/gruntwork-io/module-asg/blob/067647b3aaeb24151badbc5a2d9a6b5381dd2041/test/server_group_test.go#L78

I also tried script present in at 
https://github.com/gruntwork-io/terratest/blob/907c09f0696083a5ada580debb66bb5c00c19c32/modules/test-structure/save_test_data.go#L66 to load my local EC2 key pair using LoadEc2KeyPair and test EC2 SSH using fmt.Sprintf("SSH to public host %s", publicIP) But getting **error** while reading EC2 keypair from local in LoadTestData(t testing.TestingT, path string, value interface{}) method at json.Unmarshal(bytes, value) built in call

_Error message : Failed to parse JSON for value D:\AWS\KeyPair\pandukeypair.pem: invalid character '-' in numeric literal I am getting this error as i am trying to ream .pem file and code is trying to do json.umarshal on the .pem file_

All code snippets available in github/terratest modules talks about creating **new keypair and loading AWS EC2 JSON keypair** as but i am **NOT** getting any approach/Logic for my scenario where already **existing keypair PEM** is present i just want to load and use it for SSH EC2 validation

Could anyone help me on this ?

**Comment by brikis98** [comment]
`test_structure.LoadEc2KeyPair` is used to read an EC2 Keypair from disc that had previously been stored using `test_structure.SaveEc2KeyPair`. The code in `test_structure` is specifically for working with Terratest "test stages" ([see here for more details](https://terratest.gruntwork.io/docs/testing-best-practices/iterating-locally-using-test-stages/)) and _not_ general-purpose code for working with Key Pairs the way you're thinking.

I assume your goal is to use something like [`ssh.CheckSshCommand`](https://github.com/gruntwork-io/terratest/blob/master/modules/ssh/ssh.go#L203), right? If so, that method is typically used with a KeyPair generated at test time via [`GenerateRSAKeyPair`](https://github.com/gruntwork-io/terratest/blob/master/modules/ssh/key_pair.go#L30) and/or [`CreateAndImportKeyPair`](https://github.com/gruntwork-io/terratest/blob/master/modules/aws/keypair.go#L19). That said, if for some reason, you want to test with an EC2 KeyPair you already created outside the test, you'll have to read it from disk yourself, and store the public and private key for it in a [`KeyPair` struct](https://github.com/gruntwork-io/terratest/blob/master/modules/ssh/key_pair.go#L15-L18). You can then use that `KeyPair` in a [`Host` struct](https://github.com/gruntwork-io/terratest/blob/master/modules/ssh/ssh.go#L29) you pass to the `ssh.CheckSshCommand` method.

**Comment by pandubiet** [comment]
Thanks for all your response

I could able to achieve this by using below Code snippet which is provided from Yori

`
GenerateRSAKeyPairE:
func RSAKeyPairFromFile(fpath string) (*terrassh.KeyPair, error) {
    // import crypto/x509
    // import io/ioutil
    // import encoding/pem
    // import "golang.org/x/crypto/ssh"
    // terrassh "github.com/gruntwork-io/terratest/modules/ssh"

    pemBytes, err := ioutil.ReadFile(fpath)
    if err != nil {
        return nil, err
    }
    pemBlock, _ := pem.Decode(pemBytes)
    if pemBlock == nil {
        return nil, fmt.Errorf("failed to decode PEM block containing private key")
    }
    privKey, err := x509.ParsePKCS1PrivateKey(pemBlock.Bytes)
    if err != nil {
        return nil, err
    }
    sshPubKey, err := ssh.NewPublicKey(privKey.Public())
    if err != nil {
        return nil, err
    }
    sshPubKeyBytes := ssh.MarshalAuthorizedKey(sshPubKey)
    sshPubKeyStr := string(sshPubKeyBytes)
    return &terrassh.KeyPair{PublicKey: sshPubKeyStr, PrivateKey: string(pemBytes)}, nil
}




`

**Comment by pu3hp** [comment]
What all libraries are needed to import for this new RSA public key generation ?
