### ISSUE TITLE
azure module

### ISSUE THREAD

**Issue by dereksharman** [gruntwork-io/terratest#736]
func GetVirtualMachineTagsE(vmName string, resGroupName string, subscriptionID string) (map[string]string, error) {

map has not been properly intialized

func GetVirtualMachineTagsE(vmName string, resGroupName string, subscriptionID string) (map[string]string, error) {
	// Setup a blank map to populate and return
	**var tags map[string]string**

	// Get VM Object
	vm, err := GetVirtualMachineE(vmName, resGroupName, subscriptionID)
	if err != nil {
		return nil, err
	}

	// Range through existing tags and populate above map accordingly
	for k, v := range vm.Tags {
		tags[k] = *v
	}

	return tags, nil
}

**Comment by rguthriemsft** [comment]
@davesee Please take a look.  We will get this fixed.
