### ISSUE TITLE
test_structure.CopyTerraformFolderToTemp - verify terraformModuleFolder exists

### ISSUE THREAD

**Issue by cbuto** [gruntwork-io/terratest#738]
test_structure.CopyTerraformFolderToTemp doesn't currently validate that directories passed into the function exist.

If the terraformModuleFolder directory that is passed into `test_structure.CopyTerraformFolderToTemp` doesn't exist, the failure is handled during the `terraform init` (i.e `Error: No configuration files`).

It might be better to fail earlier if the directory doesn't exist and report a detailed error message to make debugging easier.

Let me know if this seems like a good idea and I can attempt to whip up PR one of these days!

**Comment by brikis98** [comment]
Ah, yea, checking that both folders exist and showing a clear error message if they don't is a good idea. A PR to add that would be great, thanks!
