### ISSUE TITLE
Support for CosmosDb on Azure

### ISSUE THREAD

**Issue by rguthriemsft** [gruntwork-io/terratest#741]
Adding an issue for PR submitted by @tomconte

**From Pull Request** 
I am proposing this CosmosDB module and example I wrote for using on a project I am working on, where we needed to assert certain Cosmos properties after deployment. I tried to follow the model of other Azure module contributions.

Link to Pull Request
#740

**Comment by HadwaAbdelhalem** [comment]
@yorinasub17 would you please close this issue, PR was merged

**Comment by yorinasub17** [comment]
Thanks! Closing.
