### ISSUE TITLE
ec2.InstanceTypeOffering struct not found in aws modules

### ISSUE THREAD

**Issue by git4raj** [gruntwork-io/terratest#750]
Hi,

I pulled the terratest code along with the modules. In the AWS ec2.go, there is a reference to ec2.InstanceTypeOffering in multiple functions. When I try to run the go code for Terratest, it complains, cannot find this type. I searched all over, I'm not able to find this definition.

`func pickRecommendedInstanceTypeE(availabilityZones []string, instanceTypeOfferings []*ec2.InstanceTypeOffering, instanceTypeOptions []string) (string, error) {
Any pointers would be helpful.
`
Thank you
Raj

**Comment by yorinasub17** [comment]
I think I might know what is going on here, but need more info to be sure:

- Is this your module code, or are you trying to run the tests in the terratest repo?
- If it is your own module, which version of terratest do you currently have?
- Which version of golang are you using?
- Depending on the version, are you using vendored modules (where there is a `vendor` folder) or go modules?
- If the former, what version of AWS SDK Go do you have in your `vendor` folder?

**Comment by git4raj** [comment]
This is my own module.  I used Terratest a year ago when there were installation instructions. I did a go get and got the terratest. when i was attempting to do it now to update, there were no go modules, it was not updating individual modules (the options.go file was missing the Varfiles in the struct), when i tried to get them. so I ended up doing a git clone (of the latest as of 12/21) and copied the files to my GOPATH\Src folder (\github.com\gruntwork-io). I can't find the version of terratest or aws go sdk. 

My go version is 1.15.6.

I want to test  certain features of AWS elasticsearch, it is not available in terratest.
Thus, I use a Terratest and then a library where i use aws go sdk to establish connection to the resource, get properties, interrogate and test the features. 

When I attempt to do that, the test is complaining that this is missing in ec2.go file. i ended up commenting the block as i don't use ec2 now. But, would like to resolve this.

Thank you

**Comment by yorinasub17** [comment]
Ah gotcha! Thanks for the clarification!

See if the following works:

1. Create a new folder. This can be anywhere and does not have to be in your GOPATH. This will serve as the basis for your module tests.
2. In the folder, run `go mod init github.com/YOUR_ORG/YOUR_MODULE_REPO`. This will initialize go modules system.
3. Copy paste https://github.com/gruntwork-io/terratest/blob/master/test/terraform_basic_example_test.go. This is just to initialize, and you will need to modify this to fit your needs.
4. Run `go mod tidy`. This will update `go.mod` and create `go.sum` with the proper versions of the dependencies that are needed.
5. See if the code compiles by running `go test -v -run TestFoo .`. If there are no errors, then you can start to modify the test file to fit your needs.

**Comment by git4raj** [comment]
Thanks a lot for your quick response. Currently, I have multiple TF modules and there is a test folder nested inside that and the _test.go files are inside that test folder. I run the "go test -v _test.go libtest.go"  in the terminal window at the "test" folder level.

For eg:
TF Module 1
*.tf
test
    *_test.go

TF Module 2
*.tf
test
    *_test.go

This "new folder", I'm creating is that just to get all dependencies and a one time or do I need to do this in each of the "test" folders inside the module?

**Comment by git4raj** [comment]
This is what I ended up doing, that worked for me.
Creating a new folder and running mod init didn't help. I went to my test folder and ran
go mod tidy
This pulled all the dependencies (earlier - a year ago, I used dep init & dep ensure. looks like now it is mod init and mod tidy). 
The new website for terratest is looking good but I think, having a section on "How to Install" and laying these things out would be helpful. Earlier, it used to pull the files while running or we could go and do " go get..." it will get them, not sure what is the advantage of not having that work?

Thank you for you help. Appreciate it.
Best
Raj

**Comment by git4raj** [comment]
I would love to contribute these changes as these are not available in Terratest.

**Comment by yorinasub17** [comment]
> Earlier, it used to pull the files while running or we could go and do " go get..." it will get them, not sure what is the advantage of not having that work?

This will still work, but only if you are in go modules mode. The rules for when go modules get triggered is murky, but it is:

- The source package is outside the GOPATH and has a `go.mod` file.
- The source package is inside the GOPATH, has a `go.mod` file, and the env var `GO111MODULE` is not `off`.
- The source package is inside the GOPATH and the env var `GO111MODULE` is set to `on`.

> The new website for terratest is looking good but I think, having a section on "How to Install" and laying these things out would be helpful.

The steps I mentioned are actually in [the Quick Start section](https://terratest.gruntwork.io/docs/getting-started/quick-start/). That said, we all have the curse of knowledge here having used terratest extensively for a good amount of time, so getting some feedback / contributions to improve the docs for newcomers is welcome!

**Comment by infraredgirl** [comment]
Looks like the issue has been resolved, so I'll close this ticket. Having said that, any PRs with contributions to terratest (docs or otherwise) are always highly appreciated. We'll be happy to review your PR @git4raj if you feel like submitting one!
