### ISSUE TITLE
Replace multierror implementation with go-multierror

### ISSUE THREAD

**Issue by infraredgirl** [gruntwork-io/terratest#751]
Terratest currently implements its own [multierror package](https://github.com/gruntwork-io/terratest/blob/master/modules/customerrors/multierror.go). We should scrap this and use [go-multierror](https://github.com/hashicorp/go-multierror) instead.

**Comment by urohit011** [comment]
I would like to take it up.

**Comment by infraredgirl** [comment]
Excellent, thanks Rohit! I just assigned the issue to you.
