### ISSUE TITLE
Terraform 0.14.3 breaks Terraform Output Handling

### ISSUE THREAD

**Issue by MatthiasScholz** [gruntwork-io/terratest#766]
# Summary

With terraform 0.14.3 using `terraform.Output` functionality contains quotations marks and hence breaks output usage.

# Investigation

With the release of terraform [0.14.3](https://github.com/hashicorp/terraform/releases/tag/v0.14.3) a new output flag was introduced: `-raw`
which leads to the introduction of quotation marks for none raw output, e.g.
`"tf-asg-2021012119532247190000000d"` instead of `tf-asg-2021012119532247190000000d`.

This breaks the usage of:
https://github.com/gruntwork-io/terratest/blob/0c883d74782fecaf8e5987a760f5aa9e06a04a7f/modules/terraform/output.go#L24

# Proposed Solutions

1. Adapt to reflect the latest changes:
For terraform version >= 0.14.3:
`output, err := RunTerraformCommandAndGetStdoutE(t, options, "output", "-raw", "-no-color", key)`
below keep the current implementation.
2. Provide additional functionality and redirect version handling to the user.

# Relation

- https://github.com/hashicorp/terraform-aws-nomad/issues/84
   - https://github.com/hashicorp/terraform-aws-nomad/pull/85

**Comment by brikis98** [comment]
What version of Terratest are you using? We fixed issues related to `output` in https://github.com/gruntwork-io/terratest/releases/tag/v0.31.0.

**Comment by MatthiasScholz** [comment]
The version defined here:
- https://github.com/hashicorp/terraform-aws-nomad/blob/10c23820707e0ef7eef9ea24f59dc67ef7046e45/test/go.mod#L5
  - -> `v0.30.11`

I can confirm, using version `v.0.31.0` or above solves the issue.
