### ISSUE TITLE
How to Skip specific .tf files in root directory during terratest.

### ISSUE THREAD

**Issue by ranopriyo-neogy** [gruntwork-io/terratest#791]
I have a terraform template calling different modules. I want to skip certain .tf files while testing using terratest. What are my options to achieve it.  Any script/ code i need to add in my .go file below to skip a .tf file or make it optional ? 

```
package test

import (
	"fmt"
	"testing"

	"github.com/gruntwork-io/terratest/modules/random"
	"github.com/gruntwork-io/terratest/modules/terraform"

)

func TestTemplate(t *testing.T) {
	t.Parallel()
	env_id := fmt.Sprintf("%s", random.UniqueId())
	account_id := "1234"
	customer_name := "BitBucketCI"
	db_skip_final_snapshot := true
	private_dns_domain := "test.internal"
	public_dns_domain := "test.com"

	terraformOptions := &terraform.Options{
		TerraformDir: "../",

		Vars: map[string]interface{}{
			"env_id":                 env_id,
			"account_id":             account_id,
			"customer_name":          customer_name,
			"db_skip_final_snapshot": db_skip_final_snapshot,
			"private_dns_domain":     private_dns_domain,
			"public_dns_domain":      public_dns_domain,


		},
	}

	defer terraform.Destroy(t, terraformOptions)
	terraform.InitAndApply(t, terraformOptions)
}

```

**Comment by brikis98** [comment]
What do you mean skip a `.tf` file? You mean you have some folder `foo`, with, say, `bar.tf` and `baz.tf`, and you want Terraform to ignore `baz.tf` during a test? If so, why? Could you provide some more context?

**Comment by ranopriyo-neogy** [comment]
@brikis98  yes that is correct. I want to skip one/ multiple .tf files during terratest execution. How shall i achieve it.

**Comment by brikis98** [comment]
Why? This is not a normal way to use Terraform, so Terratest doesn't support it. You can of course move/delete files with Go code yourself. But perhaps there are better ways to achieve what you want, so some context would help.

**Comment by ranopriyo-neogy** [comment]
In one terraform file there are hardcoded IPs for customer_gateway. When multiple PR are raised simultaneously the file conflicts as the test account (during terratest execution) is same for all Pull Requests . This is because Terratest creates and destroy the infrastructure using the hardcoded IPs at the same time another PR is using the same IPs - this causes conflict. I know this can be achieved my moving the `.tf` file to /optional or /off  from root folder , something i used to resolve this issue.

I was checking if there are feature in terratest to skip this file directly to prevent such conflicts as / when raised. If there is no support for this at present, I would suggest to consider it as a feature request , since it will be completely optional to someone who wants to use it.

**Comment by brikis98** [comment]
I think the Terraform native way of doing this is:

- Instead of hard-coded IPs, read the IPs from a variable. 
- Make the `default` for the variable the hard-coded IPs.
- At test time, set the variable to a test-friendly value.

Ignoring `.tf` files in a folder is _not_ idiomatic to Terraform—in fact, it will likely lead to errors, for if you delete some set of params in one file that are referenced in another, that reference will be broken—so I don't think this is something we should support in Terratest either.
