### ISSUE TITLE
Feature Request: Helper functions for Kubernetes ReplicaSets

### ISSUE THREAD

**Issue by cbuto** [gruntwork-io/terratest#793]
I'm not sure if this would pass the litmus tests defined in the contributor guide but I think it might be something worthwhile supporting in Terratest in terms of popularity/completeness.

We have tests implemented currently that rely on the outcome of creating deployments and assertions based on the associated ReplicaSet events. 

This would look much the daemonset implementation.

Let me know if this is something that sounds reasonable!

P.S Terratest has significantly improved our existing testing strategy, so I really appreciate this project and support from the maintainers!

**Comment by brikis98** [comment]
Makes sense to me and I think a PR would make sense. @yorinasub17 Any objections?
