### ISSUE TITLE
FeatureRequest: Use AWS SSM client to send multiple commands

### ISSUE THREAD

**Issue by b-m-f** [gruntwork-io/terratest#797]
# What I would like to do:

- create client with https://github.com/gruntwork-io/terratest/blob/master/modules/aws/ssm.go#L89
- Send multiple Commands via the same client

# Why?
https://github.com/gruntwork-io/terratest/blob/master/modules/aws/ssm.go#L138 always creates a new client.

Since the output is truncated I currently have to split up some workloads and execute them in sequence. Every time a new client is created the connection has to be established and waited for.

Reusing the same client will drasitacally improve the speed.

# Implementation Idea

New function `executeCommand(t testing.TestingT, client *ssm.SSM, command string)  (*CommandOutput, error)` .

This can then be used in a loop without reestablishing the connection every time.

I could send a PR if this is something you guys/gals would like to include into the SSM module.

**Comment by brikis98** [comment]
This makes sense. A PR is welcome, thank you!

**Comment by danquack** [comment]
Believe this issue can probably be closed now with #924

**Comment by brikis98** [comment]
Good point. Closing now as this was fixed in #924.
