### ISSUE TITLE
FeatureRequest:  Allow InvocationType argument to InvokeFunction()

### ISSUE THREAD

**Issue by kbalk** [gruntwork-io/terratest#802]
## What I would like to do:
Add an argument to `InvokeFunction()` that can be used as the InvocationType argument to AWS SDK's `Invoke()`.

From the AWS CLI command reference (https://docs.aws.amazon.com/cli/latest/reference/lambda/invoke.html):

> invoke
> --function-name <value>
> [--invocation-type <value>]    <-----
> [--log-type <value>]
> [--client-context <value>]
> [--payload <value>]
> [--qualifier <value>]
> \<outfile\>

https://github.com/gruntwork-io/terratest/blob/8361e81e718c421388f76021603746485c972f30/modules/aws/lambda.go#L13    

## Why?

An InvocationType argument of "DryRun" provides a simple verification of a Lambda's installation.  It's also useful where it's difficult to generate the appropriate payload to test a lambda's invocation.

**Comment by brikis98** [comment]
PR to add this, perhaps in a new function, is welcome!

**Comment by brikis98** [comment]
Fixed in #817 and released in https://github.com/gruntwork-io/terratest/releases/tag/v0.32.21.
