### ISSUE TITLE
Support resolving base URIs for existing Azure modules

### ISSUE THREAD

**Issue by davidkpiano** [gruntwork-io/terratest#811]
Placeholder issue for the ongoing work for supporting different clouds (e.g., sovereign cloud) resolved via `baseURI`:

- [x] Action Group (@davidkpiano)
- [x] AKS (@davidkpiano) 
- [x] Availability Set (@davidkpiano)
- [x] Compute (@davidkpiano)
- [x] Cosmos DB (@davidkpiano)
- [x] Disk (@davidkpiano)
- [x] Key Vault (@shahedc)
- [x] Load Balancer (@mjyeaney)
- [x] Log Analytics (@davidkpiano)
- [x] Monitor (@davidkpiano) 
- [x] MySQL (@davidkpiano)
- [x] Network Interface (@mjyeaney)
- [x] NSG (@mjyeaney)
- [x] Public IP Address (@mjyeaney)
- [x] Resource Group (@davidkpiano)
- [x] SQL (@davidkpiano)
- [x] Storage (@davidkpiano)
- [x] Virtual Network (@davesee)

**Comment by yorinasub17** [comment]
Quick question: is it possible to keep the `Get...Client` name for now to avoid backwards incompatibility? And then at a later time once all the modules are updated, we have one PR + release that renames them to `Create...Client`?

Otherwise, we can't incrementally merge the changes without avoiding a backwards incompatible version bump each time.

**Comment by davidkpiano** [comment]
> Quick question: is it possible to keep the `Get...Client` name for now to avoid backwards incompatibility? And then at a later time once all the modules are updated, we have one PR + release that renames them to `Create...Client`?
> 
> Otherwise, we can't incrementally merge the changes without avoiding a backwards incompatible version bump each time.

Good call; I'l make that change.

**Comment by HadwaAbdelhalem** [comment]
@yorinasub17  would you please close it as all realted PR are either merged or closed.
