### ISSUE TITLE
Include terratest-maven-plugin in documentation

### ISSUE THREAD

**Issue by szgergo** [gruntwork-io/terratest#821]
Hi!

I have created a maven plugin for terratest. As this is a sort of contribution, I'd like to ask whether it is possible to include the plugin in the documentation page? Plus now I'm creating a website for the plugin, would that be possible to use some of the artwork of the main terratest page? Thank you!

The plugin: https://github.com/terratest-maven-plugin/terratest-maven-plugin

**Comment by brikis98** [comment]
Cool plugin! A PR to add it to the docs is welcome. Perhaps we should add a new page under "Testing best practices" called something like "Tools and plugins"? That would create a home for any 3rd party Terratest integrations, tools, etc.

**Comment by szgergo** [comment]
> Cool plugin! A PR to add it to the docs is welcome. Perhaps we should add a new page under "Testing best practices" called something like "Tools and plugins"? That would create a home for any 3rd party Terratest integrations, tools, etc.

Hi! Thank you :) I'll do it!
