### ISSUE TITLE
Azure Public IP address module not using sovereign client module

### ISSUE THREAD

**Issue by mjyeaney** [gruntwork-io/terratest#822]
The public IP address testing modules need modified to support Azure sovereign environments (if configured). This will require:

* Addition of new supporting methods in `/modules/azure/client_factory.go` for PublicIPAddress clients
* Modifying `/modules/azure/publicaddress*.go` to call into `client_factory.go` to ensure client instances are properly configured.
* Updating any tests impacted.

Will submit PR on this work when complete.

**Comment by HadwaAbdelhalem** [comment]
@yorinasub17 would you please close it, addressed in this merged PR https://github.com/gruntwork-io/terratest/pull/897

**Comment by yorinasub17** [comment]
Closing as done in #897
