### ISSUE TITLE
Azure Load balancer testing module not using sovereign client module

### ISSUE THREAD

**Issue by mjyeaney** [gruntwork-io/terratest#824]
The load balancer testing module needs modified to support Azure sovereign environments (if configured). This will require:

* Addition of new supporting methods in `/modules/azure/client_factory.go` for LoadBalancer clients
* Modifying `/modules/azure/loadbalancer*.go` to call into `client_factory.go` to ensure client instances are properly configured.
* Updating any tests impacted.

Will submit PR on this work when complete.

**Comment by HadwaAbdelhalem** [comment]
realted Pr merged https://github.com/gruntwork-io/terratest/pull/897. can we close it please

**Comment by yorinasub17** [comment]
Closing!
