### ISSUE TITLE
anyway i could get to contribute?

### ISSUE THREAD

**Issue by saiyanlevel5** [gruntwork-io/terratest#84]
After reading the contributions guideline, i decided to ask here itself.  Noticed that there is no open issues at this repo. Could i still get to participate and contribute in anyway?

**Comment by brikis98** [comment]
Great question, thanks! I filed a few issues we could use help with: https://github.com/gruntwork-io/terratest/issues. We'll add more over time :)

**Comment by saiyanlevel5** [comment]
great, I will pick away at one of them. Cheers!

**Comment by josh-padnick** [comment]
>  a) am i correct in assuming that i can see this functioning only if i have an already existing Golang code base which i can ran this tooling against?

Yes, you'll need to import Terratest as a Go library. In the [intro example](https://github.com/gruntwork-io/terratest#introduction), what's omitted from the top is something like:

```golang
package main

import (
	"github.com/gruntwork-io/terratest/terraform"
)
```

> b) I dont have any experience in working/dealign with IaC. I have worked a little with IaaS which is obviously different from IaC. I will take it as i am not the best candidate to contribute here?

I think you're probably better off learning Terraform first and trying to manage some basic infrastructure first. Once you've done that, you'll start to understand why testing that Terraform code is important. But in general, the larger your IaC codebase, the more it suffers by not being backed by automated tests.

> c) i really like your project and the development practices you have been following and asking for from contributors and would be interested to contribute if i can get some training in some way.

Check out https://blog.gruntwork.io/a-comprehensive-guide-to-terraform-b3d32832baca for a solid intro to Terraform.
