### ISSUE TITLE
[Terraform] Add Terraform Validate function

### ISSUE THREAD

**Issue by axilleastr** [gruntwork-io/terratest#855]
From what I've seen `terraform validate` is missing from the terratest available terraform functions. 
Is this intentionally or is it something that could be added? 

Thanks! :)

**Comment by brikis98** [comment]
Not intentional. PR to add it is welcome!

**Comment by axilleastr** [comment]
Awesome, thanks :)

**Comment by brikis98** [comment]
Fixed in #866 and released in https://github.com/gruntwork-io/terratest/releases/tag/v0.32.23.
