### ISSUE TITLE
[Azure] Add sovereign cloud support for resource group

### ISSUE THREAD

**Issue by davidkpiano** [gruntwork-io/terratest#859]
The Base URI is incorrectly resolved for the resource group client, and should be fixed to read from the environment.

Addresses #811

**Comment by HadwaAbdelhalem** [comment]
@yorinasub17 would you please close it, addressed in this merged PR https://github.com/gruntwork-io/terratest/pull/884

**Comment by yorinasub17** [comment]
Closing as done in #884
