### ISSUE TITLE
Find a way to save log files from servers

### ISSUE THREAD

**Issue by brikis98** [gruntwork-io/terratest#87]
We often use Terratest to:

1. Spin up one or more EC2 Instances by running `terraform apply`.
1. Wait for those Instances to boot and do something (e.g., form a cluster), usually by executing some sort of code as part of User Data.
1. Test that the Instances are working correctly.
1. Tear down the servers.

If the process of spinning up the EC2 Instances fails (step 1), we get an error from Terraform that makes it clear what went wrong. But if step 2 fails, then from the console where we ran `terraform apply`, we cannot see what wrong. That's because the error happened in the EC2 Instances, and Terraform has no visibility into what's happening with those. This makes it tougher to diagnose a test that failed in CI, as the error log you need is on an EC2 Instance that was already torn down per step 4. 

Our best workaround so far is to use the [AWS syslog APIs](https://github.com/gruntwork-io/terratest/blob/master/modules/aws/ec2-syslog.go#L16) to fetch the most recent data from syslog. However, not all apps write to syslog, and the APIs only give us the last X KB, so important data is often missing.

This issue is to explore the question of, what's the simplest solution we could build to be able to retrieve the log data from EC2 Instances and display it in `stdout` of the test so the user can diagnose it without having to SSH to the EC2 Instances?

**Comment by josh-padnick** [comment]
My dream is to have some UI layer that Terratest can stream logs to. Maybe there's even an API where the streams are directed so that logs are persisted and viewable for future builds. But this definitely isn't a simple approach so perhaps this is best as a commercial feature.

A simpler solution for this problem could be to stream logs into a buffer that periodically writes them to S3. One issue is that this needs to be a go routine because if Terratest panics, the logs immediately stop collecting.

**Comment by brikis98** [comment]
> My dream is to have some UI layer that Terratest can stream logs to. Maybe there's even an API where the streams are directed so that logs are persisted and viewable for future builds. But this definitely isn't a simple approach so perhaps this is best as a commercial feature.

A UI would be nice. But the key question is, what's the simplest way to get logs off an EC2 Instance? Do we have to update every example to install the CloudWatch log aggregation scripts? Is there something simpler we could run on the EC2 Instances just for testing?

> A simpler solution for this problem could be to stream logs into a buffer that periodically writes them to S3. One issue is that this needs to be a go routine because if Terratest panics, the logs immediately stop collecting.

It makes sense to stream logs form the EC2 Instance to S3, but what does Terratest and goroutines have to do with that?

**Comment by josh-padnick** [comment]
> It makes sense to stream logs form the EC2 Instance to S3, but what does Terratest and goroutines have to do with that?

I suppose another approach is to install an agent on your EC2 Instances, but my thought with Terratest is that we write a function that SSH's into the box, tails the desired log files, streams the output to a buffer, and periodically flushes the buffer to S3. Since there would be many logs being streamed at once, each log would be a go routine.

**Comment by davidneudorfer** [comment]
@brikis98 If you want to get the user data off the instance you can use the AWS API.

`aws ec2 get-console-output` -> [documentation](https://docs.aws.amazon.com/cli/latest/reference/ec2/get-console-output.html)

The following is a trick I use to get the logs in a nicer format:
```
get-logs() {
  aws ec2 get-console-output --instance-id $1 | \
  jq -r '.Output' | \
  awk '{gsub(/\\n/,"\n")}1' | \
  awk '{gsub(/\\r/,"\r")}1'
}
```

**Comment by brikis98** [comment]
@davidneudorfer Thanks for the pointer, but as mentioned in the bug description, we already have support for console output in the  [AWS syslog APIs](https://github.com/gruntwork-io/terratest/blob/master/modules/aws/ec2-syslog.go#L16). Unfortunately, those are limited to 64kb, most of which is noise from the Linux boot sequence. As a result, it misses a lot of the important log info you need.

**Comment by brikis98** [comment]
This was resolved via methods such as [FetchContentsOfFileFromInstance](https://github.com/gruntwork-io/terratest/blob/master/modules/aws/ec2-files.go#L26).
