### ISSUE TITLE
Terraform 0.15 requires `sensitive = true` for certain output variables based on RM provider

### ISSUE THREAD

**Issue by robcamer** [gruntwork-io/terratest#872]
Several modules require `sensitive=true` on the output variables that are marked sensitive by the resource provider.  See references below.

This PR addresses the issue for #azure modules.  

REFERENCES:
[Releases · hashicorp/terraform (github.com)](https://github.com/hashicorp/terraform/releases)
[Upgrading to Terraform v0.15 - Terraform by HashiCorp - sensitive output variables ](https://www.terraform.io/upgrade-guides/0-15.html#sensitive-output-values )

**Comment by HadwaAbdelhalem** [comment]
thanks @robcamer .This issue was addressed in this[ merged PR](https://github.com/gruntwork-io/terratest/pull/882) . @yorinasub17 could you please close this off.

**Comment by brikis98** [comment]
Thanks, closing now per @HadwaAbdelhalem's comment!
