### ISSUE TITLE
Running InitAndPlanE will always update modules

### ISSUE THREAD

**Issue by alan2wong** [gruntwork-io/terratest#877]
The Terraform Options struct includes the option to disable upgrading during `terraform init`, but even if this is set to false, an upgrade still occurs due to `terraform get -upgrade` always being called during `InitAndPlanE`:

- `InitAndPlanE` calls both `InitE` and `GetE`: https://github.com/gruntwork-io/terratest/blob/adca4a84bcddefbb7d6453fb8bd17da25f2ecd04/modules/terraform/plan.go#L19-L29
- `GetE` is set to always call `terraform get -update` which forces an update: https://github.com/gruntwork-io/terratest/blob/adca4a84bcddefbb7d6453fb8bd17da25f2ecd04/modules/terraform/get.go#L17-L19

The expected behavior is if `Upgrade` is set to false or not set, no upgrade should be run by either `init` or `get`.

**Comment by yorinasub17** [comment]
This is now fixed in https://github.com/gruntwork-io/terratest/releases/tag/v0.34.1, where the call to `get` is removed.
