### ISSUE TITLE
Fix the link to the test code

### ISSUE THREAD

**Issue by yusuke0701** [gruntwork-io/terratest#878]
The link to the test code in this README.md is incorrect.
https://github.com/gruntwork-io/terratest/blob/master/examples/terraform-gcp-example/README.md

incorrect: https://github.com/gruntwork-io/terratest/blob/master/test/terraform_gcp_example_test.go
correct: https://github.com/gruntwork-io/terratest/blob/master/test/gcp/terraform_gcp_example_test.go

**Comment by brikis98** [comment]
Thanks for reporting! Fix is here: https://github.com/gruntwork-io/terratest/pull/889.

**Comment by yusuke0701** [comment]
thanks
