### ISSUE TITLE
Add support for GCP

### ISSUE THREAD

**Issue by brikis98** [gruntwork-io/terratest#88]
Terratest has an [aws package](https://github.com/gruntwork-io/terratest/tree/master/modules/aws) with a number of utilities useful for AWS. It would be great to add similar utilities for testing code in GCP.

**Comment by Dahs81** [comment]
Is anyone working on this? If not, I would be willing to help out whenever I get available time.

I'm creating a checklist of the initial things that I'd like to see added, but anyone else can add to this list.  To help coordinate it, I make a couple checkboxes to notify others that it is started.  This way others can jump in and help if they'd like. I'm sure there's a better way to do this, but thought I'd try to get this

I'll probably try to do this in the following order:

#### storage.go/storage_test.go
- [ ] In Progress
- [ ] Pull Request
- [ ] Completed (Merged)

#### vpc.go/vpc_test.go
- [ ] In Progress
- [ ] Pull Request
- [ ] Completed (Merged)

#### accounts.go/accounts_test.go
- [ ] In Progress
- [ ] Pull Request
- [ ] Completed (Merged)

#### iam.go/iam_test.go
- [ ] In Progress
- [ ] Pull Request
- [ ] Completed (Merged)

#### OTHER"S HERE - Feel free to edit.

Let me know if this is already started or if you don't want to do it.

**Comment by Dahs81** [comment]
Ok. Cool. I'll start sometime soon.

**Comment by josh-padnick** [comment]
+1. We'd especially love to get our open source GCP modules ([consul](https://github.com/hashicorp/terraform-google-consul), [nomad](https://github.com/hashicorp/terraform-google-nomad), [vault](https://github.com/hashicorp/terraform-google-vault)) updated with automated tests. Those will also provide a good indication of what type of functionality we'll eventually want in Terratest. Thank you for taking the lead on this!

**Comment by Dahs81** [comment]
Looking into the examples/terraform-aws-example and test/terraform_aws_example_test.go, I only see a test for an instance.  Is there a place where you are testing things like s3 buckets, iam, etc? I'll do my best to add as many tests either way.  Just curious if there are some tests that I missed so I can see some examples. If not, no big deal.

**Comment by brikis98** [comment]
Most of the examples are pretty simple. I suppose the "real" test cases are our infrastructure repos:

1.  [Consul](https://github.com/hashicorp/terraform-aws-consul)
1.  [Vault](https://github.com/hashicorp/terraform-aws-vault)
1.  [Nomad](https://github.com/hashicorp/terraform-aws-nomad)
1.  [Couchbase](https://github.com/gruntwork-io/terraform-aws-couchbase/)

These make use of S3, IAM, load balancers, and so on, and have various Terratest tests. 

I suppose we should add more complicated examples to this repo too!

**Comment by Dahs81** [comment]
Ahh. Thanks. I'll take a look at those!

**Comment by git4raj** [comment]
Looking for more support for GCP CloudStorage such as BucketAttrs, access to labels, so we can verify the resources have the expected labels / attributes.

**Comment by brikis98** [comment]
We've supported GCP for a while in Terratest now.
