### ISSUE TITLE
Update terragrunt support to use terragrunt run-all plan / apply / destroy

### ISSUE THREAD

**Issue by DavidTamLloyds** [gruntwork-io/terratest#896]
Hello I have these version setup on a mac:

go version go1.16.3 darwin/amd64
terragrunt version v0.29.2
Terraform v0.15.3

terragrunt mostly work but I got this for destroy:

         	Error Trace:	destroy.go:18
        	Error:      	Received unexpected error:
        	            	FatalError{Underlying: error while running command: exit status 1; time=2021-05-11T17:41:27+01:00 level=warning msg='destroy-all' is deprecated. Running 'terragrunt run-all destroy -force -input=false -lock=false' instead. Please update your workflows to use 'terragrunt run-all destroy -force -input=false -lock=false', as 'destroy-all' may be removed in the future!

        	            	time=2021-05-11T17:41:27+01:00 level=info msg=Stack at ...:
        	            	╷
        	            	│ Error: Failed to parse command-line flags
        	            	│
        	            	│ flag provided but not defined: -force
        	            	╵
        	            	╷
        	            	│ Error: Too many command line arguments
        	            	│
        	            	│ Expected at most one positional argument.

I looked at the code:
https://github.com/gruntwork-io/terratest/blob/8ef5dc3151259bfdc80a271e10e7e68d0b56d854/modules/terraform/apply.go#L59
https://github.com/gruntwork-io/terratest/blob/8ef5dc3151259bfdc80a271e10e7e68d0b56d854/modules/terraform/plan.go#L124
https://github.com/gruntwork-io/terratest/blob/8ef5dc3151259bfdc80a271e10e7e68d0b56d854/modules/terraform/destroy.go#L33

does it make sense to have these change to:
```sh
terragrunt run-all apply
```
etc...?

or at the very least remove _-force_ in destroy so that it works?

**Comment by brikis98** [comment]
Oh, good point! Yes, we should switch to `run-all` and remove the deprecated flags. A PR to do this is very welcome, as we're buried at the moment.

**Comment by davidtam** [comment]
ok thanks I will try creating a PR...
