### ISSUE TITLE
defer Destroy should go before InitAndApply

### ISSUE THREAD

**Issue by mastertinner** [gruntwork-io/terratest#90]
In some of the documentation, the deferral of the destruction of resources comes after the `InitAndApply` function is executed. This can lead to problems if InitAndApply aborts the test because then the `defer` statement is never called. I think we should change all the examples to have the following order:

```go
defer terraform.Destroy(t, terraformOptions)
terraform.InitAndApply(t, terraformOptions)
```

It's already implemented like that in all the example tests but not in the documentation. This would solve the problem of new users having to clean up resources manually if `InitAndApply` fails and aborts the test.

**Comment by brikis98** [comment]
Good catch! Fixed in https://github.com/gruntwork-io/terratest/commit/6cdf23d995d529790f3ce8ece57a6790b2ad33ba.

**Comment by mastertinner** [comment]
Nice. Thanks for the quick fix!
