### ISSUE TITLE
Add support for Vultr

### ISSUE THREAD

**Issue by gruberdev** [gruntwork-io/terratest#900]
### Why Vultr? 
I've noticed there are pending integrations that in terms of market share should come prior to integrating a lesser known VPS-providers, where companies like DigitalOcean come to mind as they already have an open issue regarding plans of integration with Terratest.  Nonetheless, I do think a Vultr integration will be useful regardless of the company's representation or expansion in terms of market share, as Vultr themselves and its userbase focuses more on Infrastructure with CI/CD methodologies and the use of Terraform than the average cloud provider, creating a synergy with Terratest's objective. 

<details>

  <summary>
   Personal context (Optional)
  </summary> 

<br>

Disclaimer: I do not work for Vultr nor receive financial incentives from them.

For both professional and personal use, Vultr has been my provider of choice compared to other cloud providers. Their high-frequency CPUs machines is perfect for creating k3s mini-clusters and their perfomance compared to its peers made me choose them for most of my infrastructure in terms of resources to how much I have to spend (considering I have to pay in non-USD currency doing conversions, so every dollar counts). 

Most of my terraform charts have been made integrated with their CLI and API solutions.

</details>

### Highlights

- [An API in Go already exists](https://github.com/vultr/govultr)
- [Vultr's Infrastructure team provides Terraform charts and integrations (see packages inside of the module)](https://github.com/vultr/terraform-vultr-condor)
- I'm not sure as I'm not part of Vultr's team nor have any sort of contact with them, but I'd guess they would offer support to Terratest, as they're very active in both open-source and terraform communities, this is especially important to consider in terms of providing long-term support to new versions of the API library for example.

I could create a fork today to start the work, but as I've read the [contribution guidelines](https://terratest.gruntwork.io/docs/community/contributing/), it is specifically mentioned I should create an issue to discuss wether this should be done or not before that, so I think this issue acts as a starting point to hear the community and the development team opinions wether is worth to pursue this integration or not. Thank you for your time.

**Comment by brikis98** [comment]
Thanks for raising this issue. We'd love to add support for many other clouds/providers, but as per the "Platforms" section of our [contribution guide](https://terratest.gruntwork.io/docs/community/contributing/#infrastructure-and-validation-helpers), right now, our small team can only support AWS, Azure, GCP, and Kubernetes. To be honest, we just don't have the resources to maintain anything else. 

If someone wishes to create a separate repo with Terratest plugins for other clouds, and to maintain it, we'd be happy to add it to the [tools and plugins](https://terratest.gruntwork.io/docs/testing-best-practices/tools-and-plugins/) page.
