### ISSUE TITLE
Feature request: parametrise timeout of HttpHelper

### ISSUE THREAD

**Issue by darmach** [gruntwork-io/terratest#902]
Default 10 seconds of timeout of http.Client here: https://github.com/gruntwork-io/terratest/blob/737e05c04c19e2a4f01a460f91ea24161540c772/modules/http-helper/http_helper.go#L164 is a bit too short for me -  it's used on part of the infrastructure that has some intermittent lags, and I can't do anything about it (vendor issue)

HttpDo is referenced by other HttpDo* request functions, so this would be useful in all of them - can the timeout be parametrized, and default to 10 if not defined otherwise?

**Comment by brikis98** [comment]
It can, but it's not easy to do so in Go in a backwards compatible way. I'm also worried about adding yet another parameter to the already long function signatures in `http_helper`. 

Probably what we need to do is refactor the `http_helper` methods to take in an `Options` struct. That struct can contain `tlsConfig`, `retries`, `sleepBetweenRetries`, this new `timeout` setting, etc. What's nice is that the struct would be extensible, so we could add new params in a backwards compatible way, without too much verbosity, in the future.

A PR to do this is welcome.

**Comment by darmach** [comment]
This makes a lot of sense, I will try to do that if I have some spare time.

**Comment by denis256** [comment]
Options for HTTP requests were introduced in v0.40.11

https://github.com/gruntwork-io/terratest/releases/tag/v0.40.11
