### ISSUE TITLE
[Azure] Unable to check if key vault secret exists using environment variables

### ISSUE THREAD

**Issue by victornoventa** [gruntwork-io/terratest#903]
I have had issues while running my tests that rely on `modules/azure/keyvault` to check if a secret exists. I have everything set as the instructions tell me to do and everything goes fine with my service principal information set as environment variables. But I can't check if a secret exists because it relies on Az CLI instead. Is there any specific reason for having this relying on `NewAuthorizerFromCLI`

https://github.com/gruntwork-io/terratest/blob/d1ce8bed7e5253cfa5a5c24da0a29caa47e2dcfd/modules/azure/keyvault.go#L127

Instead of relying on `NewAuthorizerFromEnvironment`?

https://github.com/Azure/azure-sdk-for-go/blob/master/services/keyvault/auth/auth.go#L19

I mean, I've seen other places using this Authorizer instead:

https://github.com/gruntwork-io/terratest/blob/d1ce8bed7e5253cfa5a5c24da0a29caa47e2dcfd/modules/azure/authorizer.go#L24

**Comment by HadwaAbdelhalem** [comment]
Operations on Azure Keyvault are 2 groups, first group "Management plan "that creates, update or detele the vault and set the permissions on it. the second group "Data plan" that add, updates, retrieve, or deletes the values stored within the vault

To run any operation on the data within azure keyvault you need to use a data plan Authorizer, while the remaining resources operations are using the management plan authorizer. 

For more details please check [this](https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/control-plane-and-data-plane)

**Comment by HadwaAbdelhalem** [comment]
@victornoventa a fix was merged to address this issue.
