### ISSUE TITLE
Use testing.TestingT instead of *testing.T in terraform/options.go

### ISSUE THREAD

**Issue by cbascom** [gruntwork-io/terratest#908]
The WithDefaultRetryableErrors function in `terraform/options.go` should use the type `testing.TestingT` instead of `*testing.T` for its argument.

This should be changed to allow for easier usage of the ginkgo framework, as it is not possible to pass the GinkgoT() type.
This also makes it consistent with the rest of the terraform functions that already accept `testing.TestingT`.

**Comment by urohit011** [comment]
Can I take this one?

**Comment by cbascom** [comment]
My PR to fix this was already merged, #909 above. I think it just not closed yet since a new release containing the fix isn't available yet.

**Comment by urohit011** [comment]
Okay, that's cool.

**Comment by brikis98** [comment]
This was released in https://github.com/gruntwork-io/terratest/releases/tag/v0.34.9.
