### ISSUE TITLE
[Feature] k8s.KubectlKustomize (template generation)

### ISSUE THREAD

**Issue by dzmitry-lahoda** [gruntwork-io/terratest#915]
Like wrapper around Apply(KubectlApply)

https://kubernetes.io/docs/tasks/manage-kubernetes-objects/kustomization/

Allows pod per test templating

**Comment by dzmitry-lahoda** [comment]
better use kustomize as separate tool because kubectl of latest version still deployed with old kustomize

**Comment by dzmitry-lahoda** [comment]
may be run conditionally (separate too or kubectl)

**Comment by yufeiminds** [comment]
I forked the repo and added the `-k` argument with related methods.

- `KubectlApplyFromKustomize`
- `KubectlApplyFromKustomizeE`
- `KubectlDeleteFromKustomize`
- `KubectlDeleteFromKustomizeE`

It worked in my usage. 😄
