### ISSUE TITLE
FindS3BucketWithTag can fail by listing tags on a deleted bucket

### ISSUE THREAD

**Issue by gigyas** [gruntwork-io/terratest#928]
Occassionally, FindS3BucketWithTag will fail like this:
```
Error: Received unexpected error:
          NoSuchBucket: The specified bucket does not exist
          status code: 404, request id: Y4FJTRQYC6GEKP13, host id: U8Mu38...
```
It appears that this is because the ListBuckets API can return a bucket that has been deleted, but hasn't been removed from S3 yet: https://aws.amazon.com/premiumsupport/knowledge-center/s3-listing-deleted-bucket/

Terratest Version: `v0.35.6`

**Comment by brikis98** [comment]
Thanks for the bug report. Sounds like a frustrating issue. I'm guessing we'll need to either find a way to handle that specific error and ignore it in that method. A PR to fix that is very welcome!
