### ISSUE TITLE
Can I use terratest with vmware vsphere?

### ISSUE THREAD

**Issue by mevinod** [gruntwork-io/terratest#929]
My org has self hosted vmware vsphere and we are installing kube and few other things on top of vmware. Can I use terratest to validate the deployment? Is there any documentation on it?

**Comment by brikis98** [comment]
Terratest has native helpers for working with AWS, GCP, Azure, Kubernetes, Docker, Packer, Linux (via SSH), and a few other things. So if you're using any of these technologies, Terratest helpers may be of use to you. There are no native helpers for VMWare, so if you need direct helpers for that, you'll have to create them yourself.
