### ISSUE TITLE
Terratest failing to destroy internetgateway 

### ISSUE THREAD

**Issue by surendarkaniops** [gruntwork-io/terratest#932]

**Comment by brikis98** [comment]
Could you provide a bit more context please? What tests? What does the code look like? What does the log output look like?

**Comment by surendarkaniops** [comment]
Hi @brikis98, Thank your for your response. issue got resolved.

I was setup ECS EC2 container instance with ASG. When i am trying to destroy the setup it is not deleting the IGW and i narrow down the issue. ASG not properly drained during the terraform destroy so that IGW not get deleted. Now i just drained the ASG manually and terraform destroy all the resources
