### ISSUE TITLE
Add GOCACHE=off to best practises

### ISSUE THREAD

**Issue by mastertinner** [gruntwork-io/terratest#94]
Since Go 1.10, test results get cached. This leads to the tests not being run sometimes because Go has cached the results and just assumes it will get the same results because the Go code hasn't changed. We should add a point to the documentation "Testing best practises" that asks users to set the `GOCACHE` environment variable to `off` for terratests:

```shell
$ GOCACHE=off go test -v -timeout 45m ./...

```

**Comment by brikis98** [comment]
Oh, interesting, I had not heard about this. Where can I find more info on `GOCACHE`?

**Comment by mastertinner** [comment]
I learned about it from here: https://github.com/golang/go/issues/22758

**Comment by brikis98** [comment]
Heh, that's quite hidden. Good find though.

Would you be up for a quick PR to add this as a note to the README?
