### ISSUE TITLE
Support for Azure FuncApp, WebJob and App services

### ISSUE THREAD

**Issue by prasadautomationtesting** [gruntwork-io/terratest#949]
Is there any support in existing library to test the following resources Funcapp, WebJob and App Services for Azure cloud?

**Comment by HadwaAbdelhalem** [comment]
There are couple old opened [PRs](https://github.com/gruntwork-io/terratest/pull/591/files) to add the modules, and there are plans to get those updated and merged in the next couple weeks

**Comment by prasadautomationtesting** [comment]
I could see reference for App services and FuncApp but not for Webjob? Do you have any update for it as well?

https://github.com/gruntwork-io/terratest/pull/591/files

**Comment by prasadautomationtesting** [comment]
Any updates on Webjob?

**Comment by HadwaAbdelhalem** [comment]
no plan for webjobs on the radar soon
