### ISSUE TITLE
Azure terratest module instalation error

### ISSUE THREAD

**Issue by prasadautomationtesting** [gruntwork-io/terratest#950]
GoLang: Latest to the market.

I am getting the following error while installing azure module.

**code:**

    package test
    
    import (
    	"testing"
    	"github.com/Azure/azure-sdk-for-go/profiles/latest/cosmos-db/mgmt/documentdb"
    	"github.com/gruntwork-io/terratest/modules/azure"
    	"github.com/stretchr/testify/assert"
    )
    
    func TestTerraformAzureCosmosDBExample(t *testing.T) {
    	foo
    	boo
    }

**Execution:**

    C:\foo\boo>go test -v
    # foo_test
    foo_test.go:6:2: no required module provides package github.com/gruntwork-io/terratest/modules/azure; to add it:
            go get github.com/gruntwork-io/terratest/modules/azure
    FAIL    foo_test [setup failed]

**Error:**

    C:\foo\boo>go get github.com/gruntwork-io/terratest/modules/azure
    # github.com/gruntwork-io/terratest/modules/azure
    C:\foo\go\pkg\mod\github.com\gruntwork-io\terratest@v0.36.5\modules\azure\keyvault.go:139:50: too many arguments in call to "github.com/Azure/azure-sdk-for-go/services/keyvault/auth".NewAuthorizerFromFile
            have (string)
            want ()
    C:\foo\go\pkg\mod\github.com\gruntwork-io\terratest@v0.36.5\modules\azure\resourcegroup.go:78:9: cannot use &rg (type *"github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2020-10-01/resources".Group) as type *"github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2020-06-01/resources".Group in return argument
    C:\foo\go\pkg\mod\github.com\gruntwork-io\terratest@v0.36.5\modules\azure\resourcegroup.go:100:18: cannot use rg.Values() (type []"github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2020-10-01/resources".Group) as type []"github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2020-06-01/resources".Group in return argument

what changes required to get rid of this error?

**Comment by paddymorgan84** [comment]
I've encountered this, and I think it's an issue with how the `github.com/Azure/azure-sdk-for-go` package is versioned. Looking at the [Go Module reference](https://golang.org/ref/mod#incompatible-versions):

> A module released at major version 2 or higher must have a matching major version suffix on its module path. For example, if a module is released at v2.0.0, its path must have a /v2 suffix. This allows the go command to treat multiple major versions of a project as distinct modules, even if they're developed in the same repository.

> The major version suffix requirement was introduced when module support was added to the go command, and many repositories had already tagged releases with major version 2 or higher before that. To maintain compatibility with these repositories, the go command adds an +incompatible suffix to versions with major version 2 or higher without a `go.mod` file. +incompatible indicates that a version is part of the same module as versions with lower major version numbers; consequently, the go command may automatically upgrade to higher +incompatible versions even though it may break the build.

The `github.com/Azure/azure-sdk-for-go` package doesn't have a `go.mod` file, which means it will be marked as `+incompatible` and subsequently be vulnerable to build breakages as you've encountered. My guess is you've got a more up to date version of `github.com/Azure/azure-sdk-for-go` on your machine than what `terratest` is expecting; as it stands `terratest` is referencing `v46.0.0`, while the latest available is `v55.6.0`.

I downgraded to `v0.35.3` of `terratest` to get this working, as these two changes exposed the issue:

- #945 (Uses `github.com/Azure/azure-sdk-for-go/services/keyvault/auth`)
- #912 (Uses `github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2020-06-01/resources`)

You could also downgrade `github.com/Azure/azure-sdk-for-go` to match `terratest`

```
go get github.com/Azure/azure-sdk-for-go@v46.0.0 
```

Ideally, `github.com/Azure/azure-sdk-for-go` would be converted to a module, but in the absence of that, maybe the `go.mod` file here could be bumped to the latest version of `github.com/Azure/azure-sdk-for-go` and fix any issues that arise from that?
