### ISSUE TITLE
Terratest seems to not being able to parse HCL JSON files

### ISSUE THREAD

**Issue by rescDev** [gruntwork-io/terratest#954]
First of all, thanks for this awesome project :)

I currently want to provide input configuration with HCL JSON files (`xyz.tfvars.json`) and get single variables via `GetVariableAsStringFromVarFile`.

```go
terraformOptions := terraform.WithDefaultRetryableErrors(t, &terraform.Options{
	TerraformDir: "../",
	VarFiles:     []string{"test.tfvars.json"},
})

project := terraform.GetVariableAsStringFromVarFile(t, "./test.tfvars.json", "project_id")
```

However, also when looking into the code, it seems like terratest only supports parsing of HCL (`.tfvars`) files for `GetVariableAsStringFromVarFile`. The error message when executing the test usually looks like

```
Error:          Received unexpected error:
                   test.tfvars.json:1,1-2: Argument or block definition required; An argument or block definition is required here.
```

**Comment by rescDev** [comment]
seems to be like a small update at https://github.com/gruntwork-io/terratest/blob/3d07a977796fb851a802288d89ff7f42a9071f0a/modules/terraform/var-file.go#L149 would fix this issue, as the parser also provides a `ParseJSON` function

**Comment by brikis98** [comment]
https://github.com/gruntwork-io/terratest/releases/tag/v0.37.7
