### ISSUE TITLE
Retry Plan & Apply when provider errors

### ISSUE THREAD

**Issue by dkirrane** [gruntwork-io/terratest#955]
A Terraform provider I use fails with 2 intermittent errors that tend to pass after re-running terraform plan & apply.

Is it possible to configure Terratest to retry a given resource if it fails with Error or fails with specific error message?

**Comment by yorinasub17** [comment]
The closest thing we have is [RetryableTerraformErrors](https://github.com/gruntwork-io/terratest/blob/142b643d20c78afaaf4a5ab6687ff01a70aa7c21/modules/terraform/options.go#L59) on the Options struct, which will retry the last terraform command when the output matches the given regex. You will also want to configure `MaxRetries` and `TimeBetweenRetries`.

We don't have anything that retries on a resource level. In theory, we can implement such a feature using `-target`, but given the amount of parsing required on the terraform output, I don't think it is practical to implement something like that.

Will close as answered.
