### ISSUE TITLE
Add upgrade option to Terraform

### ISSUE THREAD

**Issue by mastertinner** [gruntwork-io/terratest#96]
When running terratests locally, it doesn't automatically upgrade to the latest version of providers and modules. Terraform solves that by having an `-upgrade=true` flag. It would be great if this flag was part of `terraform.Options`.

```go
type Options struct {
        ...
        Upgrade    bool    // Whether the -upgrade flag of the terraform init command should be set to true or not
}
```

**Comment by brikis98** [comment]
Seems like a good addition. PR welcome!
