### ISSUE TITLE
Include '.terraform-version' file when copying Terraform folder to temporary location

### ISSUE THREAD

**Issue by yardbirdsax** [gruntwork-io/terratest#962]
As a developer using Terratest and also using [tfenv](https://github.com/tfutils/tfenv) to ensure the correct version of Terraform is used when deploying, I would like to ensure that the `.terraform-version` file [used by `tfenv`](https://github.com/tfutils/tfenv#terraform-version-file) is copied when I use Terratest to make temporary copies of my Terraform code for testing. That way, when tests are run I can make sure they use the same version of Terraform that will be used in actual deployments.

**Comment by infraredgirl** [comment]
https://github.com/gruntwork-io/terratest/releases/tag/v0.38.8
