### ISSUE TITLE
Running Terratest applies twice to test two versions of a module

### ISSUE THREAD

**Issue by FrankieSanzica** [gruntwork-io/terratest#973]
Hello,

I was wondering if Terratest could accomplish the following use case.

1) Init, apply, deploy a Terraform module.  
2) I then download a different version of the same module.
3) run a Terraform apply again using the first module's state, testing the module changes.
4) destroy

I was following this: https://github.com/gruntwork-io/infrastructure-as-code-testing-talk/blob/12ef283ae814020b167950802aae10b6e58e0231/test/proxy_app_integration_with_stages_test.go.

However, I'm having difficulty assigning the Terraform options to a new directory but using the first apply's state.

**Comment by yorinasub17** [comment]
The best way to achieve this is to codegen (or support in the module) a way to configure the `local` backend to use a common path for the local terraform state. See the [terraform docs on local backend](https://www.terraform.io/docs/language/settings/backends/local.html) for more info.

**Comment by yorinasub17** [comment]
Alternatively, you can use [-backend-config](https://github.com/gruntwork-io/terratest/blob/master/modules/terraform/options.go#L58) to set the local backend path. See https://www.terraform.io/docs/language/settings/backends/configuration.html#partial-configuration for more info on how that CLI param works.

**Comment by FrankieSanzica** [comment]
> Alternatively, you can use [-backend-config](https://github.com/gruntwork-io/terratest/blob/master/modules/terraform/options.go#L58) to set the local backend path. See https://www.terraform.io/docs/language/settings/backends/configuration.html#partial-configuration for more info on how that CLI param works.

Thanks for the quick reply.  I have tried the following:

```
	currentOptions := &terraform.Options{TerraformDir: "tmp/current", BackendConfig: map[string]interface{}{
		"path": "tmp/backend.tf",
	}}

	upgradeOptions := &terraform.Options{TerraformDir: "tmp/upgrade", BackendConfig: map[string]interface{}{
		"path": "tmp/backend.tf",
	}}
```

When I run that, I see the following:

```
TestModuleUpgrade 2021-08-13T17:15:19-04:00 logger.go:66: Running command terraform with args [init -upgrade=false -backend-config=path=tmp/backend.tf]
```

As you can see it's setting the flag **-backend-config=path=tmp/backend.tf**.  However according to the [docs](https://www.terraform.io/docs/language/settings/backends/configuration.html#partial-configuration): it should be **-backend-config=tmp/backend.tf**

Is there a better way to do this or am I missing something?

**Comment by yorinasub17** [comment]
> As you can see it's setting the flag -backend-config=path=tmp/backend.tf. However according to the docs: it should be -backend-config=tmp/backend.tf

Ah we don't support this format yet (see this open PR: https://github.com/gruntwork-io/terratest/pull/558). You should use the `Command-line key/value pairs` format of setting this. In this case, the `path` kv pair actually points to the path to the state file.

**Comment by FrankieSanzica** [comment]
@yorinasub17 thank you for all of your help.  I was able to get it all working by throwing a *backend.tf* file in each module folder:

```
 terraform {
  backend "local" {
    path = "../terraform.tfstate"
  }
}
```
And then setting the following Terraform options in Terratest:

```
currentOptions := &terraform.Options{TerraformDir: "tmp/current"}
upgradeOptions := &terraform.Options{TerraformDir: "tmp/upgrade", MigrateState: true}
```
