### ISSUE TITLE
AWS/SSM module windows support

### ISSUE THREAD

**Issue by srg1177** [gruntwork-io/terratest#978]
Hello

There is a problem with AWS/SSM module CheckSSMCommandWithClientE(), it does not support Windows platform becouse of the hardcoded [AWS-RunShellScript](https://github.com/gruntwork-io/terratest/blob/master/modules/aws/ssm.go#L192) Commant Document.

`UnsupportedPlatformType: Cannot perform operation for instance id ########### of platform type Windows`

**Comment by infraredgirl** [comment]
Thanks for the bug report, @srg1177! A PR contributing the fix for this would be most welcome.

**Comment by srg1177** [comment]
hi @infraredgirl can you please grand me access ?)

**Comment by infraredgirl** [comment]
Fixed in #981.

**Comment by infraredgirl** [comment]
https://github.com/gruntwork-io/terratest/releases/tag/v0.37.9
