### ISSUE TITLE
No 'GetTagsForVpc()', helper function (and other 'GetTags...' functions)

### ISSUE THREAD

**Issue by SphenicPaul** [gruntwork-io/terratest#995]
There doesn't appear to be any helper function for obtaining the 'Tags' for AWS VPCs - There seems to be something similar for AWS EC2 instances in [here](https://github.com/gruntwork-io/terratest/blob/737e05c04c19e2a4f01a460f91ea24161540c772/modules/aws/ec2.go#L224) but nothing for AWS VPCs.

Additionally, I suspect there are other resources that would benefit from being able to obtain the tags so these can be tested as part of builds/tests etc. - Subnet, users, roles etc. are others - Actually, there doesn't seem to be a file/script for 'subnet(s)' within this 'AWS' module - Is it worth creating one to support this initial functionality I have (or is there something located somewhere else that I'm missing)?

I might create a PR for some of the resources I initially require tags for but I just want to ensure that these would be suitable/wanted. Resources supporting tagging are on [this](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Using_Tags.html) page.

Shout if you've any questions.

**Comment by yorinasub17** [comment]
I think that is reasonable! For VPC, I might prefer updating [the Vpc struct](https://github.com/gruntwork-io/terratest/blob/master/modules/aws/vpc.go#L15-L20) that gets returned by the getter functions to include the tags.

Although these functions most likely fail the `Complexity` litmus test mentioned in [type of contributions we accept](https://terratest.gruntwork.io/docs/community/contributing/#types-of-contributions), we have a hidden criteria of `Completeness`, and retrieving tags so you can check them is a basic function of most testing, so it makes sense to add them in under that criteria.

PRs to add these are welcome!
